### ISSUE TITLE
Veterans profile

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#101]
For example, http://operationcode.org/veteran/davidmolina

Criteria: 
- Veterans sign up, secured log-in
- Upload photo, update short bio, auto-update GitHub contributions
- Current position, and/or side project 
- Skills sets by tags/category by programming language interest (pre-loaded tags)
- Talks and presentations
- Blog feed from their individual blog

**Comment by rickr** [comment]
May I suggest making Veteran Profiles a milestone and creating the bullet points as issues under the milestone? 

We probably would need (in rough order): 
* Sign up, Sign In (aka AuthZ)
* Add fields to veteran model (photo, bio, github, talks, needs_mentor, is_mentor etc)
* Display veteran profile (maybe have an option for public/private profiles)

**Comment by davidmolina** [comment]
That sounds phenomenal!

**Comment by rickr** [comment]
Created a milestone with this info in it: https://github.com/OperationCode/operationcode/milestones/Veteran%20Profiles

I created 1 issue for each of these items as well. Are you OK with me closing this issue out and tracking progress via the milestone?

**Comment by davidmolina** [comment]
Sure. Thx. That works.

On Tue, Mar 22, 2016 at 12:40 PM, Rick <notifications@github.com> wrote:

> Created a milestone with this info in it:
> https://github.com/OperationCode/operationcode/milestones/Veteran%20Profiles
>
> I created 1 issue for each of these items as well. Are you OK with me
> closing this issue out and tracking progress via the milestone?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/101#issuecomment-199981760>
>



-- 
David Molina
https://about.me/molina
