### ISSUE TITLE
Slack Invite Bot Not Working

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#102]
Slack is failing to send our veterans an automatic email. 

Code:
https://github.com/OperationCode/operationcode/blob/master/app/controllers/veterans_controller.rb

**Comment by nellshamrell** [comment]
Hi @davidmolina, I just looked into this and it seems like the code is working in development mode (at least, the job is queuing correctly).  Is there anything from the Sidekiq log or application log when someone tries to do this on the production site?

**Comment by davidmolina** [comment]
Not sure. 

Don't have the user/pass. Can we check in Heroku?

**Comment by nellshamrell** [comment]
That is a good question.  Let me do some research.

**Comment by davidmolina** [comment]
Got another note this week (Twitter). A veteran didn't get an auto-invite to Slack.
