### ISSUE TITLE
Add a success message to the 'Join' page

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#115]
To repro:
* Visit https://operationcode.org/action
* Fill in the form
* Submit the form

Currently there is no success flash or other visual indication that your form has been submitted.

There should be a success flash and maybe a message that explains what to explain next.

**Comment by davidmolina** [comment]
@rickr Agree. Something along [these lines](http://getbootstrap.com/javascript/#alerts).

**Comment by davidmolina** [comment]
In fact, need to add to Stripe donation as well.

**Comment by rickr** [comment]
Closing this since the login process has changed.
