### ISSUE TITLE
Add an iOS page

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#118]
All things [ios](https://operationcode.org/ios) with a landing.

**Comment by rickr** [comment]
First step: find a volunteer in our IOS channel to give us some good tutorials, first steps, blogs etc.

**Comment by david-le** [comment]
I can provide some tutorials and guidance on learning iOS. Only problem is that I don't know Ruby or any web languages to actually code into a webpage. Is there a template of some sort, maybe I could just drop the links and modify items? Any other suggestions?

**Comment by davidmolina** [comment]
Can you duplicate `/jsguide`?

**Comment by rickr** [comment]
If you'd l like to take a look at https://github.com/OperationCode/operationcode/issues/199 and use that as an outline you could just create a text doc and submit that. One of us can convert it to HTML.

**Comment by david-le** [comment]
I'd be curious to check out '/jsguide'. I can give it a whirl, if not, I can do the text doc. Which directory is '/jsguide' located?

**Comment by davidmolina** [comment]
It's in pages now: 
https://github.com/OperationCode/operationcode/blob/master/app/views/pages/jsguide.html.erb

**Comment by rickr** [comment]
Closing this out due to lack of activity. Please feel free to open a new issue if this is still needed.
