### ISSUE TITLE
Add an Android page

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#119]
All things [android](https://operationcode.org/android) with a landing.

**Comment by rickr** [comment]
First step: find a volunteer in our android channel to give us some good tutorials, first steps, blogs etc.

**Comment by jdspringr07** [comment]
Created the page and reference. If pulled down located: localhost:3000/android for developing. There are no links on the page currently using it, but can use this site for design.

**Comment by rickr** [comment]
Closing this out due to lack of activity. Please feel free to open a new issue if this is still needed.
