### ISSUE TITLE
Add user analytics

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#120]
There should be a way to track what users are doing, what pages they are viewing, and other various metrics that could help streamline signup, donations, etc.

Some examples are google analytics, piwik, clicky.

**Comment by davidmolina** [comment]
@rickr Absolutely. @nellshamrell integrated New Relic, but will look into Google Analytics. 

Do we know of any heat mapping open source project?

**Comment by rickr** [comment]
I think all the open source stuff that can do that (piwik, OWA) is self hosted. 

I also found https://www.ptengine.com/plan which is free for 1k page views/mo but that's not open source.

**Comment by davidmolina** [comment]
Awesome... I'm having trouble w/ my SSH keys. I transferred over the
/operationcode app to a new Heroku account separate from my personal repos
(bilingualhire). Lost push capabilities to "origin" or GitHub. But either
way, it's a real good idea.

On Thu, Mar 10, 2016 at 9:28 PM, Rick <notifications@github.com> wrote:

> I think all the open source stuff that can do that (piwik, OWA) is self
> hosted.
>
> I also found https://www.ptengine.com/plan which is free for 1k page
> views/mo but that's not open source.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/120#issuecomment-195200584>
> .
>



-- 
David Molina
https://about.me/molina

**Comment by hollomancer** [comment]
Looking at Google Analytics on this

**Comment by hollomancer** [comment]
Anything further on this, or can it be closed?

**Comment by davidmolina** [comment]
Think we're good.
