### ISSUE TITLE
Jekyll rake task runs on every rake task

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#121]
Code inside jekyll.rake is namespaced but not placed into a task causing it to run every time rake is invoked.

**Comment by davidmolina** [comment]
Oh, snap.

**Comment by davidmolina** [comment]
@rickr so just 'git pull?'

**Comment by rickr** [comment]
@davidmolina It's been a while since I've accepted a PR on github but there should be a button someone that says something like 'Merge'. Click that and the fix goes into master. Then you can git pull on your local copy of this repo.

**Comment by davidmolina** [comment]
Understood.
