### ISSUE TITLE
Automatically run tests on pull requests

### ISSUE THREAD

**Issue by nellshamrell** [OperationCode/operationcode#125]
Add Travis or a similar service to automatically run tests on all pull requests

**Comment by rickr** [comment]
I think this is a dup of #59?

**Comment by davidmolina** [comment]
Yep

On Mon, Mar 14, 2016 at 1:38 PM, Rick <notifications@github.com> wrote:

> I think this is a dup of #59
> <https://github.com/OperationCode/operationcode/issues/59>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/125#issuecomment-196511699>
> .
>



-- 
David Molina
https://about.me/molina

**Comment by rickr** [comment]
Closing due to dup (#59)
