### ISSUE TITLE
Add dollar amount options and recurring donations to donate page

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#128]
https://operationcode.org/donations/new

**Comment by Wimsy113** [comment]
Do you want a dropdown for this? is this what you're asking for?

**Comment by davidmolina** [comment]
Maybe.

I was envisioning Boolean (choices) and recurring option, but open to other options.

**Comment by rickr** [comment]
Some good ideas from #156:

Add checkbox: [] Given in memory or honor of...
Add recurring checkbox []: Make this a monthly donation

**Comment by rickr** [comment]
Here is what it should look like:
![donate_example](https://cloud.githubusercontent.com/assets/334550/16709845/6728d7b2-45ea-11e6-9641-01fee8476244.png)

**Comment by rickr** [comment]
Closing this out due to lack of activity. Please feel free to open a new issue if this is still needed.
