### ISSUE TITLE
Make requesting a mentor explicit on login form

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#130]
* Add a checkbox to request a mentor
* If the box is checked on form submit:
  * Notify the slack mentor channel

**Comment by davidmolina** [comment]
Mentor by language? Maybe pick 3?

**Comment by jjhampton** [comment]
@davidmolina I like the 'mentor by language' idea.  Having general mentors in any area of software development is great, and I've learned a good amount by comparing/constrasting across different languages/frameworks/syntax.  But ideally, I think that students having technical mentors that are skilled in the same language that they are learning would be ideal.

On the other hand, it could also be useful to have a checkbox request option for people who are unaware of what language they'd like to learn.   Something like 'I'm unsure of what language to specialize in'.  I see plenty of posts in the Slack (and elsewhere) from beginners very new to coding who simply want some guidance in specifically -what- paths/languages to focus on.

**Comment by rickr** [comment]
I think a happy medium would be areas of expertise. Maybe something like
(pick one)

* Web Dev
* Mobile
* Platform (or whatever C, C++, ML etc would be called)

**Comment by jdspringr07** [comment]
It would be a cool idea to offer the option, but I wouldn't make it mandatory. :+1:

**Comment by davidmolina** [comment]
Software developers often ask they'd like to help and mentor. Maybe we just have a page for them to help and a seperate sign up.

**Comment by rickr** [comment]
This was done in #250
