### ISSUE TITLE
Add a calendar/schedule to the website

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/operationcode#133]
This is a follow-on to our discussion yesterday @davidmolina : 

To encourage more direct collaboration & involvement between people on Operation Code, we could set up some type of calendar on the website that would list any events that we'd like to regularly schedule.  Display & track a "battle rhythm" of stuff going on every week or so. 

Examples: 
* Small-group pair-programming sessions, tailored per language ( allow users to sign up / meet up to solve code katas / code challenges together)
* Screencasts or live coding exercises (similar to twitch.tv or livecoding.tv) - similar to giving a talk to a live audience at a local Meetup, but online
* Weekly study group sessions (example - one chapter per week on something like the Rails Hartl Tutorial)
* Podcasts / live audio chats
* Deadlines for scholarships
* Weekly / bi-weekly standup meetings for Deploy Apprenticeship program

And anything else that users would like to add.  Seeing a schedule of events would give people something to look forward to and plan for.  It would also give people a more structured/planned way to interact than the more-or less improvised, organic interaction on Slack.  I think this could be very beneficial to some of the more inexperienced developers and students.

Calendar could be home-rolled, or an external solution could be used - Google Calendar, etc.  Basically something with CRUD functionality for events.

**Comment by davidmolina** [comment]
Awesome-- just added you to our battle rhythm on trello as well. take a
look at that as well.

On Wed, Mar 16, 2016 at 7:54 PM, John Hampton <notifications@github.com>
wrote:

> This is a follow-on to our discussion yesterday @davidmolina
> <https://github.com/davidmolina> :
>
> To encourage more direct collaboration & involvement between people on
> Operation Code, we could set up some type of calendar on the website that
> would list any events that we'd like to regularly schedule. Display & track
> a "battle rhythm" of stuff going on every week or so.
>
> Examples:
>
>    - Small-group pair-programming sessions, tailored per language ( allow
>    users to sign up / meet up to solve code katas / code challenges together)
>    - Screencasts or live coding exercises (similar to twitch.tv or
>    livecoding.tv) - similar to giving a talk to a live audience at a
>    local Meetup, but online
>    - Weekly study group sessions (example - one chapter per week on
>    something like the Rails Hartl Tutorial)
>    - Podcasts / live audio chats
>    - Deadlines for scholarships
>    - Weekly / bi-weekly standup meetings for Deploy Apprenticeship program
>
> And anything else that users would like to add. Seeing a schedule of
> events would give people something to look forward to and plan for. It
> would also give people a more structured/planned way to interact than the
> more-or less improvised, organic interaction on Slack. I think this could
> be very beneficial to some of the more inexperienced developers and
> students.
>
> Calendar could be home-rolled, or an external solution could be used -
> Google Calendar, etc. Basically something with CRUD functionality for
> events.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/133>
>



-- 
David Molina
https://about.me/molina

**Comment by davidmolina** [comment]
@jjhampton Could this [open source calendar work](https://github.com/calagator/calagator), or something similar?

**Comment by jjhampton** [comment]
Calagator looks decent at first glance - Rails gem so it could integrate w/ OperationCode.org.  I like the list look of http://calagator.org/ too.

Not sure how complex it is to set up - I'm wondering if there might be something more lightweight for starters.

**Comment by davidmolina** [comment]
Not sure. We could just build it from scratch.

**Comment by rickr** [comment]
I would say for a first cut we just embed a google calendar. Once that's out we can then build our own calendar. If that sounds good I can cut tickets for each of those features.

A few more gems for consideration:
https://github.com/excid3/simple_calendar
https://github.com/bokmann/fullcalendar-rails

**Comment by davidmolina** [comment]
Google cal sounds good for first cut.

**Comment by rickr** [comment]
Added a Calendar milestone with all this info in it.

#148 #149 and #150 created to track these steps. 

Anyone mind if I close this issue?

**Comment by davidmolina** [comment]
Sure thing. Thanks Rick.

On Tue, Mar 22, 2016 at 12:34 PM, Rick <notifications@github.com> wrote:

> Added a Calendar milestone with all this info in it.
>
> #148 <https://github.com/OperationCode/operationcode/issues/148> #149
> <https://github.com/OperationCode/operationcode/issues/149> and #150
> <https://github.com/OperationCode/operationcode/issues/150> created to
> track these steps.
>
> Anyone mind if I close this issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/133#issuecomment-199979358>
>



-- 
David Molina
https://about.me/molina

**Comment by jjhampton** [comment]
@rickr That sounds good, I'll close this now that we have a milestone with steps to develop a solution.  Thanks!
