### ISSUE TITLE
[Mobile] Operation Code not positioned correctly in top left

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#134]

**Comment by Tactika** [comment]
The break-point is at 325px, once it drops below the Logo doesn't scale further down.
![opcbug](https://cloud.githubusercontent.com/assets/16322338/14035864/75572058-f1f0-11e5-9c77-8cd2f23fc1b3.PNG)

**Comment by davidmolina** [comment]
Can it be moved to the left of the menu button, and atop the top photo?

On Thu, Mar 24, 2016 at 6:45 PM, Damien Richcreek <notifications@github.com>
wrote:

> The break-point is at 325px, once it drops below the Logo doesn't scale
> further down.
> [image: opcbug]
> <https://cloud.githubusercontent.com/assets/16322338/14035864/75572058-f1f0-11e5-9c77-8cd2f23fc1b3.PNG>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/134#issuecomment-201103938>
>



-- 
David Molina
https://about.me/molina

**Comment by davidmolina** [comment]
@Tactika I saw it on newer iPhone and a Samsung and it was positioned just right.
