### ISSUE TITLE
Slack Invite taking a while

### ISSUE THREAD

**Issue by jdspringr07** [OperationCode/operationcode#135]
Slack took a little over 15 minutes to generate an invite after new registration.

**Comment by davidmolina** [comment]
@jdspringr07 Not sure. It's failed before where veterans don't get the Slack invite. Both @nanoxd and @nellshamrell looked at it. Looks normal, but we'll have to take a look at the logs.

**Comment by rickr** [comment]
Going to close this out as we've heard no more complaints.
