### ISSUE TITLE
Add github to user profile

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#140]
Each `Veteran` should be able to link their github page to their profile.

Can we display their contributions on the page as well?

**Comment by davidmolina** [comment]
Yep.

Add their GitHub contributions (white box/green boxes).

On Tue, Mar 22, 2016 at 8:37 AM, Rick <notifications@github.com> wrote:

> Each Veteran should be able to link their github page to their profile.
>
> Can we display their contributions on the page as well?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/140>
>



-- 
David Molina
https://about.me/molina

**Comment by rickr** [comment]
Closing this out due to lack of activity. Please feel free to open a new issue if this is still needed.
