### ISSUE TITLE
Add #show for user profile

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#141]
There should be a way to view each `Veteran` profile at a link like:

http://operationcode.org/veteran/david_molina

If we use a name we have to worry about how we could handle duplicate names (eg having two John Smiths). It may be easier to use the veteran id for now for a link that looks like:

http://operationcode.org/veteran/5

And then allow each user to set their own vanity domain.

**Comment by davidmolina** [comment]
Good call.

What if it was connected to individual Twitter accounts? Example:
http://operationcode.org/veteran/@davidcmolina. But then what if some
veterans don't have Twitter.

On Tue, Mar 22, 2016 at 8:43 AM, Rick <notifications@github.com> wrote:

> There should be a way to view each Veteran profile at a link like:
>
> http://operationcode.org/veteran/david_molina
>
> If we use a name we have to worry about how we could handle duplicate
> names (eg having two John Smiths). It may be easier to use the veteran id
> for now for a link that looks like:
>
> http://operationcode.org/veteran/5
>
> And then allow each user to set their own vanity domain.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/141>
>



-- 
David Molina
https://about.me/molina

**Comment by rickr** [comment]
Here's an awful mockup of how I see this looking.

The thing on the left is our user picture.
To the right of that is a bootstrap nav (http://getbootstrap.com/components/#nav) tab or pil. That contains the different sections of the profile.
If a user doesn't have a section (eg talks/presentations) it shouldn't be displayed.

![12 columns](https://cloud.githubusercontent.com/assets/334550/13975136/b8935d28-f088-11e5-874e-b87d37e7443d.png)

**Comment by davidmolina** [comment]
👌
Exactly!

**Comment by rickr** [comment]
Closing this out due to lack of activity. Please feel free to open a new issue if this is still needed.
