### ISSUE TITLE
Add skills/interested in to user profile

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#145]
Each `Veteran` should have a list of skills and a list of interests in their profile.

* The skills to choose from should be in their own model (`Skill`?) with at least one attribute `name`.
* A user should be able to add how ever many skills to their skill section.
* A user should be able to add how ever many skills to their skill section.
* These two areas should be separate.
* Skills should be a prepopulated, non user editable list of languages and topics. eg ruby, python, web development, javascript etc

This can be done in an ajax-y way or a bit more beginner friendly with either a multi select or some check boxes.

**Comment by rickr** [comment]
I think it might make sense to give`Veteran`s skills and `Veteran`s that are mentors skills AND interests.

**Comment by davidmolina** [comment]
Should volunteers be a separate location? Example, fundraising, et.

On Tue, Mar 22, 2016 at 3:53 PM, Rick <notifications@github.com> wrote:

> I think it might make sense to giveVeterans skills and Veterans that are
> mentors skills AND interests.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/145#issuecomment-200068414>
>



-- 
David Molina
https://about.me/molina

**Comment by rickr** [comment]
What about people that are veterans and volunteers? 

What about a badge on volunteer pages that says what they do?

**Comment by davidmolina** [comment]
That would work too. We already have the small "medal" logo that's used in
the avatar.

On Tue, Mar 22, 2016 at 4:17 PM, Rick <notifications@github.com> wrote:

> What about people that are veterans and volunteers?
>
> What about a badge on volunteer pages that says what they do?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/145#issuecomment-200074638>
>



-- 
David Molina
https://about.me/molina

**Comment by rickr** [comment]
Closing this out due to lack of activity. Please feel free to open a new issue if this is still needed.
