### ISSUE TITLE
Add side projects to user profile

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#146]
Each `Veteran` should be able to have many side projects.

Each side project should have a name

**Comment by jdspringr07** [comment]
Is this just a simple list of projects they're working on? 

Vet's Profile:
- Side Projects
 - Project Name 1
   - Project Information
 - Project Name 2
   - Project Information

**Comment by rickr** [comment]
Exactly! I'm going to try and work on a mockup of the UI tonight or tomorrow.

**Comment by rickr** [comment]
Closing this out due to lack of activity. Please feel free to open a new issue if this is still needed.
