### ISSUE TITLE
Create a shared google calendar

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#148]
This calendar will be embedded on the website's calendar page.

* Trusted people should be able to add to the calendar
* Everyone should be able to view the calendar
* It should probably be public?

When complete please add the iframe code from the 'Embed This Calendar' section to the ticket.

**Comment by jjhampton** [comment]
@rickr @davidmolina  Do we have a preference on what the originating Google account is for the calendar? I can create a new calendar on my personal Google account to use for now - or, if we have an official Operation Code Google account set up, we can use that.

**Comment by jjhampton** [comment]
Here's the iframe code from a shared calendar on my personal Google account - I'll send out some sharing invites to the participants on this thread.

<iframe src="https://calendar.google.com/calendar/embed?src=fmnkpvclferu6r3v63al1g2em0%40group.calendar.google.com&ctz=America/New_York" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

**Comment by jjhampton** [comment]
Setting the calendar to 'Public' to allow anyone to save a calendar event to their own Google Calendars.

**Comment by jjhampton** [comment]
Closing, moving work on to #149.
