### ISSUE TITLE
Create custom calendar

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#150]
Create a custom events system that can replace the shared google calendar.

* People with the correct permissions should be able to add an event
* People with the correct permissions should be able to edit an event
* Everyone should be able to view an event.
* There should be a form or link to request and event be added.

We will need Veteran Profiles complete before this work can be used.

Should have a slack UI for entry?

Some gems that may be useful:
https://github.com/calagator/calagator
https://github.com/excid3/simple_calendar
https://github.com/bokmann/fullcalendar-rails

**Comment by davidmolina** [comment]
So we need a few tests veteran profiles? We can start w/ the Deploy
apprentices and go from there.

On Tue, Mar 22, 2016 at 12:31 PM, Rick <notifications@github.com> wrote:

> Create a custom events system that can replace the shared google calendar.
>
>    - People with the correct permissions should be able to add an event
>    - People with the correct permissions should be able to edit an event
>    - Everyone should be able to view an event.
>    - There should be a form or link to request and event be added.
>
> We will need Veteran Profiles complete before this work can be used.
>
> Some gems that may be useful:
> https://github.com/calagator/calagator
> https://github.com/excid3/simple_calendar
> https://github.com/bokmann/fullcalendar-rails
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/150>
>



-- 
David Molina
https://about.me/molina

**Comment by davidmolina** [comment]
Re-looking at Calagator as a possible gem to enable more of us to quickly setup meetup, add conference dates, etc. https://github.com/calagator/calagator

**Comment by rickr** [comment]
Closing this out due to lack of activity. Please feel free to open a new issue if this is still needed.
