### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#151]
* Add instructions for finding beginner friendly tasks
https://github.com/OperationCode/operationcode/issues?q=is%3Aopen+is%3Aissue+label%3A%22beginner+friendly%22
* Add Travis CI to bot area
* Add some verbiage for ruby
* Update labels

**Comment by jjhampton** [comment]
Additional suggestions: 

- remove bootlint ? anyone really using that? suggest other client-side linters (JSHINT, Rubocop)
-isolate the problem - add CodePen as alternative to JSBIN

- Move environment setup to top

- Change wording of ‘topic’ branches to ‘feature’ branches?

**Comment by jjhampton** [comment]
Also: 
Move entire 'Pull requests' section closer to top as well - that's the real meat and potatoes that some people are looking for.
