### ISSUE TITLE
Add additional donation options (pre-selected options, recurring, etc.)

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#156]
So for example, weekly, monthly. 

Pre-selected: $2,500, $2,000, $1,500, $1,000, $750, $500, $250, $100, $75, $50, $25, $17.75, $10, $5...

**Comment by davidmolina** [comment]
Add checkbox: [] Given in memory or honor of...
Add recurring checkbox []: Make this a monthly donation

**Comment by rickr** [comment]
Is this a dup of #128?

**Comment by davidmolina** [comment]
Whoa, yes. Dup of #128.

**Comment by rickr** [comment]
Ok - added some more details from here to #128 and closing due to dup.
