### ISSUE TITLE
Create a better transition between images on homepage

### ISSUE THREAD

**Issue by alexkaufman06** [OperationCode/operationcode#16]
A blue or simple line would make the page look a little cleaner.  Also, some javascript scrolling would be really nice.

**Comment by davidmolina** [comment]
@alexkaufman06 -- agree. We might have more b-roll too.

**Comment by alexkaufman06** [comment]
Adding more b-roll should be easy at this point.  Javascript scrolling should be quite simple.  Currently at my internship but I should be able to help out at some point this week.

**Comment by davidmolina** [comment]
Awesome. Thanks man!

**Comment by dmmoody** [comment]
Sent a pull request to resolve this issue.

**Comment by davidmolina** [comment]
Thanks @dmmoody!
