### ISSUE TITLE
Clean up deprecated code from Pages

### ISSUE THREAD

**Issue by jdspringr07** [OperationCode/operationcode#160]
There's a bunch of pages listed that are no longer in use. Reference app/config/routes.rb to find the pages being routed to.

 If any pages listed under app/pages are not located in this file, they're not being used. Pages should have their own views and controllers associated instead of housing all under one location unless they're static pages. Anything interactive needs to be split off.

**Comment by jdspringr07** [comment]
SI'm working on this right now. For some reason, I cannot assign the task to myself :(.

**Comment by jjhampton** [comment]
@jdspringr07 Weird, lemme try

**Comment by jjhampton** [comment]
@jdspringr07 Added you as a collaborator and assigned you to this task.
