### ISSUE TITLE
[Calendar] Add a link for a new calendar date

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#170]
Per #168

**Comment by jjhampton** [comment]
Some ideas taken from #149 for this: 

* Add a form (maybe directly between the header and the calendar?) with text similar to what @hollomancer had in d888efe - something like "Get involved - suggest an event to add:" followed by inputs allowing the user to suggest Event Name, Date/Time, & Description. 

* Those form values could be emailed via ActionMailer to someone who has write permissions on the Google Calendar, who would evaluate the submission and add it to the calendar.

**Comment by jjhampton** [comment]
Closing this - calendar link is no longer on the OperationCode.org page.  

Perhaps we can revisit this if it's added back in the future, maybe using the Operations Google Calendar instead that was recently set up.

**Comment by davidmolina** [comment]
Yep.
