### ISSUE TITLE
[Press Releases] Add press releases page

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/operationcode#171]
We need a separate page/view that will display all official Operation Code press releases.  One option would be to use Jekyll in a similar way that it's currently used to power our blog.  Once set up, new press releases could be added in markdown format similar to how a new blog post is added.  The layout for a press release would need to be different than is currently used for a blog post (in an established format for press releases)

Rough draft of tasks - these can be broken down into separate issues eventually:

- [x] Research how to distribute Operation Code press release on a wire service
Update 
- [x] Inquire at [PRWeb](http://www.prweb.com) as an option to distribute Operation Code press release
- [x] Inquire at [PR News Wire](http://www.prnewswire.com) as an option to distribute Operation Code press release; spoke to Julianne Petricini and received quote. 
- [ ] Review Jekyll docs: https://jekyllrb.com/docs/home/
- [ ] Review the Operation Code Blog Posting Guide to understand how Jekyll is integrated w/ Rails on our site: https://github.com/OperationCode/operationcode/blob/master/BLOG_POSTING_GUIDE.md
- [ ] Create a Jekyll layout & CSS styling for the list/index view of all press releases - example URL: www.operationcode.org/press (similar to operationcode.org/blog).  Ensure contact info is listed on the page, possibly on left navbar.
- [ ] Create Jekyll layout & styling for the view of a single Jekyll press release (similar to a single blog post, example URL: www.operationcode.org/press-release/2016/05/01/first-press-release.html)
- [ ] Review format at http://iava.org/press/ for example of how to do it right
- [ ] Add link to list/index view to Operation Code homepage - possibly in footer?

**Comment by davidmolina** [comment]
Correction: 
- [ ] Create Jekyll layout & styling for the view of a single Jekyll press release (similar to a single blog post, example URL: www.operationcode.org/press-release/2016/05/01/first-press-release.html)

**Comment by davidmolina** [comment]
Update: 
- [ ] Researched [PRWeb](http://www.prweb.com) as an option to distribute Operation Code press release
- [ ] Researched [PR News Wire](http://www.prnewswire.com) as an option to distribute Operation Code press release

**Comment by davidmolina** [comment]
So copy/paste the entire blog and rename `/press`? @nellshamrell, care to pair w/ me on this?

**Comment by davidmolina** [comment]
Closing this for now-- for now we'll just use `tags.`
