### ISSUE TITLE
Explore using Medium as a blog platform

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/operationcode#172]
The current blog platform using the default Jekyll theme is working, but it can be improved upon.  Advantages of using Medium:

* Possible improved SEO or increased traffic driven to OperationCode.org from Medium blog
* Improved out-of-the-box user interface / design
* Exposure to new user base (Medium users)
* Native comment system

One idea would be to keep the current Jekyll blog, but somehow integrate it with a Medium blog.  Perhaps show only the first paragraph of each blog post on Jekyll, maybe on the list/index view,  and the user would click on 'Read Full Article' to be redirected to Medium?

Here's a Ruby gem that cross-posts - https://github.com/aarongustafson/jekyll-crosspost-to-medium

##### Medium Blog (already set-up as of 3/29/2016)
- [x] Add byline below Blog Post title w/ author info, and description of author at end of each article

#####  Current [Operation Code blog](https://operationcode.org/blog) can be improved by: 
- [ ] Adding a 1-2 sentences underneath each blog post title
- [ ] Adding a `Read more` button that links back to the Operation Code Medium page
- [ ] Increase the number of writers/bloggers to the Operation Code Medium page from board/staff to `Core` and `Deploy` team.  
- [ ] Integrating [Ruby gem](https://github.com/aarongustafson/jekyll-crosspost-to-medium) to minimize dual efforts
- [ ] Improve Operation Code Blog look and feel from current to [Jasper](https://biomadeira.github.io/jasper/)

**Comment by davidmolina** [comment]
Agree w/ Medium advantages. Another: 
- Baked in subscription service native to Medium

The current [Operation Code blog](https://operationcode.org/blog) can be improved by: 
- [ ] Adding a 1-2 sentences underneath each blog post title
- [ ] Adding a `Read more` button that links back to the Operation Code Medium page
- [ ] Increase the number of writers/bloggers to the Operation Code Medium page from board/staff to `Core` and `Deploy` team.  
- [ ] Integrating [Ruby gem](https://github.com/aarongustafson/jekyll-crosspost-to-medium) to minimize dual efforts
- [ ] Improve Operation Code Blog look and feel from current to [Jasper](https://biomadeira.github.io/jasper/)

**Comment by davidmolina** [comment]
Medium page created: https://medium.com/@operation_code

**Comment by davidmolina** [comment]
Working on getting Jasper going...

**Comment by davidmolina** [comment]
Need to pair with someone. Errors, couldn't get it to fire up internally to the app.

**Comment by davidmolina** [comment]
@jjhampton Should we close this? It's done already... maybe separate out the Jasper stuff.

**Comment by jjhampton** [comment]
@davidmolina The main goal is finished (creating a Medium blog) - but the existing blog is still using Jekyll.

I'm almost thinking that it's overkill keeping two blogs - why would we want to keep using Jekyll AND Medium?  If Medium is the blog platform we want to use, might be worth just killing off the Jekyll blog and having the link at the top navbar on the main page - "https://operationcode.org/blog" redirect to the Medium blog.

Doing all the work to switch the current blog to Jasper, and then figuring out how to crosspost from that blog to the Medium blog just seems like unnecessary work.

**Comment by davidmolina** [comment]
Let's do that instead.

**Comment by davidmolina** [comment]
Already over there.
