### ISSUE TITLE
[Hackathons] Update hackathon page

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#174]
_As a volunteer, I want a page where military themed/sponsored hackathons can be centrally tracked, so that I can see at-a-glance when/where such events are taking place._

Minimum viable functional requirements:
- Briefly indicate the purpose of the page, at least a header and two describing sentences of copy.
- Have one section for previous hackathons, and one section for future hackathons.
- Have at least three previous hackathons identified, one future hackathon identified.
- Each hackathon should have an associated image.

**Comment by davidmolina** [comment]
Good start. 

Perhaps leveraging Jekyll, Middleman or Hugo for site and GH Pages?

**Comment by hollomancer** [comment]
Not sure what solution is best for this; maybe having it driven by calendar content, filtering events by whether they're a hackathon or not, and populating each section accordingly, minimizing upkeep.

**Comment by davidmolina** [comment]
Minimizing upkeep is key. What if leveraging the [Operation Code Meetup](http://www.meetup.com/operationcode/) page as an option?

**Comment by hollomancer** [comment]
Depends where we want to centralize our events - Meetup.com or Google Calendar. It looks like they both have an API.

Did a quick look at https://developers.google.com/google-apps/calendar/v3/reference/events - I don't think there's a way to tag Google Calendar events individually. Maybe check event descriptions for the word 'hackathon', grab the last three and the next three, and go from there?

**Comment by davidmolina** [comment]
That could work. We should try that. No date set for first Meetup.

**Comment by rickr** [comment]
Closing this out due to lack of activity. Please feel free to open a new issue if this is still needed.
