### ISSUE TITLE
[Landing] Navbar link font temporarily displays as default font on each page load

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/operationcode#177]
Steps to reproduce:

1. Go to www.operationcode.org
2. Either observe on first page load, or hit refresh
3. The browser will initially display the Navbar text while it's fetching the Google Font 'Open Sans'
4. After 1-2 seconds, when the CSS Google Font is recieved, the browser displays it in the right font

Initial load:
![screenclip](https://cloud.githubusercontent.com/assets/8835055/14068003/e98200c4-f443-11e5-878d-8a8c62f63aef.png)

---
After Google font is recieved:
![screenclip](https://cloud.githubusercontent.com/assets/8835055/14068005/f0dae016-f443-11e5-8736-88a82f876aeb.png)

There may be some way to cache this or wire up the CSS so that it doesn't do this every time, at least for repeat visitors.

**Comment by rickr** [comment]
This no longer applies due to the shift to materialize.
