### ISSUE TITLE
Need a shop

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#18]
Something like this: http://github.myshopify.com/.

**Comment by davidmolina** [comment]
@superscott

**Comment by davidmolina** [comment]
@MOPineyro -- See above.

**Comment by superscott** [comment]
10.4.
(*ノ・ω・）

**Comment by superscott** [comment]
Do we need another repo? We could make it a stand-alone site, or could it be a rails engine inside the main site? @davidmolina

**Comment by davidmolina** [comment]
Another repo. /cc @nanoxd

**Comment by nanoxd** [comment]
I think standalone is the best option. Add a CNAME or an A record for that subdomain and host an app somewhere. @davidmolina Did you have any preference on the payment provider? Do you have any accounts set up?

**Comment by davidmolina** [comment]
Copy. 

Preference, Stripe. Not yet.

**Comment by nanoxd** [comment]
@superscott I created a repo for it :smile: with a basic license. Implementation wise what were you thinking?

**Comment by davidmolina** [comment]
@superscott Something like this: http://github.myshopify.com/, and focused on t-shirts (m/f) and stickers. I have the brand assets from HackHands. /cc @nanoxd

**Comment by nellshamrell** [comment]
+1 for Shopify!  Very good people at that company.
http://www.shopify.com/

**Comment by superscott** [comment]
Update: I should have time to knock this out over the coming weekend.

**Comment by davidmolina** [comment]
Thanks Scott!

On Tue, May 19, 2015 at 10:59 AM, superscott <notifications@github.com>
wrote:

> Update: I should have time to knock this out over the coming weekend.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/18#issuecomment-103614766>
> .
>



-- 
David
t. @davidcmolina <https://twitter.com/davidcmolina>
http://davidmolina.github.io/

**Comment by davidmolina** [comment]
@superscott: convo was in Slack. BLUF: we'll hold off on building this for now. I will be closing this issue this week/sooner if no one has any objections. More background: 

Spoke to Shopify to waive the monthly. The two plans: NPO Lite: $29/month, $312/annual, $624/biennial, $936/triennial
1% transaction fees
CREDIT CARD RATES : Online 2.5% + 30c
POS Swipe Rate 2.4% + 0¢
1 GB File Storage
Unlimited Bandwidth
Unlimited Products
Discount Engine
Real-time Carrier Shipping

NPO Full: $99/month,$1068/annual,$2136/biennial,$3204/triennial

0% transaction fees
CREDIT CARD RATES : Online 2.25% + 30c
POS Swipe Rate 2.15% + 0¢
5 GB File Storage
Unlimited Bandwidth
Unlimited Products
Discount Engine
Real-time Carrier Shipping
Gift Cards
Professional Reports// we'll setup when we have more resources at our disposal.
