### ISSUE TITLE
[Store] Operation Code Swag

### ISSUE THREAD

**Issue by Swinney101** [OperationCode/operationcode#182]
Covering both issues of a store page and figuring out how to source products with the Operation Code logo for marketing/advertisement. 

I am a GIT noob so there are going to be some learning mistakes I am sure.

**Comment by Swinney101** [comment]
@jjhampton assign me please

**Comment by rickr** [comment]
Hey @Swinney101 - this seems like a great idea!

How do you plan on implementing the store? This seems like it may be better suited as a milestone with a bunch of tasks associated with it?

**Comment by jjhampton** [comment]
@Swinney101 We discussed using www.moltin.com for one of the projects Operation Code's Deploy team was helping out on.  It might be worth thinking about for our own store.  Cloud-based API service that hosts your store backend.  Storefront is language-agnostic.  Looks really cool.

**Comment by davidmolina** [comment]
@Swinney101 @jjhampton Anything [here](https://github.com/OperationCode/shop) we could use? Previously, @Wimsy113 did a first hack w/ rails. cc @rickr

**Comment by jjhampton** [comment]
@davidmolina That shop scaffolding from last year would still be a starting point - if we want to use the Shoppe gem.  Still needs a lot of work.  Question is - do we want to build our own e-commerce shop and maintain it , or leverage something else that's already been built? 

I haven't looked through the Shoppe documentation,  but I think whatever's the most lightweight and quickest option is the way to go.  Reid Blomquist in the Slack channel could also have some good input with his knowledge of e-commerce.  Another option he mentioned was SnipCart: https://snipcart.com/blog/static-site-e-commerce-integrating-snipcart-with-middleman

Moltin has Ruby SDK here that has integration w/ Rails - this may enable us to do Moltin API calls directly from the existing Operation Code Rails app -> Moltin API.

**Comment by davidmolina** [comment]
@jjhampton Agree. Love to have Reid's input. Much like SRVD, love to leverage Moltin API.

**Comment by Swinney101** [comment]
I am wading through some rails tutorials to get spun up. My web background thus far only extends through HTML/CSS. Looking forward to work with the API's. I more jumped on this project/discussion from the marketing/retail side, how do we get op code swag and grow the brand. Been absent the past two days enjoying a short break before class starts back up tomorrow.

**Comment by davidmolina** [comment]
Hey Ryan! Happy Sunday. Working the swag this week w/ a few co's and drop-shipment. In the interim, we should explore the Moltin API and getting it working properly.

**Comment by rickr** [comment]
This is being covered by #267
