### ISSUE TITLE
Change blog links to point to medium

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#192]
As per #172 our medium blog link is: https://medium.com/@operation_code

All current references to our current blog should be replaced with that.

**Comment by davidmolina** [comment]
Gotcha. That's just a header change.

**Comment by davidmolina** [comment]
This [commit](https://github.com/OperationCode/operationcode/commit/067407a73a034035583431ef6bcde6fcfe996762) fixes this issue.
