### ISSUE TITLE
[Guides] Add a JavaScript page

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#199]
Javascript Page Outline (Work in Progress):

#### Brief history of language
- [ ] 1-2 sentences 

#### Where is Javascript used? What can I program with it?
 - [ ] Browser / client-side (websites UI, single-page-application frameworks)
 - [ ] Server-side / non-browser runtimes (NodeJS)
 - [ ] Additional cross-platform applications (Electron, IoT, anything else)

### Key concepts & best practices w/ Javascript (brief rundown on WHAT to spend time on learning)
- [ ] DOM (Document Object Model)
- [ ] Primitive types (explain these briefly?)
- [ ] Prototypical Inheritance
- [ ] Closure
- [ ] Functions as first-class citizens
- [ ] ES6/2015 and onward
- [ ] Module Systems (brief explanation of what these are)

#### Free E-Books
- [ ] Eloquent Javascript - http://eloquentjavascript.net/
- [ ] Speaking Javascript - http://speakingjs.com/
- [ ] Javascript Design Patterns - https://addyosmani.com/resources/essentialjsdesignpatterns/book/

#### Tutorials
- [ ] JavascriptIsSexy: http://javascriptissexy.com/how-to-learn-javascript-properly/

#### Self-paced Online Courses
- [ ] FreeCodeCamp
- [ ] Codecademy (which track is best for JS beginners?)
- [ ] CodeSchool - https://www.codeschool.com/courses/javascript-road-trip-part-1
- [ ] TeamTreehouse ( not free, but they offer a Vet discount.  Which TeamTreehouse courses are best for JS beginners?)
- [ ] LearnJS - http://www.learn-js.org/
- [ ] SoloLearn  http://www.sololearn.com/Course/JavaScript/

#### Sample starter lessons
 - [ ] JS-Assessment by Rebecca Murphey
 - [ ] CodePen projects by Rebecca Murphey
 - [ ] JS-Koans

#### Documentation
 - [ ] MDN - http://www.mdn.org - the definitive JS documentation resource
 - [ ] W3Schools - http://www.w3schools.com/js/default.asp (Unsure if we should suggest W3 Schools - they've been known to have inaccurate info.  can't lie, I've used them as a resource tho )
  

##### Good JS Blogs to follow - (ideas?)
 - [ ] Axel Rauschmeyer
 - [ ] Eric Elliott
 - [ ] Addy Osmani
 - [ ] Rebecca Murphey

##### Video Blogs
 - [ ] LearnCodeCademy - https://www.youtube.com/channel/UCVTlvUkGslCV_h-nSAId8Sw
 - [ ] FunFunFunction - https://www.youtube.com/channel/UCO1cgjhGzsSYb1rsB4bFe4Q

##### Code Schools/Bootcamps specializing in JS: 
 - [ ] Hack Reactor
 - [ ] MakerSquare
 - [ ] Dev Mountain

**Comment by jjhampton** [comment]
@karla001 Just assigned you to this one, we can team up on it.

**Comment by karla001** [comment]
@jjhampton  Awesome! I honestly don't know what to do on it on my own. @davidmolina  said to pick a project and figure it out, so I'm  trying.

**Comment by davidmolina** [comment]
@karla001 Similar to the `ruby` milestone, ex. good tutorials, first steps, blogs etc.

**Comment by davidmolina** [comment]
@karla001 Do this first: https://github.com/OperationCode/operationcode/blob/master/CONTRIBUTING.md

**Comment by karla001** [comment]
@davidmolina  I read through it. I am having an issue installing the ruby bundle, but hopefully I will figure it out when I get a change. 
**Here is a list I have compiled for learning JavaScript: **

http://javascriptissexy.com/how-to-learn-javascript-properly/
[http://www.learn-js.org/
https://www.codeschool.com/courses/javascript-road-trip-part-1
http://www.sololearn.com/Course/JavaScript/
http://www.w3schools.com/js/default.asp
http://eloquentjavascript.net/

_It's all the basic sites that I have found through our Slack and on my own for JavaScript.

_@jjhampton  Let me know what you think.   Also I am wondering how many links do you think we should include. I really think we should limit the amount of links because too much information can easily overwhelm  someone who is just starting out.

**Comment by jjhampton** [comment]
@karla001 I agree, don't want to overwhelm with too many links.    Distilling our list down to the best stuff for beginners should be a goal. That is a solid start, though!

 Maybe have a separate resources/links into different sections by type? Free E-Books / Tutorials / Self-paced  Courses ala Codecademy / Good JS Blogs to follow / Code Schools<<<<< something along these lines.

I'm going to add a rough draft outline of potential page sections we can work on building out up top in the description of this issue - I'll include your links in there.  Once we have that, we can expand the outline to anything else we want to include.  

Then we can build convert the outline to HTML for the actual page.

**Comment by karla001** [comment]
@jjhampton  Great! I hope I can get everything set up by then.

**Comment by jjhampton** [comment]
I added a checklist to the description that David posted at the top.  We can revise that as we go, check & uncheck things, etc.  Ideally we will remove/strikethrough some of those things to only include the absolute essentials that beginners need.  Goal is for this to be our go-to resource for Veterans who need an intro to Javascript.

@david A similar outline to this could be used for the other 'Getting Started' pages, just with different checkbox items specific to those languages.

**Comment by davidmolina** [comment]
@jjhampton Agree. Thanks. Could you possibly start us off on that template, and then we can reassign/adjust fire from there with new assignments and hit the ground running faster? Example that template you mentioned? cc @karla001

**Comment by karla001** [comment]
Not sure what else to do now for this feature. Let me know if there is something I can do? Sorry, again never really used Github.

**Comment by AishaBlake** [comment]
I'd love to help with this! I'm a JavaScript instructor at a coding bootcamp, so this is my bread and butter. Has anyone actually started building out the HTML? Should I be watching #212 for guidelines on how to structure this?

**Comment by rickr** [comment]
Hi Aisha, 

I don't believe there is any HTML cut yet. All these guides are tracked in a milestone which has a bit of detail to how things could be structured: 
https://github.com/OperationCode/operationcode/milestones/Getting%20Started

**Comment by AishaBlake** [comment]
@rickr I did see that milestone, but this issue (relating to JavaScript) appears to be the most fleshed out by far. I also saw that someone made an Android page, but it doesn't look like it's actually been integrated yet.

**Comment by davidmolina** [comment]
Hi Aisha, 
Nothing has been cut up--would love your help on this so others can touch and go, replicate for other languages. Be happy to jump on a quick conference call as well if that be more helpful, fast.

**Comment by AishaBlake** [comment]
Hey David,
Sure thing! Does today work for you? I'm off work at 5pm EST.

**Comment by davidmolina** [comment]
Sure... knocking a part of an MOU for a new foundation partner. Email me a
good direct line, and I'll call you shortly. david[at]operationcode[dot]org

On Tue, May 31, 2016 at 1:34 PM, Aisha Blake <notifications@github.com>
wrote:

> Hey David,
> Sure thing! Does today work for you? I'm off work at 5pm EST.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/199#issuecomment-222811613>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw1KHCUqGQOfSXm9YmATtjlUUfRVXsFks5qHJtVgaJpZM4IF-Hh>
> .
>



-- 
---
David Molina
http://davidmolina.github.io

**Comment by davidmolina** [comment]
Hi @AishaBlake, per our conversation love to get your help on this. Maybe pair w/ @karla001? Re-assigning this to you.

**Comment by AishaBlake** [comment]
So I had a quick talk with David on the phone and I'd like to be assigned to this issue. 

@karla001 : You mentioned that you're not really familiar with GitHub. I teach people to use Git and GitHub as well as to program in JavaScript as part of my job. Please let me know if you'd like to collaborate and/or if I can help demystify GitHub!

**Comment by terakilobyte** [comment]
I found http://chimera.labs.oreilly.com/books/1234000000262/index.html this book to be exceptional as well while learning. Come to think of it I have an entire list of free JS books that were all really good. I can share them all if you'd like, though a broad deluge of information may make newcomers feel swamped and despairing "I'll never learn all this!".

**Comment by davidmolina** [comment]
Nice. 

Do share it.

**Comment by terakilobyte** [comment]
Books and Videos:
JavaScript resources, all free online:

http://jsforcats.com/
https://www.youtube.com/playlist?list=PLeL6uTxQ-uX_5BpOb2FDNgG6SxjCs59Kv
https://www.youtube.com/watch?v=hQVTIJBZook
https://www.khanacademy.org/computing/computer-science/algorithms
http://watchandcode.com/courses/eloquent-javascript-the-annotated-version/ | http://eloquentjavascript.net/index.html
https://www.youtube.com/watch?v=8aGhZQkoFbQ
https://github.com/getify/You-Dont-Know-JS
https://www.udacity.com/course/object-oriented-javascript--ud015
https://leanpub.com/javascript-spessore/read
https://www.udacity.com/course/javascript-design-patterns--ud989
http://chimera.labs.oreilly.com/books/1234000000262/index.html
https://leanpub.com/javascriptallongesix/read
https://www.youtube.com/watch?v=gawmdhCNy-A
http://jhusain.github.io/learnrx/
https://github.com/DrBoolean/mostly-adequate-guide

Some of those are more skewed towards functional style programming in JS, but they are all good.

**Comment by jjhampton** [comment]
@AishaBlake I sent you an invite to the Operation Code GitHub Org - once it's active we can assign you to this issue.  Thanks for the offer to help - it would be great to get this Javascript page off the ground and serve something up to the community!

**Comment by jjhampton** [comment]
@AishaBlake Have you started any work on this yet?  If not, I'd like to start drafting up a rough scaffolding for the page tomorrow, based on the outline at the top of the comments for this issue.

**Comment by AishaBlake** [comment]
@jjhampton I actually did exactly that. I just committed/pushed to my fork. I did realize I wasn't sure where to put it. It's just floating in the root directory at the moment!

**Comment by AishaBlake** [comment]
So I do think this guide could use a little more copy. It's mostly a very long list at this point. It could also probably be stripped down a bit. I like the big buckets we've got here, but it could probably use fewer list items and some more explanation of the different resources. Thoughts?

**Comment by jjhampton** [comment]
@AishaBlake I agree - I think a key here is to have this be as useful to absolute beginners as possible, and only include the best resources.  Don't want to over-indundate people with too many links.  It's already easy enough to get distracted when trying to teach yourself.

Maybe you can submit a PR for the fork that you started with the HTML template?  I scrolled through (didn't demo it on my machine) and that looks like good progress so far.  Once the PR is submitted, we can review it and pare it down to what resources are most applicable.

We can also identify, as you mention, some more "copy" besides just the long list.  Perhaps some original content on how to:
* set up a text editor / IDE
* set up a local server for demoing web apps
* set up Node or an easy-to-use REPL for experimenting w/ JS code

Also maybe some content related to the currently used build tools: 
* Gulp
* Webpack (I'm not very experienced w/ this, but it appears to be gaining more traction)

Those are just some ideas.  I think once your PR is submitted we can start adding more stuff.

**Comment by rickr** [comment]
Closing this since #233 was merged.

Thanks all for helping!
