### ISSUE TITLE
Background photos on homepage not responsive on mobile

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#20]
... and, not responsive on browser. Should size accordingly, both scholarship fellows, software mentorship, new gi bill expansion.

**Comment by davidmolina** [comment]
@nanoxd @alexbeeken gents-- responsiveness on background photos changed on that last commit.

**Comment by nanoxd** [comment]
In what way? I noticed a little quirkiness but none of the css overwrote any part of the image css.

**Comment by nanoxd** [comment]
Running a `git checkout HEAD~2` on master yields the same result on live site and dev site. I checked both Safari and Chrome. Are you seeing issues on any other browser?

**Comment by davidmolina** [comment]
I see this on my iPhone:

On Mon, Apr 27, 2015 at 10:27 PM, Fernando Paredes <notifications@github.com

**Comment by davidmolina** [comment]
![img_9532](https://cloud.githubusercontent.com/assets/1848616/7363292/eaf082f6-ed2c-11e4-99b9-4f262720b97a.PNG)

**Comment by davidmolina** [comment]
@alexkaufman06 - do you see the same?

**Comment by Wimsy113** [comment]
Okay so there is a simple fix for this,  let me check on the source code and then get back to you, but I'm sure I can fix it.

**Comment by davidmolina** [comment]
Awesome. Thanks Krystyna for the contribution.

**Comment by alexkaufman06** [comment]
Any luck on the photos @Wimsy113?  I was thinking about taking the photos down for now and adding a simple background as a temporary fix.

**Comment by davidmolina** [comment]
@alexkaufman06 -- take another stab. Temporary fix is ok. For now. Till we figure it out.

**Comment by davidmolina** [comment]
@Scripore contribution 47dc437 fixed this.
