### ISSUE TITLE
[Stripe] Add a success message to the 'Donate' page

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#201]
To repro:

Visit [https://operationcode.org/donate](https://operationcode.org/donate)
Fill in the form
Submit the form
Currently, there is no success flash or other visual indication that your donation has been submitted.

There should be a success flash and maybe a message that explains what to expect next.

**Comment by rickr** [comment]
Looks like this is a dup of #115 . I'll close that one.

**Comment by davidmolina** [comment]
Oh, my bad.

**Comment by rickr** [comment]
Donations are now handled via donarbox.
