### ISSUE TITLE
[Mailer] Update welcome mailer 

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#202]
Add note about Slack channels, protocol, etc.

**Comment by davidmolina** [comment]
@rickr @hollomancer @jjhampton anything in the mailer we should update? I just added free-code-camp.

**Comment by rickr** [comment]
@hollomancer + rob Can you verify code of conduct, conciseness.

**Comment by davidmolina** [comment]
What's still left on this, @rickr?

**Comment by rickr** [comment]
I just did another pass over it but it might be worth it to have @jeremysb1 take a look.

**Comment by jeremysb1** [comment]
we're talking about the welcome email? what's the latest and greatest @rickr @davidmolina?

**Comment by rickr** [comment]
Template is here: https://github.com/OperationCode/operationcode/blob/master/app/views/user_mailer/welcome.html.erb

**Comment by jeremysb1** [comment]
Pretty good but needed a few slight copy changes. Most notably, a brief explanation of what we use Slack for. I submitted a pull request #423

**Comment by rickr** [comment]
#423 was merged. Calling this good.
