### ISSUE TITLE
[Landing] Add Programs & Services to header

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#207]
Reformat header to drop-down menu.

**Comment by tadake** [comment]
When the screen is at a smaller size the nav bar aoutomatically converts to a dropdown menu. Are you wanting to make it a dropdown menu only?

**Comment by davidmolina** [comment]
@tadake Or on mobile, maybe it opens to the right?

**Comment by rickr** [comment]
Is this the issue where we were going to convert to dropdown style menus? eg http://getbootstrap.com/javascript/#dropdowns

**Comment by davidmolina** [comment]
@rickr Exactly. Something where desktop, hover and links fall directly beneath but horizontal; mobile it could open to the right. Not sure what our analytics say about where people click, but I'm finding 9/10 emails are asking where to join, more about what we do, funders on how to commit, so definitely the header needs to be more broad reaching. @tadake

**Comment by davidmolina** [comment]
This [commit](https://github.com/OperationCode/operationcode/commit/6179f6b7f89ce96e5cea1d159a38716dcb84776b) fixes this issue.
