### ISSUE TITLE
Integrate Slack

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#21]
We have a community on Slack, but need to integrate and authenticate through app while continuing petition (/action).

**Comment by Wimsy113** [comment]
There are several apps in slack that allow for this, my team uses them, there's a github app, as well as Circle CI and dploy.io might be worth checking them out.

**Comment by davidmolina** [comment]
Agree. Fernando (@nanoxd) has the lead. Can you work with him?

**Comment by nanoxd** [comment]
@Wimsy113 What did you have in mind?

**Comment by Wimsy113** [comment]
Well the github app for slack keeps track of pull requests for the repo that it's connected to, and the circleci actually tests the changes that you have made to a repo and let's you know whether they have passed or failed so you can make changes accordingly, they also track pull requests as you go. They can get really spammy especially if you are working on a fix or whatnot. so it really depends on what you're trying to track @nanoxd

**Comment by nanoxd** [comment]
@Wimsy113 I responded back in Slack :smile:. Let's move this discussion there

**Comment by davidmolina** [comment]
Thanks @nanoxd for this recommendation for on-boarding: https://github.com/rauchg/slackin.
