### ISSUE TITLE
[Learn.co] Add link to site for easy enrollment 

### ISSUE THREAD

**Issue by juanmayoral** [OperationCode/operationcode#210]
I just enrolled in Learn.co  wondering if they is an easier and faster way to enroll.

**Comment by davidmolina** [comment]
@juanmayoral good point. we really need to add that link for faster enrollment. cc @Wimsy113

**Comment by davidmolina** [comment]
This [commit](https://github.com/OperationCode/operationcode/commit/7b1a3fdedb8692c853ef70a15162cca8d373c4bc) fixes this.
