### ISSUE TITLE
[Guides] Create a newbie guide

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#212]
Guide should include: 
- Slack protocol, ex. intro, channels, what channels are for, "@" sign, "@here", et
- GitHub protocol, ex. account setup, contributing their first issue here on `/operationcode` and understanding labels and assignments, 
- Enrollment in Learn.co
- Enrollment in [insert free programs to start building websites/web apps/native apps]

**Comment by rickr** [comment]
Closing due to updates to welcome mailer updates and getting started.
