### ISSUE TITLE
Automate /action or petition

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#22]
Military/veterans sign the petition, but the data remains in the rails app and not automatically into the newsletter for the SITREPs.

**Comment by davidmolina** [comment]
We use mailchimp for our SITREPs. About 111 veterans are signed up. Need to automate data input and touch it once, not having to take the data from active-record and then manually input it into mailchimp. Was looking at this: https://github.com/mailchimp/email-blueprints. 

Also, need to automate Tweets to U.S. Senators and U.S. Representatives based on veterans zipcode. Manually inputting this as well. Live tweet: https://twitter.com/operation_code/status/590256827067015168.

**Comment by davidmolina** [comment]
Ideally, we could use Change.org API and Twilio API allowing both civilians and military/veterans to sign the petition to expand New GI Bill to include code schools, locate their local representative, and contact them free of charge using Twilio.

**Comment by nellshamrell** [comment]
I've done this before - building a nightly job which synced all data in a Rails app with Mailchimp, making heavy use of this awesome Mailchimp API wrapper https://github.com/amro/gibbon.  Gibbon makes it very easy to access the Mailchimp API from within a Rails application using Ruby.

Would be happy to integrate this as a first step, though eventually I will need the Mailchimp credentials to make this work.

**Comment by davidmolina** [comment]
Hi @nellshamrell- just sent you an invite. Thanks!

**Comment by nellshamrell** [comment]
Got it.  TY!

**Comment by davidmolina** [comment]
@nellshamrell -- so this relates a bit to #44 . Total requirements: 
- automate signup between rails app and MailChimp (no need to manually input from database copy/paste to MailChimp)
- automate signup between rails app and Slack (Software Mentor Protégé Program) Operation Code community
- Integrate Change.org & Twilio API to automate "traditional letter to Congressman" based on service-member or veterans zip code (from their response in the rails app) 
- Auto tweet based on service-member or veterans zip code response vs. manually having to input every time (Change.org & Twilio API should solve this). Example tweet: https://twitter.com/operation_code/status/591029490798714880. 
Thanks @nellshamrell!

**Comment by nellshamrell** [comment]
I think I'll take on the automate signup between the rails app and MailChimp first, submit a pull request, get that deployed in, then move onto the next requirement (though if anyone else feels like working on the other requirements while I'm working on the Mailchimp piece please feel free!)

**Comment by nellshamrell** [comment]
How I imagine the Mailchimp aspect of this working:

![operation_code_mailchimp](https://cloud.githubusercontent.com/assets/813007/7557661/74a07e08-f74a-11e4-99b4-d839d72d9606.png)

**Comment by nellshamrell** [comment]
How I imagine the Mailchimp part of this working:

![operation_code_mailchimp](https://cloud.githubusercontent.com/assets/813007/7557679/bb3203fa-f74a-11e4-82d0-c6ad88b5efde.png)

**Comment by davidmolina** [comment]
@nellshamrell -- perfect!

**Comment by nellshamrell** [comment]
Mailchimp is currently transitioning from v2.0 of their API to v3.0.  Documentation on what methods we should use to subscribe veterans through the API is not clear, pinged Mailchimp over twitter for clarification on which API we should use.

**Comment by nanoxd** [comment]
Thanks for the heads up :+1:

**Comment by davidmolina** [comment]
Thanks Nell for the heads up.

On Sun, May 10, 2015 at 8:52 PM, Fernando Paredes <notifications@github.com>
wrote:

> Thanks for the heads up [image: :+1:]
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/22#issuecomment-100756174>
> .
>



-- 
David
http://davidmolina.github.io/ | t. @davidcmolina
<https://twitter.com/davidcmolina>

**Comment by nellshamrell** [comment]
Updating:

We can indeed use the Mailchimp v3.0 (got a response back from the [Mailchimp API team](https://longreply.com/r/91fd2c8c).  Although [Gibbon](https://github.com/amro/gibbon), a great wrapper for use when calling the Gibbon API from Ruby code, currently does not support v3.0, the maintainer is [working on updating it now](https://github.com/amro/gibbon/issues/118) (I'm going to be helping him test it when it is ready).

I would recommend waiting until Gibbon is updated.  We could theoretically call the Mailchimp API directly...but that would be messy and difficult to maintain.  The maintainer of Gibbon has been very responsive both in maintenance of Gibbon and responding to any questions or issues with it.

**Comment by nanoxd** [comment]
@nellshamrell I'm all for waiting. No need to do more work than necessary

**Comment by davidmolina** [comment]
Awesome. Let's hold off.

On Tue, May 12, 2015 at 7:50 PM, Fernando Paredes <notifications@github.com>
wrote:

> @nellshamrell <https://github.com/nellshamrell> I'm all for waiting. No
> need to do more work than necessary
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/22#issuecomment-101488364>
> .
>



-- 
David
http://davidmolina.github.io/ | t. @davidcmolina
<https://twitter.com/davidcmolina>

**Comment by davidmolina** [comment]
Be great to tie in our Twilio.org account and send vets a text (https://twitter.com/robertlenne/status/607901970733658112).

**Comment by gxespino** [comment]
What would you want the texts to say? I can implement twilio pretty easily.

**Comment by davidmolina** [comment]
Maybe it's three part: (1) print letter to the veteran's or civilian
supporters member of Congress using the Change.org API, (2) a call to that
office or text?, and (3) an automatic tweet to that veteran's or civilian
supporters Member of Congress and x2 U.S. Senators. Example tweet:

https://twitter.com/operation_code/status/589545850126368769

On Tue, Jun 16, 2015 at 12:53 PM, Glenn Espinosa <notifications@github.com>
wrote:

> What would you want the texts to say? I can implement twilio pretty
> easily.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/22#issuecomment-112549979>
> .
>



-- 
David
t. @davidcmolina <https://twitter.com/davidcmolina>
http://davidmolina.github.io/
