### ISSUE TITLE
[Config] .sass-cache showing even after in .gitignore

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#224]
https://github.com/OperationCode/operationcode/blob/master/.gitignore

cc @rickr

**Comment by rickr** [comment]
You should just be able to remove them (`git rm --cached <dir>`), commit the rm, and then further updates won't be tracked.

**Comment by davidmolina** [comment]
So `git rm --cached .sass-cache`?

**Comment by jjhampton** [comment]
What @rickr is saying should work - can probably do the same for the `bower_components` directory.  Usually need to make at least one commit with the removal, and then you're good from then on.
