### ISSUE TITLE
Add map of Operation Code members to site

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#229]
Put map of code schools on home page.

**Comment by rickr** [comment]
The map is available at https://operationcode.org/veterans/map , it just needs to be linked to somewhere.

**Comment by davidmolina** [comment]
Landing?

**Comment by rickr** [comment]
Put it in the footer

**Comment by davidmolina** [comment]
This [commit](https://github.com/OperationCode/operationcode/commit/3d1994a1b70f2dd3230dd0246d5c04765975e1ce) fixes this.
