### ISSUE TITLE
[Footer] Add GuideStar logo

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#235]
<a href="http://www.guidestar.org/profile/47-4247572" target="_blank"><img src="http://widgets.guidestar.org/gximage2?o=9522101&l=v1" /></a>

**Comment by davidmolina** [comment]
<a href="http://www.guidestar.org/profile/47-4247572" target="_blank"><img src="http://widgets.guidestar.org/gximage2?o=9522101&l=v2" /></a>

**Comment by davidmolina** [comment]
<a href="http://www.guidestar.org/profile/47-4247572" target="_blank"><img src="http://widgets.guidestar.org/gximage2?o=9522101&l=v3" /></a>

**Comment by davidmolina** [comment]
<a href="http://www.guidestar.org/profile/47-4247572" target="_blank"><img src="http://widgets.guidestar.org/gximage2?o=9522101&l=v4" /></a>

**Comment by davidmolina** [comment]
^^ Either or works.

**Comment by davidmolina** [comment]
@rickr can we move this to high? Thx.

**Comment by rickr** [comment]
Done. It'll be done by the weekend.

**Comment by rickr** [comment]
This was fixed in #349
