### ISSUE TITLE
Embedded videos should size accordingly on mobile

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#24]
Currently, embedded videos on mobile don't respond and fit to screen.

**Comment by davidmolina** [comment]
@nanoxd still not responding on mobile (iPhone).

**Comment by nanoxd** [comment]
#29 took us partway there thanks to @alexbeeken. I got sidetracked and didn't push it up to Heroku. Pushing now

**Comment by nanoxd** [comment]
iPhone 6: 

![operation code veteran coders 2015-04-27 22-00-38](https://cloud.githubusercontent.com/assets/1889575/7363074/e04e340a-ed28-11e4-8ea7-36f5170e23aa.png)

**Comment by davidmolina** [comment]
Awesome--works perfect @nanoxd! Thanks @alexbeeken for your contribution on this!
