### ISSUE TITLE
In the footer the 'Mentor' and 'Volunteer' links are mailtos

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#246]
These should either be a form (the join form?) or explain the roles.

**Comment by erangeljr** [comment]
Do you have a more formal description of these roles? Do you want the form to just submit it's content to the same email they're currently pointing to?

**Comment by rickr** [comment]
Lets remove `mentor` and create a new `volunteer` page. We can enumerate the various things people can do on that page (eg mentoring).

If @davidmolina has no objections to that plan I'll work on getting some copy for that page.

**Comment by davidmolina** [comment]
No objection. Thx Rick.

**Comment by rickr** [comment]
Closing due to redesign
