### ISSUE TITLE
Scholarship application

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#25]
Another fellow rubyist, @shawnacscott, suggested OpenConferenceWare (http://openconferenceware.org/) as a possibility to build out the Operation Code Scholarship Application. Criteria: 
- Secure login for both committee and applicants
- Subdomain potentially, ex. scholars.operationcode.org
- Easy to track, star, flag, ask questions, pre-screen, award, post-award and success stories
- Automatically pre-screen applicants, coordinate reviews, internal chat and video interviews

Initial thoughts, but this moves to the top of the priority as crowdfunding campaign started this week.

**Comment by ivanoats** [comment]
I've been working on a Scholarships application for UW, but it's not near ready yet. A couple of the other vendors we talked to in our buy/build discussions:

- https://www.academicworks.com
- http://www.wizehive.com

**Comment by shawnacscott** [comment]
@rediab would be the one to be able to give you more info about OpenConferenceWare and whether it might work for this use case.

**Comment by davidmolina** [comment]
Thanks @shawnacscott. 

@reidab - would OpenConferenceWare work for an scholarship application process & tracking system?

**Comment by reidab** [comment]
@davidmolina It certainly might work, but there are some things to consider about its current design that might need working around:

* Since Open Source Bridge has a public proposal process, OCW doesn't currently have any support for making proposals private after they're submitted. This is something I'd gladly accept a PR for, provided it was implemented as an optional feature.
* The proposal fields aren't easily customizable. If you need to ask different questions of applicants, it would require adding corresponding database fields or reworking things to serialize data in another way. I'm personally in favor of moving towards a more customizable proposal form, but I don't have any immediate plans to do this.

**Comment by davidmolina** [comment]
@reidab - still working through this.

**Comment by davidmolina** [comment]
Ivan, curious why the other apps ruled were out? Did they not provide a good on boarding? Require separate logins? Wondering what is your progress on the UW app?

**Comment by ivanoats** [comment]
I actually ended up leaving that position at UW. Last I heard they were looking at AcademicWorks again.

**Comment by davidmolina** [comment]
Oh, right on. We'll probably end up building something internally, active
record and keep it minimal. Thx.

On Mon, Aug 10, 2015 at 1:27 PM, Ivan Storck <notifications@github.com>
wrote:

> I actually ended up leaving that position at UW. Last I heard they were
> looking at AcademicWorks again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/25#issuecomment-129596457>
> .
>



-- 
David
t. @davidcmolina <https://twitter.com/davidcmolina>
http://davidmolina.github.io/

**Comment by hollomancer** [comment]
Scholarship Criteria
Veteran-founded and led, Operation Code is on a mission to help transitioning military, guard & reserve troops, veterans and their families learn to code and build software to change the world. Our community partners provide conference scholarships to make these events more accessible and inclusive to individuals from all walks of life. 

Criteria for conference scholarships are the following: 
Be willing to provide 2-3 sentences about why you would like to attend the conference and what you hope to get out of it; 
Be a transitioning military, guard & reserve troop, veteran and/ or military family; 
Be interested in coding and software development as a post-military career pursuit and/or make your big idea a reality; 
Be actively engaged in our software mentorship community on Slack; 
Be an active contributor in our open source projects on GitHub; 
Be a follower and participant in our social media profiles, ex. Twitter & Facebook; 
Be willing to be interviewed pre-conference for our Medium to share your story; 
Be able to document your experience and lessons learned in Medium on the conference within 48-hours of attending to empower other military veterans to explore coding to change the world. 

Unfortunately, at this time we are unable to cover travel/lodging. However, our operations team is actively pursuing fundraising opportunities to ensure end-to-end conference travels are seamless in the future. 

https://operationcode.org/scholarships

**Comment by rickr** [comment]
Closing this out due to lack of activity. Please feel free to open a new issue if this is still needed.
