### ISSUE TITLE
Bad links do not present a 404 message.

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#253]
REPRO
1) Go to https://operationcode.org/thisneedsto404
2) Observe.

RESULT
A page appears that does not inform the user that they attempted to access a location that does not exist.

EXPECT
A 404 error appears, or the user is redirected to the home page. Ideally, we have a custom 404 page that is a little friendlier.

**Comment by rickr** [comment]
A 404 *is* returned. Just looks like the page displayed is incorrect.

**Comment by rickr** [comment]
This is probably the culprit:
https://github.com/OperationCode/operationcode/blob/master/public/404.html

**Comment by rickr** [comment]
Fixed in #348
