### ISSUE TITLE
Video Pause

### ISSUE THREAD

**Issue by alexkaufman06** [OperationCode/operationcode#26]
Background video on page keeps pausing and showing a blank black screen for a second.  Possible fix with Media API? http://stackoverflow.com/questions/14161599/customize-html5-video-stop-point-frame 

Adding a picture of the hands in the background might help as well.

**Comment by davidmolina** [comment]
Right. That should work.

**Comment by davidmolina** [comment]
Gotta be another way vs. blank screen. Not sure. /cc @BrainScraps @nanoxd

**Comment by davidmolina** [comment]
@Scripore contribution 47dc437 fixed this in the intermediate until we can come up with a better solution for mobile. Replaced video with scrolling photos.
