### ISSUE TITLE
Figure out how to update our blog section

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#261]
Now that we're moving to medium the `Recent highlights from our blog` section on the home page is going to be out of date. We need a way to populate this data. 

Some questions to answer:
* Does medium have an API we can call to do this automatically?
* If not can this be scripted as a rake task?

**Comment by davidmolina** [comment]
Closing.. as we're now over on Medium. :)

**Comment by rickr** [comment]
@davidmolina I think we still need this so we can update the blog section on opcode.org with the content from medium...unless we want to remove the recent highlights section?

**Comment by rickr** [comment]
2

**Comment by davidmolina** [comment]
Auto update from Medium?

**Comment by rickr** [comment]
Basically yea. I haven't looked into if that's possible or not. We could just remove the blog section for now. I suspect it's not seen often (if at all). Let me see if I can pull some stats to confirm.

**Comment by davidmolina** [comment]
Remove from landing? Sure. Priority there is conference & code school scholarships, sponsors and in the news.

**Comment by rickr** [comment]
...it's not on there now. Ok then - this should be fine to close!

**Comment by davidmolina** [comment]
Will do..
