### ISSUE TITLE
Page for selling merch, store.operationcode.org

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#267]
Need to identify provider for this, then build frontend, ex. shop.operationcode.org or operationcode.org/shop

**Comment by davidmolina** [comment]
Someone in Slack mentioned Teespring.

**Comment by RobKriner** [comment]
I was just looking into this - [http://artistshopshelp.threadless.com/article/16-how-does-pricing-work-for-items-in-my-artist-shop]. Threadless will handle all of the logistics for getting our shirts made and mailed, and will give us our own storefront that we can customize. They have options for t-shirts, hoodies, and are working on other SWAG we can add. Krystyna tweeted last night that she was working up t-shirt designs, so it seems like this might be worth looking into as well?

**Comment by davidmolina** [comment]
Sounds like a win-win. Can you get us setup, Rob?

**Comment by RobKriner** [comment]
Yep. Already pinged Krystyna on the t-shirts and she should have some designs to share by the end of the week. I can then get everything set up and launched by the time the booster campaign is done.

**Comment by davidmolina** [comment]
Outstanding.

**Comment by hollomancer** [comment]
@RobKriner, let me know when we can move on this.

**Comment by sfillm07** [comment]
Is this issue available?

**Comment by rickr** [comment]
@RobKriner @hollomancer Are we still OK with threadless?

**Comment by hollomancer** [comment]
@rickr Threadless creds in 1password. Let's move forward on this

**Comment by sethbergman** [comment]
Did you guys have a chance to take a look at the admin dashboard here:
[Operation Code Store](http://operation-code.mybigcommerce.com)
@rickr @hollomancer

**Comment by rickr** [comment]
I don't think we have the bandwidth to manage inventory and shipping right now but I do want to keep this in our pocket for when we do.

@sfillm07 - lets go ahead and move forward with threadless. 

Our store URL is https://operationcode.threadless.com/

I don't see a place to stick a new menu item so unless anyone objects lets just add a link to the footer under the 'Get Involved' section with a title 'Operation Code Store'.

**Comment by sethbergman** [comment]
You don't have to manage inventory. It's optional. Also, go through the checkout process and abandon your cart. There is a great feature built in to recover abandoned carts. You can customize the emails that go out and offer coupon codes to get the lost sale. Spend a little time in the backend and look at the features. I'm almost certain that I can get you a great deal because of my relationships with Bigommerce.

**Comment by sethbergman** [comment]
There's also an automated shipping manager for any orders. Just print the label and ship it!

**Comment by sethbergman** [comment]
If you need the shirts made then I have a great resource for this also. What are you going to be paying for the Threadless service?

**Comment by sethbergman** [comment]
Is the issue that you need a system that will handle shipping your orders?

**Comment by rickr** [comment]
Lets move discussion to https://github.com/OperationCode/operationcode/issues/631.

**Comment by sfillm07** [comment]
What is the username for the account?

I tried operationcode, operation_code, oc

**Comment by rickr** [comment]
I don't think you'll need the username for the account. This should just be adding a link to https://operationcode.threadless.com/ to the footer.

**Comment by sfillm07** [comment]
Copy

Sean

**Comment by sfillm07** [comment]
@rickr can we close this issue?

**Comment by rickr** [comment]
We can as this was fixed in #633
