### ISSUE TITLE
Add map of all code schools

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#272]
_As a visitor, I want to see a geographical map of where all the code schools in the country are, so that it's easy for me to tell which ones are near my location._

**Product Requirements**
The code schools page has a map above the fold, showing where code schools are in the continental US.

**Technical Requirements**
We can leverage the veterans/map code to do this easily.
- [ ] Add an `all` method to `lib/code_schools.yml`
- [ ] Move the veterans/map code to /maps/veterans
- [ ] Reuse that same code to create /maps/code_schools

Stretch goal:
- [ ] Color code schools accepting the GI bill in green.

**Comment by hd719** [comment]
Hello there! I am new to open source and I would like to contribute to this project.

**Comment by hollomancer** [comment]
Added you as contributor

**Comment by hd719** [comment]
Hey @hollomancer I checked the `lib` folder I could not find the `code_schools.yml` file, but I did find the `code_schools.rb` file.

**Comment by rickr** [comment]
The method should be added to `code_schools.rb`. That's a typo in the issue.

**Comment by hd719** [comment]
Hello @rickr I keep getting an `Uninitialized Constant OperationCode` error when I try run `make setup`

Full Error: 

```
docker-compose run web rake db:create
rake aborted!
NameError: Cannot load `Rails.application.database_configuration`:
uninitialized constant OperationCode
(erb):7:in `<main>'
/usr/local/bundle/gems/railties-4.2.5.2/lib/rails/application/configuration.rb:104:in `dat
abase_configuration'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/railtie.rb:41:in `block (3 l
evels) in <class:Railtie>'
/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
NameError: uninitialized constant OperationCode
(erb):7:in `<main>'
/usr/local/bundle/gems/railties-4.2.5.2/lib/rails/application/configuration.rb:104:in `dat
abase_configuration'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/railtie.rb:41:in `block (3 l
evels) in <class:Railtie>'
/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create => db:load_config
(See full trace by running task with --trace)
make: *** [db_create] Error 1
```

**Comment by hd719** [comment]
Hello @rickr I am getting a `NameError: Cannot load `Rails.application.database_configuration`:
uninitialized constant OperationCode`, this happens when I run `make setup` in the command line. I have done `bundle install` and installed the gems. 

Full Error: 

```
docker-compose run web rake db:create
rake aborted!
NameError: Cannot load `Rails.application.database_configuration`:
uninitialized constant OperationCode
(erb):7:in `<main>'
/usr/local/bundle/gems/railties-4.2.5.2/lib/rails/application/configuration.rb:104:in `dat
abase_configuration'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/railtie.rb:41:in `block (3 l
evels) in <class:Railtie>'
/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
NameError: uninitialized constant OperationCode
(erb):7:in `<main>'
/usr/local/bundle/gems/railties-4.2.5.2/lib/rails/application/configuration.rb:104:in `dat
abase_configuration'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/railtie.rb:41:in `block (3 l
evels) in <class:Railtie>'
/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create => db:load_config
(See full trace by running task with --trace)
make: *** [db_create] Error 1
```

**Comment by rickr** [comment]
@hd719 That looks like a bug. #724 has been filed. Fix coming shortly.

**Comment by rickr** [comment]
@hd719 Fix has been merged into master. Please pull in the latest changes and reopen #724 if you're still having issues.

**Comment by hd719** [comment]
Hello @rickr to configure the map to display all the code schools, 

I have quick question in the `codeschools.yml` file it does not show the latitude and longitude for the code schools. I was wondering do I have to add the latitude and longitude coordinates separately for each of the individual code school or is there an automated process that implements that? 

-Thank you.

**Comment by rickr** [comment]
Hi @hd719 

Is Lat/Long required? We should have the address and at the very least the city/state for each school if that's helpful.

**Comment by hd719** [comment]
@rickr 

Hey, so the reason I ask is because the map API requires coordinates.

**Comment by rickr** [comment]
Hrm ok. If that's the case we'll need to store lat/longs for the schools. For now you can just omit schools that don't have a lat/long from the listing of code schools for the map and we can add them over time.

**Comment by hd719** [comment]
Hey @rickr and @hollomancer again sorry for the bother, but any update on the pull request

**Comment by rickr** [comment]
Hey @hd719. Apologies for the delay. I've been super underwater lately. I'll try to get to this today.
