### ISSUE TITLE
Style signup form errors

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#274]
They're currently pretty ugly.

Stretch goal: Get them to be inline with the form.

**Comment by davidmolina** [comment]
@rickr, can we close? Looks ok on desktop and mobile.

**Comment by rickr** [comment]
I don't think so. If you just submit the form with no email or zip you'll see the attached pic.
<img width="947" alt="screen shot 2016-09-02 at 10 50 39 am" src="https://cloud.githubusercontent.com/assets/334550/18207894/2713dbfe-70fb-11e6-8e26-d1e9431f78ac.png">

**Comment by rickr** [comment]
Closing due to redesign
