### ISSUE TITLE
Implement wall of commits

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#280]
When a new user signs up, in order to get them hooked on programming, we should have a guide that allows them to add their name and a message to a page that we serve.

The page:
- can be served out of /public
- may or may not be HTML
- should be editable on github without having to get the rails env setup
- have a better name than 'wall of commits'

The guide:
- should explain at a very high level, git, github, HTML, CI/CD
- should be WAY easy to follow
- leave the user wanting to contribute in a more meaningful way.

**Comment by davidmolina** [comment]
Idea: OAuth with GitHub which forces everyone to get/sign in to their GitHub account. 

New users are expected to do the Hello World tutorial.

**Comment by rickr** [comment]
This is now done via operationcode_bot's Operation Code Challenge.
