### ISSUE TITLE
Conditionally display certification

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#282]
Since we accept civilians as mentors/volunteers the 'I certify' submit button on the sign up page should be changed to a checkbox that is conditionally displayed if you select a branch of service.

Additionally, to be a bit more explicit we should add a 'none' or 'civilian' to the drop down.

**Comment by davidmolina** [comment]
Roger. 

That `first blank` was that part. But there was no welcome_mailer for new mentors to match it. 

Ideally, there is, and they get that welcome note that Conrad and Rob drafted.

**Comment by hollomancer** [comment]
This is no longer a part of our signup flow.
