### ISSUE TITLE
Auto-add new members as repo contributors

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#283]
_As an organization admin, I want new members of Operation Code to be automatically added as repo contributors to OperationCode/operationcode and /operationcode_bot, so that they don't have to be added manually._

**Challenges**
- [] We'll need to associate Slack users with Github users if we want to do this.

**Comment by davidmolina** [comment]
That. Also, should be a bot somewhere, `/github Add @david to contributors`

**Comment by hollomancer** [comment]
The idea here is that they're automatically added to the 'contributors' team in Github. That means they can be assigned issues.

**Comment by hollomancer** [comment]
https://developer.github.com/v3/orgs/teams/#add-or-update-team-membership looks like it'll do the trick.
