### ISSUE TITLE
Design: Volunteer Landing

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#284]
_As a potential mentor volunteer, I would like a way to sign up for Operation Code that does not emphasize military background._

Functional requirements:
- Would like a separate form for mentors to sign up, invite to Slack.
- This can just be an alternate landing for #282.
- Field for specialty
- Field for years of experience
- Field for blurb about why you want to be involved

Technical requirements:
- Identify the commonalities between the mentor/veteran forms.
- Extract them to a partial
- Modify registrations controller to detect if a user is signing up as a vet or mentor (default to vet)
- If veteran, mix the veteran partial, if mentor mix in the mentor partial

**Comment by hollomancer** [comment]
Would like a separate form for mentors to sign up, invite to Slack

**Comment by hollomancer** [comment]
This can just be an alternate landing for #282

**Comment by cherstewart** [comment]
Yes, please!

**Comment by rickr** [comment]
How would we vet new mentors? Would adding a `i would like to be a mentor` check box to the form suffice?

**Comment by cherstewart** [comment]
I would probably add a bit more than that, maybe specialty, years of experience and a blurb about why you want to be involved, just to put in an extra bar for people who truly want to be involved. Just my two cents. :)

**Comment by davidmolina** [comment]
Should be sufficient.

**Comment by rickr** [comment]
Ok - I think we can do all that relatively cleanly!

**Comment by rickr** [comment]
Simplifying a bit. This PR will now:
* Add a route called /mentors/sign_up
* Render the same signup form
* Automatically mark the new member as a mentor

**Comment by davidmolina** [comment]
Woohoo!
