### ISSUE TITLE
Mentor Landing: Link to Mentor SOP

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#285]
_As a potential mentor volunteer, I would like to see the guidelines behind being a software mentor before I sign up, so that I know what I'm getting into._

This can be a link to our Github mentor page in a new tab, as an MVP.

**Comment by hollomancer** [comment]
Add copy from Google Drive doc re: Mentor SOP

**Comment by divayprakash** [comment]
@hollomancer I'd be willing to take a crack at this. Let me know what you're looking for!

**Comment by hollomancer** [comment]
@divayprakash, short version - we want to get the content from https://github.com/OperationCode/mentorship into the page at https://operationcode.org/mentorship, so that we can better describe the current offerings our mentorship program has.

**Comment by divayprakash** [comment]
@hollomancer Working on it!

**Comment by divayprakash** [comment]
@hollomancer Sorry but I'm unable to understand how to do that. The structure of this repository is a bit confusing for me since I'm a beginner so could you be a bit more descriptive as to how I should go about the same?

**Comment by jzinna** [comment]
@hollomancer I presume you want to have the text on the webpage itself, not just a link to the GiHub page, right?
