### ISSUE TITLE
Style Flash Messages

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#296]
Log in or log out of a profile to see an unstyleized flash message. They should be styled.

Keep in mind that flash messages are set in the application layout. On the main page this disrupts the images. We can either redirect to the sign in page when someone logs out or figure out a way to do flashes in a non invasive way. Maybe a toast? http://materializecss.com/dialogs.html

**Comment by mwagz** [comment]
I'd like to tackle this one.

**Comment by rickr** [comment]
Closed in #566
