### ISSUE TITLE
Remove vendor/bundle

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#324]
From travis:

> ```
> ###### WARNING:
> Removing `vendor/bundle`.
> Checking in `vendor/bundle` is not supported. Please remove this directory
>   and add it to your .gitignore. To vendor your gems with Bundler, use
>   `bundle pack` instead.
> ```

**Comment by Shruti9520** [comment]
@rickr I would like to work on this issue.

**Comment by rickr** [comment]
@Shruti9520 - thanks for wanting to work this issue. It looks like vendor/bundle may not exist anymore. Could you confirm that for me?

**Comment by sfillm07** [comment]
It does not look like this file exists.

**Comment by rickr** [comment]
Ok then, closing this issue.
