### ISSUE TITLE
Home page images breaks responsive navbar on Mobile

### ISSUE THREAD

**Issue by nanoxd** [OperationCode/operationcode#33]
Images on home page break the responsive nav bar. Specific model was iPhone 6. Can be replicated via Chrome  with a resolution of 375x667 and a device pixel ration of 2

[Preview](https://vid.me/a2I1)

**Comment by davidmolina** [comment]
Hmm. I'm using iPhone 5.

**Comment by Wimsy113** [comment]
Let me check it on my 6 and see

**Comment by davidmolina** [comment]
@Scripore contribution 47dc437 fixed this.
