### ISSUE TITLE
Move guidestar logo into asset pipeline

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#342]
Current image is linked to github: 
` +        <img src="https://camo.githubusercontent.com/ad78997b7ab7b62d4f93b59860b1e19821676b58/687474703a2f2f776964676574732e6775696465737461722e6f72672f6778696d616765323f6f3d39353232313031266c3d7633" data-canonical-src="http://widgets.guidestar.org/gximage2?o=9522101&amp;l=v3" style="max-width:100%;"></a></p> `

It should be in the asset pipeline.

**Comment by dmarchante** [comment]
@rickr @davidmolina Is there a way to acquire the logo with a transparent background and better resolution? Viewing the image on a mobile device revealed the low resolution. Also, now looking at it, I would use the logo with out the text and add it in manually.

**Comment by davidmolina** [comment]
We have the vector file.

**Comment by rickr** [comment]
OBE - Guidestar's instructions have us hotlinking. Fixed in #349
