### ISSUE TITLE
Marketing: ID high-profile sponsors

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#352]
Having high-profile sponsor logos on our main page will help strengthen Operation Code, and allow us to recognize sponsors who have contributed so much to our success.

**Comment by rickr** [comment]
This is a great idea! You're thinking of something like those startup type 'Our Customers' with all their logos and everything right?

I'm going to put this on hold for now. It seems like we may want to do a bit of a redesign on the main page so lets sort that out first. Opened up #355 for that discussion.

**Comment by hollomancer** [comment]
Yep, exactly. We should probably identify one row of these (two rows always looks cluttered), validate our permission to use their branding, and add below the main image on the front.

**Comment by davidmolina** [comment]
Going ahead and taking this... @rickr @hollomancer

**Comment by hollomancer** [comment]
Github should be here, at a minimum.
