### ISSUE TITLE
Layout bug on the About page

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#362]
![image](https://cloud.githubusercontent.com/assets/9288648/17388465/5f600854-59ca-11e6-8640-7133947b995f.png)

**Comment by davidmolina** [comment]
@hollomancer: using safari and not seeing a problem.

**Comment by davidmolina** [comment]
Disregard. I see the problem.

**Comment by codedoll** [comment]
@rickr this was fixed, not sure when. It wasn't me who made the PR.

<img width="1324" alt="screen shot 2016-10-05 at 6 21 05 pm" src="https://cloud.githubusercontent.com/assets/17578236/19133860/982fedf4-8b28-11e6-8de2-e79ca5d60b3b.png">
<img width="854" alt="screen shot 2016-10-05 at 6 21 31 pm" src="https://cloud.githubusercontent.com/assets/17578236/19133864/9e3b36cc-8b28-11e6-9abc-2e8922af8aa4.png">

**Comment by rickr** [comment]
👍 @codedoll - closing.
