### ISSUE TITLE
Facebook shows the /veteran/sign_up icon as guidestart not the OpCode logo

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#372]

**Comment by rickr** [comment]
I think we should just need to follow the directions here: https://developers.facebook.com/docs/sharing/webmasters#markup

To add the og:image tags to application.html.erb to point to our logo. 

You could also think about adding https://github.com/kpumuk/meta-tags

**Comment by davidmolina** [comment]
@rickr, most definitely. Reviewing the docs.

**Comment by sfillm07** [comment]
I added the og: image code to the application.html.erb like the docs stated.  I tried to create a new pull request but it looks like it added it to the request I posted yesterday.  I used the largest logo we had on the squarespace page, need to test to see how it looks.
