### ISSUE TITLE
Add /amazon-smile copy

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#373]
Amazon Smile

How Does it Work?

1. Visit smile.amazon.com.
The entire shopping experience is the same and most products available on amazon.com are available at AmazonSmile.

2. Sign in and Choose Your Charity
The screen will look slightly different depending on whether or not you’re already signed into Amazon. If you’re already signed in, simply search for “Operation Code” and proceed to step 3.

3. Select “Operation Code”
When you search for a charity, such as “Operation Code,” you will receive an email confirmation and you can begin shopping.

4. Begin shopping!
Once you’ve selected "Operation Code" everything else functions the same. Shop for your favorite products or the perfect gift. Most products are eligible on Amazon Smile–if not, you’ll be notified. You can checkout normally as well. No extra cost is passed onto you–Amazon will donate 0.5% of your purchase to Operation Code!

5. Share with your friends
After you’ve successfully completed a purchase on AmazonSmile you can share the news with your friends on Facebook, Twitter or via email. This option appears on the confirmation page after your order is complete. (edited)

**Comment by davidmolina** [comment]
Going ahead and taking this... @rickr

**Comment by davidmolina** [comment]
^^ Add the FAQ.

**Comment by davidmolina** [comment]
This [commit](https://github.com/OperationCode/operationcode/commit/7286c92d0de5b5e16b951f4e50dc46dbd421dcaa) fixes this.
