### ISSUE TITLE
Add /internships copy

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#375]
How does this work? 

***
Operation Code is Seeking Legislative Interns

Are you interested in being part of Operation Code's mission? 
Interns will assist the legislative lead in implementing strategies to increase coding education opportunities for our serving and returning service members.

Job Responsibilities Include:
Aid in the development of Operation Code's legislative strategies
Building and maintaining relationships with state and Federal legislative offices
Drafting memos, emails, newsletters and lobbying materials
Participate in strategy meetings and calls
Serve as a liaison for Operation Code in meetings with legislative staff
Provide updates to Operation Code board/management

You:
Excited to improve the life of our service members
Excellent communications skills
Ready to do some research
***

**Comment by rickr** [comment]
Fixed in #516
