### ISSUE TITLE
Add Codeup to /code_schools

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#376]
According to this article, Codeup is VA approved: http://www.bizjournals.com/sanantonio/news/2016/07/12/veterans-enlistedat-sa-tech-school-get-full.html.

**Comment by davidmolina** [comment]
Going ahead and taking this... @rickr @hollomancer

**Comment by jotasprout** [comment]
If this is still open, I'll take it and crank it out.

**Comment by jotasprout** [comment]
Working on it now.

**Comment by jotasprout** [comment]
If this is still needed, I can take it on.

**Comment by rickr** [comment]
Go for it @jotasprout !

**Comment by jotasprout** [comment]
Rock on. I'm going through the Contributor instructions setting up my environment now.

**Comment by jotasprout** [comment]
Nevermind. I've spent hours trying to get this Ruby environment installed and configured on both my Ubuntu laptop and iMac. Each is having it's own problems. I give up.

**Comment by jotasprout** [comment]
When I try to install redis using brew, I get two errors that it couldn't link a couple directories and that I should delete those paths and run 'brew update.' That doesn't mean to delete the directories, does it? Is there a file in which I should delete references to them?

**Comment by jotasprout** [comment]
I can find the page in question on the live site but not in the files cloned to my local repo.

**Comment by jotasprout** [comment]
Any direction would be awesome.

**Comment by rickr** [comment]
Hi @jotasprout thanks so much for pinging again. Really sorry I dropped the ball in your first replies. 

Code Schools are managed through [https://github.com/OperationCode/operationcode/blob/master/config/code_schools.yml](config/code_schools.yml).

You should just be able to add this school there and see it show up on code_schools

**Comment by jotasprout** [comment]
That gives me a 404. While I found a "blog" folder, there's no "master" folder inside it.

**Comment by rickr** [comment]
Ah - I think I mixed up my URL markdown. This is the link:
https://github.com/OperationCode/operationcode/blob/master/config/code_schools.yml

**Comment by jotasprout** [comment]
What is this witchcraft? How does that work? It's the same URL.

**Comment by rickr** [comment]
Haha - I used the following markdown: `[https://github.com/OperationCode/operationcode/blob/master/config/code_schools.yml](config/code_schools.yml)` which has the URL and the link text backwards relatively linking to `config/code_schools.yml`.

**Comment by jotasprout** [comment]
Just submitted the pull request. Newbie question re: the markdown--why would you do that? Also, should I really finish a Ruby course or two before seeking out further operationcode issues to help with?

**Comment by rickr** [comment]
I was just trying to make the message read a bit easier. If I had done it correctly it would look like this: [config/code_schools.yml](https://github.com/OperationCode/operationcode/blob/master/config/code_schools.yml)

A lot of our beginner friendly issues are small HTML or CSS fixes so I'm sure you can still contribute, although learning rails would not be a bad thing!

**Comment by jotasprout** [comment]
The courses I've chosen (based on research using the infallible Internet) to start just focus on Ruby. Your thoughts?

**Comment by rickr** [comment]
If you're interested in webdev and rails having a good background in ruby won't hurt =) 

This issue was fixed in #530. Thanks @jotasprout
