### ISSUE TITLE
Include our video on main page

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#382]

**Comment by davidmolina** [comment]
Going ahead and taking this... @nellshamrell

**Comment by davidmolina** [comment]
It's already on homepage. Closing this.

**Comment by davidmolina** [comment]
![screen shot 2016-08-20 at 3 23 56 pm](https://cloud.githubusercontent.com/assets/1848616/17834208/220f01e4-66ea-11e6-9fe0-33375f0ea1e1.png)
