### ISSUE TITLE
Add code school logos to code school scholarships page

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#387]
Let's add graphics to the code school scholarships page, and draw some extra attention to our partners!

**Comment by davidmolina** [comment]
Going ahead and taking this... cc @nellshamrell

**Comment by aaron-suarez** [comment]
So, it looks like this is still open. Can I take it?

**Comment by aaron-suarez** [comment]
So this was my interpretation of what we were trying to add here. Obviously, the next step is to add all of them, but this shows the first logo.

![with-sabio-logo](https://cloud.githubusercontent.com/assets/2008701/19876396/b92686b4-9fa3-11e6-89fe-3d5bc44d13ed.png)

**Comment by rickr** [comment]
I think this requires a bit more thought. 

My initial questions:
* What's the source of these logos? 
* What if they can't be reduced down to fit in this table? 
* Where are they going to be hosted?

**Comment by aaron-suarez** [comment]
In my current implementation, the pictures are stored in operationcode/public and the original source is the website. I haven't ran into any size reduction problems thus far. This is where I'm at:

![with-three-logos](https://cloud.githubusercontent.com/assets/2008701/19877773/1f5b811c-9fb0-11e6-8afa-9b90d13a3994.png)

**Comment by rickr** [comment]
That doesn't look too bad. What does it look like if the logos are on the left side and you align all the text on to the right of them?

**Comment by aaron-suarez** [comment]
Here's how it looks with the logos on the left. What do you think?

![logos-on-left](https://cloud.githubusercontent.com/assets/2008701/19914077/bc51964e-a075-11e6-9607-725a7729c14c.png)

**Comment by aaron-suarez** [comment]
So.. the only logos added in PR #561 were for the section "VA Approved Schools". Were we also trying to add logos for the section "Code School Scholarships" and "Code Schools by State"?

**Comment by rickr** [comment]
Can you try centering the logos?

Yea - I think if we are going to add logos we should add logos to every school.

**Comment by hollomancer** [comment]
For the front page, we definitely need logos. @rickr @davidmolina - what do you think of having a separate PR for the front page and the code schools page? Reason being, the front page has a bit more urgency re. how we present these schools

**Comment by rickr** [comment]
#548 covers adding schools to the front page. It should be reusing the code from this PR unless we just want to stuff logos onto the main page.
