### ISSUE TITLE
Feature:  "Join" Buttons

### ISSUE THREAD

**Issue by jeremyshorelinepark** [OperationCode/operationcode#392]
The existing "Join Now And Get Coding" button on the homepage should be brought up to be placed 'above the fold' and be immediately visible once visitors reach the homepage. The idea is to increase speed to signup and not make them scroll down for the button. 

Users can also signup on the Nav bar in the right-hand corner, but "Join" doesn't stand out in relation to the other information they are greeted with. My suggestion is to make that another green button to draw attention to it. Since it's on the nav bar, another benefit is users will always see the Join button no matter where they're at on the website. For example, a user wants to learn more about Operation Code before they sign-up. So they go to the "About" page, read up, and decide to join. Having a green button in the right-hand corner on the nav bar would always make it obvious where they should click to "Join".

**Comment by davidmolina** [comment]
@jeremyshorelinepark: would you like to take this one, or just a recommendation?

**Comment by rickr** [comment]
Hi @jeremyshorelinepark - thanks for the feedback! This is actually a dup of #380 so I'm going to close this ticket and ask all discussion be moved there.
