### ISSUE TITLE
Create Environment Set-up Wiki

### ISSUE THREAD

**Issue by jpphaneuf** [OperationCode/operationcode#395]
From Zero to Hero....I'm a complete noob and find I'm stumbling around just trying to get GitHub and Atom working....and learning all the acronyms, etc...

**Comment by davidmolina** [comment]
@jpphaneuf: Perfect recommendation! I found it challenging learning this stuff when I first got started. If it wasn't for Baltimore Ruby on Rails group, and Jared and a few others, might have taken longer.

**Comment by jpphaneuf** [comment]
Cool! In our Basic, we would always break down teaching points into Squads....Like coming to attention is:
Squad 1: Right knee is brought perpendicular to.....blah
Squad 2: Both clenched hands positioning beside the seam....blah
Squad 3: Blah, Blah...

Final product is achieved on completion of the last squad....and you chant out the Squads as you perform them to increase muscle memory.....

Basically, I'm sure there's a similar teaching concept used in most militaties that we can structure some newbie lessons on how to get started. I'm sure the info is out there, but I know for me sometimes with my PTSD, I'm like a squirrel going down rabbit holes....easy to get lost! ;)

*I'm actually more just rambling to test using the GitHub feautures and learn how to collaborate. (That could be a cool idea....gamification of the learning for OperationCode???)

**Comment by rickr** [comment]
Where would you like this info to be? We have [CONTRIBUTING.md](https://github.com/OperationCode/operationcode/blob/master/CONTRIBUTING.md) - would it be a different doc? An addition to this one?

**Comment by jpphaneuf** [comment]
I don't think making a new document would be required now that I've dug in and found the CONTRIBUTING.md section....I was just having a hard time getting my environment "set-up" but have realized that there are so many variables that I don't know that a step by step install process can be maintained up to date. Between Codecademy, Lynda and the documentation in Operation-Code I think I might of figured it out...which I suppose is the ultimate teaching point that I needed to learn....how to find solutions using various sources!

**Comment by hollomancer** [comment]
Maybe a GETTING_STARTED.md?

**Comment by rickr** [comment]
In addition? My concern would be to have too many choices for a new user. What would be the deliminator for content in CONTRIBUTING and GETTING_STARTED?

**Comment by jpphaneuf** [comment]
Have to agree with Ryan regarding document control and having too many options....so I recommend adding in a newbie section, the ones like me coming in and the last language they used was BASIC on a Commodore 64. How do I even set up the "environment" to just be able to follow along kind of stuff...but I will say there's a sense of accomplishment for figuring it out...overcoming the struggle...resonates with me from basic training. 

JP Phaneuf
(iPhone)

**Comment by davidmolina** [comment]
@jpphaneuf: Right. Ideally just the CONTRIBUTING doc. Maybe we just make that more explicit somewhere on the website for newbies not knowing to look into the codebase.

**Comment by jpphaneuf** [comment]
A "REPORT FOR DUTY HERE" type link maybe...something catchier but you get
the gist ;)

**Comment by rickr** [comment]
Where do we stand on this issue? I'd like to add some specific tasks or close it out. I think maybe some rewording, encouragement or better intro in CONTRIBUTING.md?

**Comment by davidmolina** [comment]
Better rewording--no need to reinvent the wheel. 

-Dave
@davidcmolina
http://davidmolina.github.io

**Comment by jpphaneuf** [comment]
Agreed

**Comment by jpphaneuf** [comment]
Shall I close the issue?
