### ISSUE TITLE
K2 Data Science Scholarship

### ISSUE THREAD

**Issue by ty-shaikh** [OperationCode/operationcode#396]
Edit...scholarship no longer offered.

**Comment by rickr** [comment]
Hi @ty-shaikh - are you guys a code school? Are you looking to be listed on https://operationcode.org/code_schools ?

**Comment by ty-shaikh** [comment]
We are a special type of code school. We teach Python and machine learning. We are creating data scientists rather than computer programmers.

Getting listed in that directory would be great. We wanted to get listed here as well (https://operationcode.org/scholarships). In the code school scholarship sections. We also would like to showcase your logo and link to your site.

**Comment by hollomancer** [comment]
Thanks, @ty-shaikh! Will look at this. Let's talk more - staff@operationcode.org

**Comment by rickr** [comment]
We're good to add this. @ty-shaikh can you add yourself to [code_schools.yml](https://github.com/OperationCode/operationcode/blob/master/config/code_schools.yml) and submit a PR?

Can you also open a new ticket to add yourself to /scholarships? If you want to open a PR to add yourself there too that would be great. If not please include the copy you'd like to see on that page.

Thanks!

**Comment by ty-shaikh** [comment]
Hey @rickr - We had to pivot our business model to a self-paced program. Instead of live streaming classes at night, everything is pre-recorded. We also dropped our price significantly, so we have no availability for scholarships at this time. Hopefully soon, we can restart them. Feel free to close and delete this issue.

**Comment by rickr** [comment]
Will do - thanks for the update!
