### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by nellshamrell** [OperationCode/operationcode#40]
When I attempt to run tests with this command:
```bash
  $ npm install && bower install && npm test
```

I get this response:
```
➜  operationcode git:(drop-down-menus-on-hover) ✗ npm install && bower install && npm test
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! path /Users/nellshamrell/Projects/open-source/operationcode/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34

npm ERR! package.json ENOENT, open '/Users/nellshamrell/Projects/open-source/operationcode/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nellshamrell/Projects/open-source/operationcode/npm-debug.log
```

Looks like there should be a package.json file in the repo?  Or is that something I should create on my own?

**Comment by davidmolina** [comment]
Thanks @nellshamrell. Let me take a look on my end. Looks like we're missing we're missing the package.json file.

**Comment by davidmolina** [comment]
Whoa, @nellshamrell. I'm getting the same error. /cc @nanoxd

**Comment by davidmolina** [comment]
@nellshamrell - look for the invite on Slack. We were just talking about this, this or last week and using something to test.

**Comment by nanoxd** [comment]
Hey @nellshamrell! Looks like our contribution guide is wrong. Sorry about that. In the meantime the following commands should get you up to speed:

```
bundle
bundle exec rails s
```

**Comment by nellshamrell** [comment]
I did those to get the environment set up, but are there existing tests I need to run before submitting a pull request? I have a fix for an issue :)

**Comment by davidmolina** [comment]
Hey @nanoxd! Thanks for revising those! / @nellshamrell - no existing tests setup now, so no. Send fixes over. Thanks :)

**Comment by nellshamrell** [comment]
Got it!
