### ISSUE TITLE
Move off Heroku

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#403]
Heroku and AWS are costing us an arm and a leg. Let's evaluate what cloud platforms are most sustainable for us as a nonprofit.

**Comment by davidmolina** [comment]
Yes.

**Comment by hollomancer** [comment]
@rickr, what do we need in terms of infrastructure for an MVP against Digital Ocean? @nellshamrell - any thoughts?

https://www.digitalocean.com/community/tutorials/how-to-manage-your-multi-node-deployments-with-rancher-and-docker-machine-on-ubuntu-14-04

**Comment by rickr** [comment]
We'll need to dockerize the rails app, postgres, redis, and whatever else I may be missing. 

Created a new milestone here: https://github.com/OperationCode/operationcode/milestone/12

**Comment by rickr** [comment]
First batch of tickets have been created. Going to close this out.
