### ISSUE TITLE
The home landing page seems a little too verbose

### ISSUE THREAD

**Issue by dengjonathan** [OperationCode/operationcode#408]
While looking at the homepage- I think it might have too much information on it, potentially confusing new users/ possible partners.  

I think an ideal home page would do three things:
1. Explain what operation code is tersely 
2. Show how to get started in 5 minutes
3. Provide links to docs that will allow a user to dive deep if they're interested

I am using the yeoman project's landing page http://yeoman.io/, as an inspiration for this.

One specific example is in the hero (div.slider) on the homepage. The slide captions are too long for the casual reader to glance at before the slide changes.

My main concern is that veterans who are just starting to learn to code may be turned away because of the rush of information.  

I saw Issue #355 was about finding a new layout for the home page, but we should also take the opportunity to reduce the homepage text.  This will make the burden of updating it less onerous and I think for accessibility (a large portion of veterans are medically retired for health reasons), less text is better.

I'm going to submit a pull request with just text updates in the template for now, but I think we should update the copy throughout the site.

**Comment by hollomancer** [comment]
Hmm, should we break this up into smaller issues including #409?

**Comment by rickr** [comment]
I agree the home page feels a bit heavy on text. Lets use this issue to discuss and then break out actionable items into tickets in this new (milestone)[https://github.com/OperationCode/operationcode/milestone/11]. We'll probably need a ticket to generate the copy and then push those updates out per section we want to change.

@jeremysb1 do you have any input here?

**Comment by jeremysb1** [comment]
@rickr I do. I'll make a Jing video. Right now it's overkill imo and we could get the point across more concisely. My thoughts are also consistent with my thoughts on the navigation menu, which I have a new video and will be creating a new ticket for. We should definitely create a larger ticket that gets broken up into smaller issues @hollomancer.

**Comment by jeremysb1** [comment]
I've done major homepage redesigns and complete rebrands with product and marketing teams. During Thursday's meeting, I'll bring some questions around this which will guide us to make this happen.

**Comment by jeremysb1** [comment]
The first thing we should do is make the best use of our current real estate on the homepage. 

As a user, I want to join and/or sign up for a newsletter when I first arrive at the homepage and don't want to have to read a lot of text to figure out what the organization is about. The ideal solution is for new joiners to sign up at the welcome gate when they first arrive to the website.

Please see this video and the website below for visual clarification: 

http://screencast.com/t/j9gXPF0rgxE
http://www.appsumo.com/buildfire/

To break down the video:
1. Eliminate the current graphic and text at the top of the homepage;
2. Make the space where the graphic and text was the same color as the rest of the site;
3. Create welcome gate with:  a heading of Operation Code and a simple sentence of what we're about centered to the left of the page; and a sign up form asking for an email and zip code centered to the right with a "Join" button;
(4) Eliminate the current signup fields and button on the homepage, but leave the "Join" button on the Navigation menu; and 
(5) users are to be brought to the welcome gate, not the area where they currently are brought to.

**Comment by rickr** [comment]
Closing due to redesign
