### ISSUE TITLE
Extend slackbot functionality to greet new users

### ISSUE THREAD

**Issue by dengjonathan** [OperationCode/operationcode#410]
Our slack bot prototype could be extended to automate a lot of our onboarding process.  I think right now it involves a lot of change, i.e. people see that somebody new has logged in and they all say hello!  However, if a veteran is in a weird time zone or everyone just misses it, they could get no welcome at all, get confused and leave.  Our on-boarding experience should be more consistent, and the only way to do that without a support team is to automate.

Right now I think we're at the brainstorming stage, where we should discuss:

1. What the bot will say to each new user.  I propose the bot sends a quick shout out on the general channel saying welcome to Operation Code.  Then the bot should PM the user an HTML welcome sheet with links to FAQs, docs, and a testimonial from a new user to motivate them.

2. The new user might have some questions that a slack bot can answer.  Simple stuff like What is operation code?, who founded operation code?  How do I get a job? I was playing around with this API https://wit.ai/, but I think there's lots of stuff out there we can use to do NLP on user requests.

3. Eventually this slackbot could be extended to do some analytics.  I.e. it could do a random survey and ask users why they joined, what their goal is,  and save this info to a file/ db.  This could be used by the development team to present to possible sponsors.

**Comment by hollomancer** [comment]
Will review and break this up into sub-issues later in the week.

**Comment by hollomancer** [comment]
@dengjonathan @jeremysb1 - can we generate some copy for this? I can get this going now.

**Comment by jeremysb1** [comment]
[https://docs.google.com/document/d/1y8hwuH75rZXaOr9cfAnRmD05KDI5RUV_vQIGdvzfj3k/edit?usp=sharing](url)

This is just initial Slackbot copy to introduce new users on the general channel. More is forthcoming to address onboarding.

**Comment by hollomancer** [comment]
Copy is up and bot is online in Heroku. Closing this, additional work will be in separate tasks.
