### ISSUE TITLE
Add split gem

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#411]
https://github.com/splitrb/split

This gem will allow us to do self hosted A/B testing.

Please check to make sure the management console is protected by at least basic auth

**Comment by hollomancer** [comment]
This is necessary technical work that will allow us to start doing A/B testing of copy, images, and layout on our site.

**Comment by hollomancer** [comment]
http://recipes.sinatrarb.com/p/middleware/rack_auth_basic_and_digest should do the job.
