### ISSUE TITLE
Navigation Menu Cleanup

### ISSUE THREAD

**Issue by jeremysb1** [OperationCode/operationcode#413]
The current navigation menu is cluttered imo. Below is a way to reduce the clutter with two of the current menu options.

Users and site visitors could opt to "Contribute" to Operation Code by clicking on a "Contribute" option on the navigation menu where "Donate" and "Shop" currently exist. Donate and Shop would then become categories under Contribute with the existing subcategories of each remaining intact.

To execute:  (1) Condense "Donate" and "Shop" under a new navigation menu heading of "Contribute" with Donate and Shop being categories under "Contribute"; and (2) the existing subcategories under "Donate" (square cash, dwolla, and online) and "Shop" (AmazonSmile) remain. 

Please see the following Jing video for further and visual clarification:

http://screencast.com/t/H11Z0fwY5av

**Comment by rickr** [comment]
Great idea and excellent ticket!

**Comment by jeremysb1** [comment]
Thanks @rickr ! Less is more in design.

**Comment by rickr** [comment]
Fixed in #426
