### ISSUE TITLE
Contribution options from the Nav Menu

### ISSUE THREAD

**Issue by jeremysb1** [OperationCode/operationcode#414]
Question:  how would users/site visitors learn how they can become sponsors, mentors, volunteers, or open source contributors once they arrive at the homepage?

Currently, they need to scroll down to the bottom of the homepage and find the options under "Contribute". 

Upgrade Fix:  All of the categories under "Contribute" at the bottom of the page - "Sponsors", "open Source Contributions", "Mentors", and "Volunteers" - should be accessible from the navigation menu under ["Contribute](https://github.com/OperationCode/operationcode/issues/413)" (issue 413)  along with "Donate" and "Shop". 

Please see the Jing video below for further visual clarification:

http://screencast.com/t/xevWuy5l

**Comment by rickr** [comment]
Closing due to redesign
