### ISSUE TITLE
Create a programming term glossary

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#415]
It should be in alphabetical order. 
It should be searchable.

Can we use the github wiki?

**Comment by hollomancer** [comment]
I've been wanting to do this, and a recommended reading list, for a little while. Do we want to host and update ourselves, or link out to other sites?

**Comment by AshTemp** [comment]
I think we need a space for all the awesome links we've been passing around lately. Like a place that says START HERE for the uber beginner! 

IE:
Definitions
How to Git.
Examples, pictures, videos, etc.

**Comment by hollomancer** [comment]
https://github.com/OperationCode/mentorship is where this stuff lives now.
