### ISSUE TITLE
Link Slack handle to Operation Code account

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#416]
@rickr - we're exploring Salesforce integration, to link between Slack, our website DB, and when we last contacted mentees. Looking at exporting our current user list into a CSV, for import into Salesforce.

**Comment by rickr** [comment]
@hollomancer Is this a one time process or does there need to be an API?

**Comment by hollomancer** [comment]
I think this is going to need to be an API, unless Salesforce can point to the DB directly. I imagine it can, need to investigate.

Assigning to myself for research

**Comment by hollomancer** [comment]
This will need to happen in a different way.
