### ISSUE TITLE
Add Startup Institute to code school list

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#424]
Startup Institute

[Startup Institute](https://www.startupinstitute.com/) offers all veterans an [automatic $1,000 off](https://www.startupinstitute.com/admissions/scholarships/) the cost of their full-time program. Train to work in the innovation economy in the areas of web development, web design, digital marketing, or sales and account management. Additional scholarships are also available for: Women in Tech, People of Color in Tech, Seasoned Professional in Tech (age 40+), and Excellence in STEM. [Learn more…](https://www.startupinstitute.com/admissions/scholarships/)

**Comment by hollomancer** [comment]
Will need to get an image for this too.

**Comment by rickr** [comment]
This was added in #459
