### ISSUE TITLE
SEO: Top 5 in Google Search

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#425]
I want to ensure that Operation Code appears in the top five search items when google searching "Operation Code", so that people looking for our organization can find us.

**Comment by rickr** [comment]
IIRC there's a rails gem for SEO. Not sure if it's any good or not.

**Comment by kylemh** [comment]
@rickr can this issue be closed? "Operation Code" still yields us as number one on Google and Bing.

**Comment by rickr** [comment]
Yea. Lets go ahead and close this. If we want to take action on @rkerneggers additional terms please file additional tickets.
