### ISSUE TITLE
Mobile Menu has overlapping text

### ISSUE THREAD

**Issue by AshTemp** [OperationCode/operationcode#430]
As a user, when I view the mobile version of the page with a Chrome browser the menu squishes together. Menus should not squish. 
![image](https://cloud.githubusercontent.com/assets/19790104/18222966/7cb3b6ac-716d-11e6-8438-8421cc567d63.png)

**Comment by codigopluspluscom** [comment]
hey man! I can help!

**Comment by hollomancer** [comment]
@codigopluspluscom Let us know if you have a fix and submit a PR!

**Comment by rickr** [comment]
It looks like this has been fixed so I'm going to close the ticket. Please do feel free to jump into any of our other issues!
