### ISSUE TITLE
Build more end to end tests

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#435]
This is a placeholder for a larger epic. @rickr, I think that having new coders build some simple end-to-end tests is a good way of making the site more robust, instilling good habits, and getting them familiar with working in the code.

Even if they do break because we're iterating so fast :grinning: 

Thoughts?

**Comment by rickr** [comment]
We should already have a milestone for end to end tests. We really don't need to many and they shouldn't break. For now we probably just want to test sign up flow and donations.
