### ISSUE TITLE
Need to automate enrolled military/ veterans into Slack. 

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#44]
Possible use for Sidekiq (http://sidekiq.org/). /cc @nanoxd 
Onboarding should be automated, seamless

**Comment by ckib16** [comment]
@davidmolina Let me check with @saron of #CodeNewbie website. They have a great Slack channel and signup was seamless. Standby one...

**Comment by ckib16** [comment]
Ok here is their sign-up page using [TypeForm](typeform.com) - https://codenewbie.typeform.com/to/uwsWlZ

After that it looks like there are a few options:
1) Copy & paste from TypeForm each day/week
2) Automate the import by hacking together a script using these guidelines: https://levels.io/slack-typeform-auto-invite-sign-ups/

Hopefully Saron has come up with something else in the CodeNewbie flow. It was pretty quick for me to get my account.

**Comment by davidmolina** [comment]
@ckib16 -- that be rad if you can take a stab at it. @nanoxd had some good ideas as well. 

Let's keep this issue open until we resolve this.

**Comment by ckib16** [comment]
Update - Saron at CodeNewbie confirmed we talked about up above. Typeform -> Slack. The actual generation of Slack invites is a manual copy/paste of emails into Slack, or we can try the plugins like [slackin](https://github.com/rauchg/slackin) above.

**Comment by davidmolina** [comment]
Resolved in #48.
