### ISSUE TITLE
Stand up rancher on DO

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#441]
Might be useful: https://www.digitalocean.com/community/tutorials/how-to-manage-your-multi-node-deployments-with-rancher-and-docker-machine-on-ubuntu-14-04

**Comment by hollomancer** [comment]
Tested this out. @rickr - any opinions on docker-machine vs kubernetes?

Still waiting for DO's accounts credits to come in before moving too much further.

**Comment by hollomancer** [comment]
This is up. Need to determine whether we want a separate rancher-server-dev and rancher-server-test or not.

**Comment by hollomancer** [comment]
Single server for now, MVP.
