### ISSUE TITLE
Not providing a valid email address on signup reads "Email Please provide a valid e-mail address"

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#444]
![image](https://cloud.githubusercontent.com/assets/9288648/18232712/da67114a-72a3-11e6-8027-df009ef9cafc.png)

Shouldn't display "Email" at the beginning.

**Comment by arijitad** [comment]
i will try this one.

**Comment by rickr** [comment]
Hi @arijitad - FYI there is a PR open awaiting response from @jcserracampos

**Comment by yeli-buonya** [comment]
Can you review my PR?

**Comment by NZenitram** [comment]
I checked the PR's for yeli's fix and it seems it wasn't not accepted. I will be submitting a PR with the formatting fix for this today. 

<img width="736" alt="screen shot 2017-02-26 at 9 40 16 am" src="https://cloud.githubusercontent.com/assets/17070891/23341599/e127d1ac-fc07-11e6-9b26-2b6fd4c6cd64.png">

Please let me know what you think. 

Thanks, 

Nick

**Comment by rickr** [comment]
Hi Nick - thanks for the future PR! This looks good to me.

How hard would it be to get the 'One error prohibited' text to be bit smaller?
