### ISSUE TITLE
Donate button should go directly to Square

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#448]
Intent here is that the donate dropdown in the header is no longer a dropdown - it goes directly to Square and we don't clutter the experience - @jeremysb1, think this'd be better UX?

**Comment by rickr** [comment]
Do we have any plans/tickets to simplify donations? Could we just have one donation page (the one we host) and ditch the rest in the name of simplicity?

**Comment by davidmolina** [comment]
@rickr, that's the plan. Move those others to the FAQs under `Donate`.

**Comment by davidmolina** [comment]
Through Square, we receive the funds instantly whereas the others take a few days. Simplification here is key.

**Comment by rickr** [comment]
Ok - and what donate button is this talking about? The menu?

**Comment by hollomancer** [comment]
@rickr @davidmolina - Updated the comment to be a bit clearer on the intent.

**Comment by jeremysb1** [comment]
Can you walk me through what happens after they donate? Are they taken back to operation code's homepage? We want a complete journey. Meaning, they arrive at the homepage, they select anything from the menu - in this case "Donate" which takes them to Squarecash- and they can still get back to the homepage with one click. I agree that being taken to squarecash is better UI than having 4 options in a dropdown, but we need a complete journey.

**Comment by hollomancer** [comment]
@rickr @davidmolina - does what @jeremysb1 propose sound good?

**Comment by jeremysb1** [comment]
Let's just stick with the square page, accessible from the "Get Involved" Page, illustrated in the video below. The square page will open in a new window just like paypal does for resilient coders.

http://screencast.com/t/ASstv0lcC2tY

**Comment by hollomancer** [comment]
We'll use Donorbox for this.
