### ISSUE TITLE
Add Fullstack Academy to code schools list

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#452]

**Comment by rickr** [comment]
Website here: http://www.fullstackacademy.com/

Schools can be added in this file: https://github.com/OperationCode/operationcode/blob/master/config/code_schools.yml

**Comment by karla001** [comment]
@hollomancer  Should this issue be closed? Is there any way I can do that?

**Comment by hollomancer** [comment]
If you add the issue number to the pull request, it'll link them. Like so! #483
