### ISSUE TITLE
Partner with us button doesn't work.

### ISSUE THREAD

**Issue by AshTemp** [OperationCode/operationcode#453]
When viewing the Code School page as a user the Partner with us button does not work. It should open an additional window or other mail program to allow the user to e-mail staff@operationcode.org

**Comment by samullman** [comment]
can't find the button but this should work
`<a href="mailto:staff@operationcode.org"></a>`

**Comment by codedoll** [comment]
This seems to be working on my end. When I click "Partner With Us" it opens my mail client with the recipient filled as "staff@operationcode.org" @AshTemp were you using a specific device?

**Comment by AshTemp** [comment]
I was using my desktop with Chrome.

**Comment by codedoll** [comment]
@AshTemp is it possible you don't have a default email client set up?

**Comment by rickr** [comment]
Tried in Firefox, Chrome, and Safari and had no issues there. @AshTemp I think this is local to your machine. Closing this out.
