### ISSUE TITLE
Acquire additional user data post-signup

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#454]
We need to know x number of Operation Code veterans are x gender, x income bracket and x level of education. The goal is to capture this data early on and post-funding compare it to actual numbers and whether there is progress.

We need a fast-follow way of getting that information after someone logs in. My take? We time it three days after signup. At that point, they're more likely to be engaged and be interested in answering additional questions.

Maybe an automatic mailer, or a Slack inquiry.

**Comment by jeremysb1** [comment]
auto mailer would be my vote. it would allow us to explain why we need the info and how answering the questions helps the mission.

**Comment by hollomancer** [comment]
Captured in #569.
