### ISSUE TITLE
Tell us your story (Getting information for Upcoming Podcast)

### ISSUE THREAD

**Issue by kjaymiller** [OperationCode/operationcode#457]
I will be hosting the Operation Code Podcast. It will be an interview podcast talking to the many friends and members of Operation Code. This interview show will be primarily telling the story of its users and how they made (or are making) the transition from service member to developer.

I would like to have a page somewhere on the website that showcases the previous stories and podcast episodes. I would also like a place for people to tell their story and help us find people for the show.

**Comment by hollomancer** [comment]
Working on this. Thinking of having a subdomain pointing to podcast.operationcode.org

**Comment by kjaymiller** [comment]
That sounds good to me!

Jay Miller

kjaymiller@gmail.com

On Sat, Sep 10, 2016 at 8:27 AM Conrad Hollomon

<
mailto:Conrad Hollomon <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Working on this. Thinking of having a subdomain pointing to podcast.operationcode.org

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/OperationCode/operationcode/issues/457#issuecomment-246117802
, or

**Comment by davidmolina** [comment]
Awesome!

**Comment by rickr** [comment]
Huh...my email response didn't make it here so sorry if this gets posted twice.

This site is going to be static content right? Can we create a new repo and use github pages to serve the content?

**Comment by rickr** [comment]
Since we landed on putting this on its own subdomain I'm going to stop tracking it in this repo. 
Please let me know if you need an additional git repo created to support this effort.
