### ISSUE TITLE
blog.operationcode.org design and subdomain

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#463]
Wanted to get some opinions on having our blog point to blog.operationcode.org on Medium, and doing a bit of custom design here. Example.

https://backchannel.com/how-to-teach-computational-thinking-29e45c8a2664#.7o7d22l4e

**Comment by rickr** [comment]
Is this what we do now?

**Comment by hollomancer** [comment]
I think we just don't point the subdomain. The rest is goldplating.

**Comment by jeremysb1** [comment]
solid idea. it would allow people to get back to the homepage by having a home option on the navigation menu.

**Comment by hollomancer** [comment]
Change in scope. We host our own blog in Markdown and republish to Medium and other sites for SEO (see #576)
