### ISSUE TITLE
homepage design above the fold

### ISSUE THREAD

**Issue by jeremysb1** [OperationCode/operationcode#466]
The current homepage when users first arrive to the site needs work. We're not even using some of the current page because we have users skip the area with the pictures and white text. Also, the button is too big, as is the operation code logo. they need to be smaller.

I propose the following:  

(1) we cut all pictures and the white text that's layered on top. 
(2) make the space a clear white background;
(3) in the new space above the fold we only add our organization name, a headline that we already have "The fastest way for military, veterans and their families to get coding", and a sign up form to the left similar to the screenshot below and as detailed further in the jing video.

These are minor changes that will improve the design and increase acquisition.

<img width="1280" alt="screen shot 2016-09-05 at 6 58 57 am" src="https://cloud.githubusercontent.com/assets/21281011/18452525/67b5ee04-78f8-11e6-9cb1-0d5d0c789dea.png">

Jing Video:  http://screencast.com/t/C97e2ym4BdW

**Comment by rickr** [comment]
I'm on board. I think this an excellent candidate for an A/B testing.

Could you file separate tickets (1 each) for resizing the logo and nav button?

**Comment by hollomancer** [comment]
Capturing in #355.
