### ISSUE TITLE
Move scholarships from code schools to "Scholarships" page.

### ISSUE THREAD

**Issue by jeremysb1** [OperationCode/operationcode#467]
On our scholarship page, which needs to be renamed to simply "Scholarships", there are no actual scholarships. They are on the code schools page. That doesn't follow. If I'm searching for scholarships and there is a scholarship page, my first instinct is to go there.

~~Also, the drop down menu in "What We Do" needs to be reordered by popularity. People come to us for code schools, scholarships, and then everything else. Thus, code schools and then scholarships should be ordered in the drop down menu 1 and 2 then so on.~~ (See #489)

Please see the video for further visual clarification.

http://screencast.com/t/0ykBDdxuS

**Comment by rickr** [comment]
#489 created to reorder the menu.

**Comment by rickr** [comment]
Closing due to redesign
