### ISSUE TITLE
Move "success stories" to homepage

### ISSUE THREAD

**Issue by jeremysb1** [OperationCode/operationcode#468]
to start, we move all the content from the success stories page to the homepage right below the "What We Do" Section replacing the Why Operation Code and Latest News Section.

we need the homepage to cut to the chase as soon as possible to persuade people to either donate or join. the whole point of sharing success stories is to get them to either donate or join. thus, moving the success stories page to the homepage would accomplish that.

Please see the video below for further clarification.

http://screencast.com/t/TajOoubRj

**Comment by BratCat** [comment]
Can I take this?
