### ISSUE TITLE
Reduce Size of the Operation Code Icon 

### ISSUE THREAD

**Issue by jeremysb1** [OperationCode/operationcode#470]
The Operation Code Icon and Operation Code" text in the upper left on the homepage is too big. It needs to be reduced to be just slight bigger than the size as the navigation menu text.

**Comment by codedoll** [comment]
Is this a good enough size?
# **ORIGINAL:** 
<img width="502" alt="screen shot 2016-09-20 at 8 53 56 pm" src="https://cloud.githubusercontent.com/assets/17578236/18694009/6730dd68-7f74-11e6-890a-165003d60d6c.png">
<img width="1264" alt="screen shot 2016-09-20 at 8 54 05 pm" src="https://cloud.githubusercontent.com/assets/17578236/18694010/6732bec6-7f74-11e6-886c-e79da52488bc.png">


# **EDITED**
<img width="1175" alt="edited" src="https://cloud.githubusercontent.com/assets/17578236/18694014/6d30fb4e-7f74-11e6-8dc3-4a5bdef2ae8b.png">
<img width="499" alt="screen shot 2016-09-20 at 8 53 44 pm" src="https://cloud.githubusercontent.com/assets/17578236/18694015/6d3ef2e4-7f74-11e6-8ac2-b53bf8b17197.png">

**Comment by codedoll** [comment]
I changed the logo from: 
```
.navbar-fixed .nav-wrapper .brand-logo img {
    height: 64px;
}
```

to
 ```
.navbar-fixed .nav-wrapper .brand-logo img {
    height: 1.3rem; 
    margin-top: .3rem;

}
```

**Comment by jeremysb1** [comment]
looks good!
