### ISSUE TITLE
Signup should not reference veterans specifically

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#485]
I've gotten a number of comments over the past couple of months from potential members who are a bit unclear as to whether they can actually sign up, since they are not specifically veterans.

The URL for signing up specifically references veterans, so I'm wondering if there's a way we can make it clearer in our copy that everyone is welcome.

**Comment by rickr** [comment]
https://operationcode.org/sign_up works. I believe #246 would help solve this as well. With no objections I'll close this as a dup.
