### ISSUE TITLE
Create swag button that links directly to CottonBureau

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#486]
Add a new entry to the 'Donate' menu. 
It should be labeled "Swag" and point to https://cottonbureau.com/products/operation-code-medal

Original ticket:
> @davidmolina - Thinking this is a cheap and easy way to get a swag area without going through too much tech stuff.
> 
> Placement-wise, link off one of the menu buttons? @jeremysb1

**Comment by davidmolina** [comment]
This is perfect. Quick and fast. We'll leave to Jeremy on best placement

**Comment by rickr** [comment]
Lets put this under donate.

**Comment by abbylarner** [comment]
I'd like to try this one out!

**Comment by rickr** [comment]
Hi abbylarner - looks like this was already completed yesterday in #507

**Comment by abbylarner** [comment]
Ah! I missed that :) Thanks!
