### ISSUE TITLE
Reorder "What We Do" Menu section

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#489]
The drop down menu in "What We Do" needs to be reordered by popularity. 

Order should be 
* Code Schools
* Scholarships
* All other items

**Comment by codedoll** [comment]
@rickr just making sure I got this right. 

**You wanted to rearrange from this:**
<img width="1303" alt="screen shot 2016-09-20 at 10 11 38 am" src="https://cloud.githubusercontent.com/assets/17578236/18673681/b661c550-7f1a-11e6-8ee1-6f926a50c4ff.png">

**To this:**
<img width="1325" alt="screen shot 2016-09-20 at 10 11 25 am" src="https://cloud.githubusercontent.com/assets/17578236/18673698/c1f7e7e6-7f1a-11e6-88f8-b290515d4aa4.png">

**Comment by rickr** [comment]
That's correct!

**Comment by rickr** [comment]
Fixed in #493
