### ISSUE TITLE
Add mailing address to website

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#490]
farrah [3:36 PM]  
Also, i´m wondering if we want to put an office address that people can mail a check to? Old school, I know, and do we want people to know our address. But some organizations have a PO Box here people can mail.

Need to determine the best place for this @rickr @jeremysb1

**Comment by jeremysb1** [comment]
the ideal solution would be a contact us page like black girls code

**Comment by rickr** [comment]
What other items are on the contact page?  This seems like a good candidate to throw in the footer.

**Comment by jeremysb1** [comment]
Below is an example of a contact us page. It can have a form where people ask questions and see our mailing address.

http://www.blackgirlscode.com/contact-us.html

**Comment by jeremysb1** [comment]
Let's just throw this in the footer like Resilient Coders. 

http://screencast.com/t/3otYqaDduCU
