### ISSUE TITLE
Move Donations FAQ under Donations tab

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#491]
farrah [2:58 PM]  
I´m seeing that we have a FAQ about Donations, and i´m thinking it would be better to have it under the Donations tab. What do you say?

@davidmolina @jeremysb1 - thoughts?

**Comment by rickr** [comment]
I think if we need to have FAQ in close proximity to our donations page we're doing something wrong.

**Comment by davidmolina** [comment]
Exactly.

Most definitely we're doing something wrong when donations simply don't come in, when we struggle just to maintain financially.
