### ISSUE TITLE
Fix cd directory in the Getting Started guide

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#494]
In CONTRIBUTING.md in the [Operation Code section](https://github.com/OperationCode/operationcode/blob/master/CONTRIBUTING.md#operation-code) the directory a user `cd`s into is incorrect.

It should be changed from `cd operationcode` to `cd operationcode-upstream`

**Comment by karla001** [comment]
I fixed this but i am not sure how to create the pull request to merge it to this  repository from my fork.
