### ISSUE TITLE
Link homepage from blog

### ISSUE THREAD

**Issue by jeremysb1** [OperationCode/operationcode#496]
Site visitors are unable to return to the homepage from the blog. If they can't return to the homepage, they are unable to complete any call to action if they aren't already members or if they want to donate.

My .02 is to simply hyperlink the "Operation Code" text illustrated in the screen share picture below to the Operation Code homepage.

http://screencast.com/t/3AdDMz5snYh (screen share picture)

**Comment by jeremysb1** [comment]
another option is to simply have the blog open in a whole new window.

**Comment by benhastings** [comment]
Desiring of keeping users in the operationcode application, the fact that the blog currently resides on the medium platform makes the best UX choice to have that link open a new tab/window. Blank target lets the user's browser make that choice.

This is the change included in the pull request (#545) referenced above.
