### ISSUE TITLE
Add a blog

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#51]
Jekyll or Middleman. Thanks @techguydiy!

**Comment by superscott** [comment]
Since I personally don't enjoy working with either of those, I would say check out this video about [Pelican](http://blog.getpelican.com/).

https://youtu.be/cRtRxk5waE0?t=2h14m45s

**Comment by techguydiy** [comment]
They are pretty similar, the biggest difference is ruby vs python. I am
still new to this org, so please feel free to correct me if I am mistaken.
To this point it seems like most of the code has been ruby, so I feel like
a ruby platform would make sense to continue down. Plus it seems like there
is a much lower barrier for entry into Jekyll, no need for a virtual
environments...if you have ruby installed and a browser, you can pretty
much roll.

Add to the fact the github allows for free hosting of Jekyll sites, I feel
like this tools will be able to have a quick impact on someone new to
learning programming.

With all that being said, it seems like all of these repos are learning
opportunities for veterans...having more than one way of doing things
wouldn't hurt anything.

Let me know your thoughts.

Thanks,
Jason

**Comment by davidmolina** [comment]
Jekyll + GitHub page is gold. We want to encourage our vets chances at coding and contributing with different languages and platforms. Agree we could incorporate within the current rails app, but separate might be nice.

**Comment by davidmolina** [comment]
Jason, did we decide which platform?

**Comment by techguydiy** [comment]
Yes, I am moving forward with Jekyll.

Sent from my iPhone

On Jun 15, 2015, at 1:09 PM, David Molina <notifications@github.com> wrote:

Jason, did we decide which platform?

> On Jun 12, 2015, at 2:41 PM, Jason Sullivan <notifications@github.com>
wrote:
>
> They are pretty similar, the biggest difference is ruby vs python. I am
> still new to this org, so please feel free to correct me if I am mistaken.
> To this point it seems like most of the code has been ruby, so I feel like
> a ruby platform would make sense to continue down. Plus it seems like
there
> is a much lower barrier for entry into Jekyll, no need for a virtual
> environments...if you have ruby installed and a browser, you can pretty
> much roll.
>
> Add to the fact the github allows for free hosting of Jekyll sites, I feel
> like this tools will be able to have a quick impact on someone new to
> learning programming.
>
> With all that being said, it seems like all of these repos are learning
> opportunities for veterans...having more than one way of doing things
> wouldn't hurt anything.
>
> Let me know your thoughts.
>
> Thanks,
> Jason
> —
> Reply to this email directly or view it on GitHub.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/OperationCode/operationcode/issues/51#issuecomment-112157495>
.

**Comment by davidmolina** [comment]
Do you have privileges to start a new repo?

**Comment by techguydiy** [comment]
I do. Will start when I push initial commit.

Sent from my iPhone

On Jun 15, 2015, at 1:36 PM, David Molina <notifications@github.com> wrote:

Do you have privileges to start a new repo?

> On Jun 15, 2015, at 11:19 AM, Jason Sullivan <notifications@github.com>
wrote:
>
> Yes, I am moving forward with Jekyll.
>
> Sent from my iPhone
>
> On Jun 15, 2015, at 1:09 PM, David Molina <notifications@github.com>
wrote:
>
> Jason, did we decide which platform?
>
> > On Jun 12, 2015, at 2:41 PM, Jason Sullivan <notifications@github.com>
> wrote:
> >
> > They are pretty similar, the biggest difference is ruby vs python. I am
> > still new to this org, so please feel free to correct me if I am
mistaken.
> > To this point it seems like most of the code has been ruby, so I feel
like
> > a ruby platform would make sense to continue down. Plus it seems like
> there
> > is a much lower barrier for entry into Jekyll, no need for a virtual
> > environments...if you have ruby installed and a browser, you can pretty
> > much roll.
> >
> > Add to the fact the github allows for free hosting of Jekyll sites, I
feel
> > like this tools will be able to have a quick impact on someone new to
> > learning programming.
> >
> > With all that being said, it seems like all of these repos are learning
> > opportunities for veterans...having more than one way of doing things
> > wouldn't hurt anything.
> >
> > Let me know your thoughts.
> >
> > Thanks,
> > Jason
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/OperationCode/operationcode/issues/51#issuecomment-112157495
>
> .
> —
> Reply to this email directly or view it on GitHub.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/OperationCode/operationcode/issues/51#issuecomment-112163811>
.

**Comment by superscott** [comment]
ლ(́◉◞౪◟◉‵ლ)

**Comment by davidmolina** [comment]
@techguydiy @superscott ETA?

**Comment by davidmolina** [comment]
Should we have a blog and news section for press releases, or just blog? both?

**Comment by davidmolina** [comment]
Will be attacking this, this week. Now that we're donation capable and SSL-secured.

**Comment by ckib16** [comment]
I can help with this. I'll make a branch with Jekyll and get started. No experience with Jekyll but heard it was good and fairly easy to use.

http://jekyllrb.com/

**Comment by davidmolina** [comment]
thanks Chris.

**Comment by ckib16** [comment]
Just submitted PR for this. happy to discuss. I also wrote a big "101" type document for fellow Jekyll newbies to use. Let me know what you think. Happy to discuss.
