### ISSUE TITLE
Website Redesign

### ISSUE THREAD

**Issue by jeremysb1** [OperationCode/operationcode#511]
This epic will encompass the redesign of our website with an improved user experience and website performance so folks are able to "get involved" (Join, Donate, Mentor, Partner) and more concisely learn the benefits of getting involved from our homepage. Also, improved will be our code schools page, scholarship pages, and blog.

**Comment by rickr** [comment]
Going to track this in a project: https://github.com/OperationCode/operationcode/projects/2
