### ISSUE TITLE
Prevent code from showing

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/operationcode#512]
![opcodeerror](https://cloud.githubusercontent.com/assets/2008701/18939340/3be7d5a6-85c5-11e6-961a-4690d66311c0.jpg)

On Windows 7/Internet Explorer 11, the navigation bar displays as "arrow_drop_down" across the top.

**Comment by ErnestoD** [comment]
I was looking into it but with Windows 10/IE 11, the text is gone but the actual arrows are below text. 
![untitled](https://cloud.githubusercontent.com/assets/21998106/19528483/309324f4-95fa-11e6-8d36-aecba60b346b.png)
