### ISSUE TITLE
Create Learning Resources page

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/operationcode#513]
Operation Code could use a page where people can go to find free websites and other resources to learn coding basics, cyber security, and other relevant topics. It should be broken down by topic. Would also be cool if there is a way for people to contribute new resources as they come across them.

**Comment by jeremysb1** [comment]
yeah this is a good one. we'll address with developing the new onboarding program. if you have any design recommendations or mockups, they are welcome.

**Comment by hollomancer** [comment]
@aaron-suarez - We've created a repo where people can add these resources under https://github.com/OperationCode/mentorship - when the new onboarding/design becomes available, we'll port the content over to the site!

**Comment by hollomancer** [comment]
See https://github.com/OperationCode/mentorship for this stuff.
