### ISSUE TITLE
Fix typo in FAQ

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/operationcode#514]
Under question "Why doesn't Operation Code offer services to non-military/veterans?" it says "..we believes it is our moral obligation.."

This should be changed to "...we **believe** it is our moral obligation..." (bold added for emphasis).

**Comment by aaron-suarez** [comment]
Also, under this question it says "the numbers speak for themselves" but I don't see any numbers. Not sure if this is a fully separate issue or something to do with my setup...

**Comment by kopijunkie** [comment]
@aaron-suarez technically a separate issue as it isn't a typo, but I believe 3 of the 4 lines of text that follows just under "These numbers speak for themselves:" is meant to be a bulleted list. I'm assuming you're looking to fix this issue too so to point you in the right direction, have a look at how the HTML is being used in the YAML file.

**Comment by rickr** [comment]
Fixed in #515
