### ISSUE TITLE
From "Join" to "Get Involved"

### ISSUE THREAD

**Issue by jeremysb1** [OperationCode/operationcode#521]
We change "Join" to "Get Involved" on the homepage just like [Resilient Coders](http://www.resilientcoders.org/). From there, they are able to access the "Get Involved" page and contribute to Operation Code as a partner, new joiner, mentor, or donate. Please see the video below for illustration.

http://screencast.com/t/Wh3Pf7ysy

**Comment by codedoll** [comment]
<img width="1204" alt="screen shot 2016-10-02 at 7 12 56 pm" src="https://cloud.githubusercontent.com/assets/17578236/19024589/65e865c0-88d4-11e6-9729-5e87d157016d.png">
@jeremysb1 does this look good?

**Comment by jeremysb1** [comment]
yes. we also need another CTA for people to "Get Involved" directly on the page. Meaning, we remove the "Teach Me to Code" button altogether and change it to a "Get Involved" Button taking users to the 'Get Involved" Page just like in the screenshare below and the video in my first comment above.

http://screencast.com/t/GMIbsvWr4PTB

**Comment by codedoll** [comment]
👍 just saw this version of the issue. opened link too fast. i see your examples now.
