### ISSUE TITLE
Fix bullet points in FAQ

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/operationcode#522]
In the FAQ question "Why doesn't Operation Code offer services to non-military/veterans?" There is supposed to be a bulleted list but there are no bullet points. Firefox version 49.0/Ubuntu 16.04.1.

![faq bullets issue](https://cloud.githubusercontent.com/assets/2008701/19044717/1ba3bc12-895b-11e6-9a33-2c17c27c28c2.png)

**Comment by rickr** [comment]
@jeremysb1 - are we retaining the FAQ in your redesign?

**Comment by aaron-suarez** [comment]
I used some inline CSS to make it display like this:

![first-attempt-bullets](https://cloud.githubusercontent.com/assets/2008701/19083172/c10f0258-8a26-11e6-86c3-d6fdfa3dfa16.png)

Based on the fact that inline CSS worked, I don't think it's a problem with the HTML. I think perhaps we need to add a CSS class for this `<ul>` and that will override whatever CSS rule is causing the bullets to disappear. Any thoughts on how it looks or how it should be designed (inline CSS or CSS class)?
