### ISSUE TITLE
Slack link broken on FAQ > "What are the hours of operation for Operation Code?"

### ISSUE THREAD

**Issue by codedoll** [OperationCode/operationcode#523]
![screen shot 2016-10-03 at 12 25 02 pm](https://cloud.githubusercontent.com/assets/17578236/19044951/73d618ea-8964-11e6-980b-e97007699bf7.png)

External link to Slack is broken.

**Comment by codedoll** [comment]
@hollomancer what didn't this close automatically with the merge?

**Comment by hollomancer** [comment]
No idea. Closing

**Comment by rickr** [comment]
I think `This closes issue #523` needs to be `This closes #523`.

**Comment by codedoll** [comment]
Oh, thanks @rickr
