### ISSUE TITLE
Logo In Mobile Layout Is Offcenter

### ISSUE THREAD

**Issue by jdspringr07** [OperationCode/operationcode#527]
As a mobile user when I visit the page the logo is offcenter and not fully displayed

> Will update with a better description in the morning.
> 
> Also, will add pictures. My mobile github app is kind of garbage right now.

**Comment by jdspringr07** [comment]
![screenshot_2016-10-04-00-36-35](https://cloud.githubusercontent.com/assets/9255710/19093816/d403fcf4-8a5a-11e6-8d54-a3c6a6668459.jpg)
![screenshot_2016-10-04-00-36-59](https://cloud.githubusercontent.com/assets/9255710/19093815/d402582c-8a5a-11e6-8125-e4315193133d.jpg)
![screenshot_2016-10-04-00-37-40](https://cloud.githubusercontent.com/assets/9255710/19093817/d4042620-8a5a-11e6-9d2f-264e847334b1.jpg)

As promised, here are screenshots of the issues. I'm running Android, Version 6.0.1 on Samsung Galaxy Note 5.

On my device, it almost looks like the banner has static settings instead of scaling with mobile screen resolution. Additionally, the hamburger will expand, but I'm unable to collapse it without going back to the previous page or select an option.

**Comment by rickr** [comment]
First issue is fixed in #526. 

Did you try clicking outside of menu to collapse?

**Comment by codedoll** [comment]
@rickr it is not fixed still.

**Comment by codedoll** [comment]
<img width="395" alt="screen shot 2016-10-05 at 4 38 24 pm" src="https://cloud.githubusercontent.com/assets/17578236/19130672/3404bcbe-8b1a-11e6-9e26-24b8d20412dc.png">
<img width="892" alt="screen shot 2016-10-05 at 4 38 42 pm" src="https://cloud.githubusercontent.com/assets/17578236/19130674/35405372-8b1a-11e6-9822-9799a0b6e528.png">

**Comment by rickr** [comment]
There were 3 issues in this ticket. The first one was resolved (text to big in the header) in #526 and I don't think the 3rd issue is actually an issue so I renamed the ticket to deal only with the offcenter logo. Perhaps I should have closed this one and opened 3 more to avoid confusion.

**Comment by codedoll** [comment]
good call I agree.

**Comment by bisho1995** [comment]
![ice_screenshot_20161016-091359](https://cloud.githubusercontent.com/assets/12195877/19415063/020e1146-9381-11e6-96c7-7a6e2ac939e5.jpeg)

**Comment by bisho1995** [comment]
Guys I made some changes in the css and after those changes its looking like this .. but I am not used to the ways and means of github so I cannot post the solution. I will try to post it, but this is the expected result right ?

**Comment by bisho1995** [comment]
![ice_screenshot_20161016-092011](https://cloud.githubusercontent.com/assets/12195877/19415086/cdf3f226-9381-11e6-9e5c-418301dbeb36.jpeg)


Just do these two changes and you would be good
