### ISSUE TITLE
Easier to navigate code schools

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#53]
First hack at it and I put them in alpha-order, ex. California, etc. and added links and their respective addresses. Few issues: hard to navigate. Thinking a map and broken down by cities. Maybe geolocation based? Secondly, code school addresses change often. Few I notice, including Portland Code School and PDX Code Guild have different addresses. In general, little maintenance other than adding code schools (link to their site) based on cities where they are operational.

**Comment by davidmolina** [comment]
Additionally, a feature that tracks what coding schools have submitted their application for Veterans use of the GI Bill? [Reference](https://twitter.com/caseyagil/status/613944170307162112)

**Comment by nellshamrell** [comment]
Do you have a current list of those code schools and their current locations that you can send me?  I have a hack day scheduled tomorrow and would like to take a crack at this.

**Comment by davidmolina** [comment]
Awesome Nell! 

Yeah, our current one is here: 

https://github.com/OperationCode/operationcode/blob/master/app/views/pages/codeschools.html.erb

Daelen Cornelius made this: 

https://github.com/OperationCode/operationcode/pull/58

Need code schools, location, licensed and VA accredited.

**Comment by davidmolina** [comment]
Add to homepage/landing w/ a map and pins.

**Comment by KevinRoss-** [comment]
Making it easier to navigate will be great. This is a good issue and I'll take a look at it.

**Comment by rickr** [comment]
This was fixed in #269
