### ISSUE TITLE
All-in-one source for veteran benefits. (Not GI Bill or Health Care but non-government related)

### ISSUE THREAD

**Issue by ErnestoD** [OperationCode/operationcode#534]
As a visitor,
I would like an all-in-one benefits to links.
It could include education/non-educational (non-GI related such as lydia.com with linkedin.com [free year membership] and https://niccs.us-cert.gov/training/federal-virtual-training-environment-fedvte for example.)

**Comment by Scrub10000** [comment]
I think this would be a fantastic addition. Maybe another drop down menu for "Veteran's non Government Benefits" or a link to it from the 'What We Do' drop down menu.

**Comment by hollomancer** [comment]
@aaron-suarez, maybe we can have this as a sub-page?

**Comment by aaron-suarez** [comment]
Yeah @hollomancer, that's a great idea. You think that the Learning Resources page would be the kind of information they're suggesting?

**Comment by hollomancer** [comment]
Yeah, we can just have it as a markdown directory in the same page for now.

**Comment by juanchaves** [comment]
@aaron-suarez I have a long list of links too (free resources), I can send you a file. Also, there are a lot of NGO's that offer help for veterans like the following list that help vets: 

[The Soldier Project](https://www.thesoldiersproject.org/)

[National Alliance on Mental Illness](http://www.nami-greaterseattle.org/)

[Vets Go](http://www.vets-go.com/resources)

[Heroes to Hometowns Washington State](http://www.waheroestohometowns.org/Links.html)

[The Seattle Stand Down](http://www.theseattlestanddown.org/)

[Outreach And Resource Services for Women Veterans](http://oars4vets.org/)

**Comment by aaron-suarez** [comment]
Ok you want me to do a PR to add "Veteran's non-Government benefits" to the dropdown and then embed Veterans.md from the Learning Resources repo into the page?

**Comment by aaron-suarez** [comment]
Yeah send me your file over the operation code slack. @ aaron-s is my username on there
