### ISSUE TITLE
Minimize the Logo Size (no rhyme intended)

### ISSUE THREAD

**Issue by Wimsy113** [OperationCode/operationcode#536]
Please use one of the following templates to create new issues:

For a new feature:
As a visitor, when on the mobile site, the logo should be more compact

(https://cloud.githubusercontent.com/assets/7386887/19486630/2ae7037c-952d-11e6-887b-4e21d0a50268.png)

**Comment by benhastings** [comment]
My day job is front-end performance optimization, so I absolutely appreciate that you care about optimizing a logo for speed.

After typing that and looking again... are you talking about changing the dimensions or payload size?  I've completed the latter and will be pushing that momentarily.  If that's not what you intended, I can take a stab and reducing the dimensions, too.

**Comment by benhastings** [comment]
is this a duplicate/related to #470 & #510 or is it actually looking at the payload size?  

If it is, I've scoured the site but can't seem to locate the image to replace with the payload optimized version.  I'll be happy to share it if needed/desired.

**Comment by Wimsy113** [comment]
Nope it's not related to #470 . It is related to #510. It was decided that in mobile, displaying the words "Operation Code" is not necessary, we can just use the medal in mobile. That's pretty much it.

**Comment by Wimsy113** [comment]
This is part of a redesign of the site in mobile. It's a revamp so that everything flows better and looks better and so we don't run into issues with the other elements in the header while in mobile.

**Comment by hollomancer** [comment]
This is captured in #537.
