### ISSUE TITLE
Minimize the Logo Size (no rhyme intended)

### ISSUE THREAD

**Issue by Wimsy113** [OperationCode/operationcode#537]
As a visitor, when on the mobile site, the logo should be more compact

![screen shot 2016-10-18 at 12 19 35 pm](https://cloud.githubusercontent.com/assets/7386887/19486685/59e10ef2-952d-11e6-823a-f5b285af1cdf.png)

**Comment by CdiegoBB** [comment]
What cellphone you use, tell me the model. I am new here and i want to help
