### ISSUE TITLE
Mobile Interface Improvements 

### ISSUE THREAD

**Issue by Wimsy113** [OperationCode/operationcode#538]
As a visitor, on the mobile site, the hamburger menu should open to a neater, more user friendly overlay instead of a side bar menu to cut down on the amount of scrolling one has to do on mobile.

![screen shot 2016-10-18 at 12 21 45 pm](https://cloud.githubusercontent.com/assets/7386887/19486813/da2edcba-952d-11e6-9d10-ed74bfd65ebb.png)

**Comment by Dark-reaper** [comment]
@Wimsy113 

Would it be possible for me to take ownership of this issue ? 

I also noticed that the menu breaks when on mobile 
![image](https://cloud.githubusercontent.com/assets/2376414/19593658/f54d2dd4-9781-11e6-89e6-7971f7638f68.png)

I propose something more similar to the mockup where to menu toggle is on right and the logo on the or centered, but the current logo will look bad if it's centered, you'll need to create something smaller.

**Comment by Wimsy113** [comment]
I was going to Livecode this on Saturday but something came up and now I can't do it, if you want you can take a whack at it @Dark-reaper but you'll need to complete issue #536 so you can incorporate the changes for the header first. I've got medal asset if you need it, just DM me in the slack and I'll get it to you
