### ISSUE TITLE
Shorten meta description to under 160 chars for SEO

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#540]
Too long. 187 chars: 'Veteran-founded and led, Operation Code is a national 501(c)(3) non-profit organization on a mission to support military, veterans and military families coding and learn web technologies.'

**Comment by braxtonfair** [comment]
I got this, give me a few mins for a pull.

**Comment by braxtonfair** [comment]
Could you mind telling me where this is? I can't seem to find where.

**Comment by benhastings** [comment]
sorry, @braxtonfair, I didn't refresh to see your desire to take this one.

**Comment by braxtonfair** [comment]
@benhastings It's no problem.

**Comment by hollomancer** [comment]
Resolved by #543
