### ISSUE TITLE
Add GI bill approved schools to home page

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#548]
As a visitor,
When I visit the home page,
I should see what code schools are validated for the GI bill.

Sabio, Code Fellows, Turing

**Comment by jonodonovan** [comment]
So taking the same information from https://operationcode.org/code_schools and adding it the home page?

**Comment by DickinsonMark** [comment]
you can use GI bill at Galvanize as well!

**Comment by hollomancer** [comment]
Consolidating into #355.
