### ISSUE TITLE
Embedded fundraising section

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#55]
Currently, we're directing potential donors to our fiscal sponsor and we're losing donors this way. Our donations have been poor, at best (couple hundred since joining in Jan 2015). Too much friction and lost of the Operation Code brand. Need to integrate Dwolla or another easy-to-use and mobile-friendly system that expedites one-time, recurring, etc donations through Operation Code. Ideas?

**Comment by davidmolina** [comment]
We'll be using Dwolla this week to integrate. /cc @Scripore

**Comment by gxespino** [comment]
I can do this pretty easily if you set up a a stripe account instead of DWOLLA.

**Comment by davidmolina** [comment]
I don't think there's a price difference between the two is there? What
about PayPal? One-time and recurring?

**Comment by gxespino** [comment]
Very minimal price difference if there is any. Stripe's API is much easier to use that Braintree (paypal) and Braintree has a 4-6 day period before they approve new accounts from my experience. Stripe can do recurring and one time payments. 

Stripe == best and easiest to integrate

**Comment by davidmolina** [comment]
We have a Dwolla account. Will setup an Stripe account and get you the API
info.

**Comment by davidmolina** [comment]
@gxespino Added you as a user. Also, might be a different thread, but need to integrate additional ways for donors to give, SMS, Amazon, etc.

**Comment by davidmolina** [comment]
@gxespino From Stripe: A new USD bank account ending in XXXX was successfully added
to your Stripe account. Can we knock this out today or should we team up? /cc @nanoxd

**Comment by gxespino** [comment]
functionality is complete. working on styling and client side validations today. should be finished late this evening, EST.

**Comment by davidmolina** [comment]
Outstanding!

**Comment by davidmolina** [comment]
@gxespino trying to get it to work locally.

**Comment by ckib16** [comment]
@gxespino same as @davidmolina, running into Postgres error. I'll switch to SQLite in development env and see if I can get running.

**Comment by ckib16** [comment]
Hmm. Keep geting error `FATAL:  role "davidmolina" does not exist`. StackOverflow answers so far have not helped. Anything I'm missing getting set up locally? I'm not used to running PG locally, but I have it installed correctly and running.

**Comment by davidmolina** [comment]
Let's hack on this later today if you have time.

**Comment by ckib16** [comment]
I fixed it late last night. Up and running locally!

Chris

**Comment by davidmolina** [comment]
Nice Chris! 

Can you deploy to Heroku?

**Comment by ckib16** [comment]
Yeah, I have before for all my Bloc stuff. But usually that wold of couse be at the end of the fix. Fix > PR to Master . Then push to Heroku.

Just got an hour now, let me start digging into code and see if I can tell what's up.

**Comment by ckib16** [comment]
Sorry - just to clarify my last post. The problem with Stripe is still there. I wasn't clear.

What I meant was, I fixed my problems with PG locally, and now have the basic app running on my Mac so I can start hacking on the issue.

**Comment by davidmolina** [comment]
Right. That's what I figured.

On the Stripe error, that's what we're all seeing.

**Comment by ckib16** [comment]
Key problem is *mostly* fixed. Need to verify a charge for $69 went through on test site on Stripe Dashboard on 2015-07-07. @davidmolina can you please verify?

**Comment by ckib16** [comment]
Other small items (after confirming payments are successful going thru)
- [ ] fix logic in donations_controller - showing the text of the "thank you" email message instead of the :flash success message to the user
- [ ] welcome email formatting issues - user name not included in "Dear    ," welcome line. Other small errors.
- [ ] Check email is sent out

**Comment by davidmolina** [comment]
This commit 554c5940199c1b743711954fff485e91b0afa454 addresses this.
