### ISSUE TITLE
Add VetBot for programming

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#553]
As a new member, when I join VetBot should ask what programming languages am I interested in. It should auto-respond with books, links to get started. For example:

VetBot: Hi, I'm VetBot of Operation Code here to assist and guide you towards some resources to get coding. What programming languages are you interested in learning so that I can tailor some solutions for you? 
Me: Hi! I'm interested in Ruby, Ruby on Rails. 
VetBot: Outstanding. If you're just starting out, recommend Michael Hartl's Ruby on Rails Tutorial (https://www.railstutorial.org/book), Chris Pine's Learn to Program (https://pine.fm/LearnToProgram/chap_00.html), and Learn Ruby The Hard Way (https://learnrubythehardway.org/book/). If you get stuck, ask a question in the #general or #web-dev channel so we can assist. 
Me: Excellent. Thank you!

**Comment by binarymason** [comment]
Hi @davidmolina 

Rough draft on laying the framework for this is here: https://github.com/binarymason/vetbot.  Thought I'd go ahead and put this in front of you guys.  Feedback welcome.  At any time, please feel free to copy, fork or cherry pick.

Deployment instructions are here: https://github.com/binarymason/vetbot/blob/master/README.md.  

![vetbot](https://cloud.githubusercontent.com/assets/12122953/21557249/9824a810-cdf7-11e6-83b3-ad0da8d64d37.gif)

**Comment by hollomancer** [comment]
Let's figure out how to combine this with what @rickr has done on https://github.com/OperationCode/operationcode_bot

**Comment by rickr** [comment]
Going to close this out. Any further discussion we can have over in https://github.com/OperationCode/operationcode_bot
