### ISSUE TITLE
Signup Flow: Add Slack desktop app link to post-signup flow

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#568]
In order to reinforce Slack as a part of our community and onboarding experience, we should include a link to Slack on the post-signup page, after a user signs up.

**Comment by technicalpickles** [comment]
> post-signup page

Do you mean the home page? It seems like signing up from the home page redirects you back to the home page with a notice.

Also, there's a welcome email that says like:

> Once in Slack (you'll probably want to download the app),

It might make sense to add a link there too.
