### ISSUE TITLE
Embed civilian signup on homepage

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#57]
Currently, non-military veterans visit the same page as military veterans to sign up and get on our newsletter. It takes too long and potentially we lose hundreds of possible signups weekly. /cc @Scripore

**Comment by emckenna** [comment]
There seems to be two forms already, the one on the "sign up" (/action) page and the mail chimp form from the link on the "sign up" page.  What are you looking for here?  Perhaps the Signup should have two menu options?  "Civilian" and "Veteran" ?

**Comment by davidmolina** [comment]
Right. Should be two: military/veterans and civilians. 

Military/veterans go into Slack automatically. Civilians, we have to manually input them into Mailchimp, but ideally should auto this process.

**Comment by emckenna** [comment]
I started thinking about Vets/Civilians/Donors, etc and got into the weeds really quick.  I think it might be best to consolidate to one form and a new "SignupController" that handles how the user gets signed up.  For military/vets we can just do what were doing now, just more the code around.  And for Civilians, can look at using mailchimp api call to subscribe them to the list.

**Comment by davidmolina** [comment]
Sounds good.

**Comment by rickr** [comment]
Consolidating into #56 .
