### ISSUE TITLE
Signup Flow: Remove zipcode from signup flow

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#570]
In order to make the signup process as seamless as possible, let's take the zipcode out. We'll design a post-signup greeting to acquire additional information!

**Before this is worked on the above mentioned post signup greeting must be completed.**

**Comment by binarymason** [comment]
Is this blocked until #569 gets designs and details sorted out?  Or in the meantime, is editing a user's profile to add zip codes acceptable?

Happy to help out.

**Comment by rickr** [comment]
Hi @binarymason. I think we can hold most of this work until our redesign is completed. We targeting right around after the new year.
