### ISSUE TITLE
Donate flow uses Donorbox modal

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#571]
This interacts with stripe and allows users to donate from our website.

**Comment by hollomancer** [comment]
What do we get with Stripe in terms of being able to save credit card information, donate with Paypal, Amazon Payments, etc?

Was looking at this donation system using Stripe; https://donorbox.org/

**Comment by rickr** [comment]
I'm using these tickets to track what we need to bring over but this is something I wanted to bring up. Right now we have about 5 options - do we want to keep all of them? Do want to find something like donorbox?

**Comment by hollomancer** [comment]
I think we should commit to a single option. Amazon Smile and purchasing stickers, etc. should not be under Donate.

Will take a quick look at how donorbox integrates...

**Comment by hollomancer** [comment]
`<script src="https://donorbox.org/install-popup-button.js" type="text/javascript" defer></script>
<a class="dbox-donation-button" href="https://donorbox.org/operationcode" style="background:#2d81c5 url(https://d1iczxrky3cnb2.cloudfront.net/red_logo.png) no-repeat 37px center; color: #fff;text-decoration: none;font-family: Verdana,sans-serif;display: inline-block;font-size: 16px;padding: 15px 38px 15px 75px; -webkit-border-radius: 2px; -moz-border-radius: 2px; border-radius: 2px; box-shadow: 0 1px 0 0 #1f5a89; text-shadow: 0 1px rgba(0, 0, 0, 0.3);" >Donate</a>`

**Comment by ver2point0** [comment]
@rickr @hollomancer I'd like to take this issue. What exactly do I need to do?

**Comment by rickr** [comment]
I think that should do the trick. You'll be replacing the existing donate dropdown with this.

**Comment by ver2point0** [comment]
@rickr That's good to know. I'm still having difficulty getting Op code to run on C9. I've posted another screenshot in the slack channel.

**Comment by ver2point0** [comment]
@rickr @hollomancer I've got OpCode running on C9 now. Can I have this issued assigned to me now?

**Comment by rickr** [comment]
She's all yours!

**Comment by ver2point0** [comment]
Thanks @rickr!

**Comment by ver2point0** [comment]
![inspectandadd](https://cloud.githubusercontent.com/assets/12492121/21875164/f5575028-d847-11e6-8a2c-1652cb21a5f4.JPG)

@rickr @hollomancer I tested out the donorbox changes in Chrome's dev tools first before making any changes in the actual code base. How does it look? I still have to change the mobile nav part too.

**Comment by rickr** [comment]
Merged in #600
