### ISSUE TITLE
Markdown Blog at blog.operationcode.org

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#576]
We host our own blog in Markdown and republish to Medium and other sites for SEO.

Functional requirements:
- New blog entries can be created in Markdown.
- New blog entries create a new index entry.
- blog.operationcode.org redirects to the blog index, which may have its own design (not in the scope of this story)

This issue replaces #463.

**Comment by binarymason** [comment]
Why not use Github Pages for this?  That would meet all of the functional requirements. 

Move the jekyll code in`/blog` to its own repo and make a project page https://help.github.com/articles/user-organization-and-project-pages/#project-pages and add a CNAME in your DNS settings that points `blog.operationcode.org` to `operationcode.github.io/blog`

Moving `/blog` to its own repo would also avoid issue of cluttering the git history here with a bunch of blog posts.

**Comment by rickr** [comment]
One requirement to move this back to our site vs the current place it's hosted (medium) was for SEO. I think moving it to a subdomain would undermine that effort.

**Comment by rickr** [comment]
Ah - looking at the ticket I see it mentions blog.operationcode.org specifically. @hollomancer do you mind if I update it so it's hosted at /blog? Unless we actually do want to move it to blog.operationcode.org.

**Comment by hollomancer** [comment]
Yeah, that's not a requirement - /blog is fine.

**Comment by jjhampton** [comment]
The route @binarymason suggested sounds like it should work- we already have an old `blog` repo (https://github.com/OperationCode/blog) that could be revived to serve as a GitHub Project Page (as long as DNS redirects are also available). 

Here's some other useful info on custom domains / redirects/ Project Pages https://help.github.com/articles/custom-domain-redirects-for-github-pages-sites/

**Comment by binarymason** [comment]
Note that the `blog` repo that @jjhampton is mentioning is already up, live and running as a Project Page at https://operationcode.github.io/blog/. 

If you're fine with that theme, etc. all you have to do is create the CNAME record in your DNS settings that points `blog.operationcode.org` to `operationcode.github.io/blog`.

**Comment by jjhampton** [comment]
Closing issue after discussion w/ @hollomancer.  Moving forward with a plan for a GitHub pages-hosted static blog, which will be tracked in multiple new issues.
