### ISSUE TITLE
Design: Partners Landing

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#578]
Please use one of the following templates to create new issues:

For a new feature:
As a [VISITOR, ADMIN, ETC],
When I [CONTEXT/LOCATION FOR FEATURE],
It should [DESCRIBE FEATURE]

For a bug:
As a [VISITOR, ADMIN, ETC],
When I [CONTEXT OF BUG]
It [DESCRIBE BUG]
It should [EXPECTED OUTCOME]

See #361 for additional information.

**Comment by Aniket965** [comment]
as visitor 
in partners landing page 
do we have to  make animation for when landing on partners page?
