### ISSUE TITLE
Design: Scholarships

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#579]
Please use one of the following templates to create new issues:

For a new feature:
As a [VISITOR, ADMIN, ETC],
When I [CONTEXT/LOCATION FOR FEATURE],
It should [DESCRIBE FEATURE]

Some UX notes are captured by @jeremysb1 in #467.

**Comment by tpham045** [comment]
Hi! I would like to take this design task. 

From the #467 Jeremy's screencast, there is only one thing left in his request:

As Visitor/Student,
When I click on Scholarship page
The scholarships of coding schools should display right after the video.

**Comment by hollomancer** [comment]
All yours!

**Comment by tpham045** [comment]
Hello!
I did some user test on the original design to find some pain points.

Here is the first draft: [http://operation-code-scholarship.webflow.io/](http://operation-code-scholarship.webflow.io/)

What do you think? @hollomancer

**Comment by hollomancer** [comment]
@tpham045, will take a look!

**Comment by hollomancer** [comment]
This looks great! @rickr, what do you think?

**Comment by tpham045** [comment]
Just talk to @rickr today. It seems that we plan to build/convert a new front end (repo operationcode_frontend) using React.

I think it is better to organize these Design tasks over there. 
@hollomancer What do you think?

**Comment by hollomancer** [comment]
Agreed - we can recreate there.
