### ISSUE TITLE
Design: About Us Page

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#580]
_As a visitor, I want to be able to visit an About Us page on the site, so that I can learn more about who and what's behind Operation Code. This will help me build confidence in Operation Code as an organization._

Product requirements;
* Purpose, vision, mission statements.
* Link to the history timeline of our organization.
* Portraits of board and staff.
* Short bio of board and staff (no more than 3 sentences)

Technical requirements;
*

**Comment by Aniket965** [comment]
can i design or can give suggestions on this?(i am new to github)?

**Comment by rickr** [comment]
Hi @Aniket965 We have a few people currently working on designs for these pages.

If you're interested in helping out feel free to sign up at http://operationcode.org/join. This will give you access to our slack team where you can join the #design channel. They should be able to get you pointed in the right direction.
