### ISSUE TITLE
Favicon.ico not compatible with all devices

### ISSUE THREAD

**Issue by Kornil** [OperationCode/operationcode#588]
As a visitor on my IOS(Safari) or Android(Chrome) device the website icon is absent for both retina and non retina devices.
The metro tile icon for WIN8/WIN10 and the mask-icon for OS X Safari is also absent/not configured.
The favicon.ico file does not have the recommended sizes required by desktop browsers(16x16, 24x24, 32x32, 48x48, 64x64)

I'd like to fix this issue for your website: to do this I require an image file of your logo with resolution bigger than 320x320 px.

Francesco Agnoletto

**Comment by rickr** [comment]
![operationcode_transparent_icon](https://cloud.githubusercontent.com/assets/334550/21205103/6cd830f8-c228-11e6-9087-221ca470f503.png)

This should be 400x400.
