### ISSUE TITLE
Investigate setting up Travis CI

### ISSUE THREAD

**Issue by emckenna** [OperationCode/operationcode#59]

**Comment by emckenna** [comment]
http://foundation.travis-ci.org/

**Comment by davidmolina** [comment]
@emckenna I've fired an email.

**Comment by emckenna** [comment]
Great!  sorry i've been less available last week or so.. sick kid, house office renovation taking up all the free time ;)

**Comment by davidmolina** [comment]
No probl. Hurry up and wait now.

On Tue, Jul 21, 2015 at 6:54 AM, Eric Mckenna <notifications@github.com>
wrote:

> Great! sorry i've been less available last week or so.. sick kid, house
> office renovation taking up all the free time ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/59#issuecomment-123314649>
> .
>



-- 
David
t. @davidcmolina <https://twitter.com/davidcmolina>
http://davidmolina.github.io/

**Comment by rickr** [comment]
#184 has us deploying each merge to master into production.

@davidmolina are there any more steps for this ticket or can it be closed?

**Comment by davidmolina** [comment]
Could be closed.
