### ISSUE TITLE
Video on scholarships page is not responsive

### ISSUE THREAD

**Issue by wcriss44** [OperationCode/operationcode#596]
As a visitor,
When I visit the scholarships page, located at https://operationcode.org/scholarships , the video
is not responsive. The video should change in size depending on the size of my browser.

Additional Information (eg browser version, screenshots etc):

I am using Google Chrome to view the website. I opened DevTools to try and get it working properly
so that I can add some suggested styling or class names. However, I noticed that the class names do not seem to be consistent between pages.

**Comment by kboygit** [comment]
I am so sorry for the inconvenience , and thank you for bringing this up to us :+1:
