### ISSUE TITLE
Possible bug on about page

### ISSUE THREAD

**Issue by wcriss44** [OperationCode/operationcode#597]
As a visitor,

When I visit the about page, located at https://operationcode.org/about

It seems to have a website embedded for the video. I do mean a website, as in the entire HTML source code of a website. I am not sure if this is intended or not. Worth noting, the video player does work fine. If this is unintended it might improve performance to clean this up.

Additional Information (eg browser version, screenshots etc):

The bug seems to be related to the containing \<iframe> and not the parent \<div>. I copied the source and glanced through it in sublime but didn't notice anything out of the ordinary. This leads me to believe that the issue might be related to something replacing the contents in the \<iframe>, such as a script. I've also included a screenshot of DevTools showing the issue. The two \<!DOCTYPE html> declarations should be fairly easy to spot with out zooming in any.

<img width="1233" alt="screenshot 2017-01-10 01 22 30" src="https://cloud.githubusercontent.com/assets/24770046/21796140/a0c5d9ae-d6d4-11e6-8e64-7c4f8c41c9ef.png">

**Comment by wcriss44** [comment]
Additional information:

I cloned the repository and tested it on my computer. This still happens on my local computer but with a bit of variation. Sometimes it shows a new HTML page relating to Viemo, like the picture above. However, sometimes it shows a page that has to do with https://js.stripe.com/v2/ . I don't know enough about Ruby on Rails yet to really track this down. I hope that this information helps!

**Comment by kboygit** [comment]
thank you again for bringing this up to us :+1:

**Comment by rickr** [comment]
#605 fixed this. Thanks for the heads up!
