### ISSUE TITLE
Make a downloadable package for branding

### ISSUE THREAD

**Issue by kjaymiller** [OperationCode/operationcode#601]
Please use one of the following templates to create new issues:

As a VISITOR. when I go to operationcode.org/press-kit all of the press media should be available as a downloadable file. 

There should also be branding guidelines and individual downloads of content.

Additional Information (eg browser version, screenshots etc):
This would be a downloadable .zip file

To complete this ticket please:
- [ ] Make the package available on operationcode.org
- [ ] Make sure the contents reflect our current branding (See #602)

**Comment by davidmolina** [comment]
@kjaymiller, good call. I can put these in AWS and share in the links this week.
