### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by CdiegoBB** [OperationCode/operationcode#616]
Please use one of the following templates to create new issues:

For a new feature:
As a DEVELOPER,
When I START SERVICE THIN START --SSL
It should I HAVE THE MESSAGE IN MY BROWSER ECONNREFUSED, MAYBE IS FOR DE REDIS

Hi rickr i try to deploy the website in my pc, i want to be a colaborator, thefore when i start the service with Thin start --ssl i have a message "ECONNREFUSED" with the Redis and i do not know why, i have all the software that you write in the contribute.

**Comment by rickr** [comment]
What's the URL you're going to?

**Comment by CdiegoBB** [comment]
Hi rickr i try to deploy the website in my pc, i want to be a colaborator, thefore when i start the service with Thin start --ssl i have a message "ECONNREFUSED" with the Redis and i do not know why, i have all the software that you write in the contribute.

**Comment by rickr** [comment]
Could you please attach a screenshot or some logs?

**Comment by CdiegoBB** [comment]
Nevermind is working right now, hahaha I do not know if was the internet conection or what. Therefore i will begin to contribute with this cute project.
