### ISSUE TITLE
Add user database to CRM

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#617]
As an admin, I would like the CRM to hold our user database, so that we can begin linking our user database to other automated actions.

At the moment, we have users lists in partial, and in a number of different areas. We need to get our whole user list in Airtable under a single base and table, and then begin building systems off of that. Since we can't refer to multiple bases, this is going to have to suffice.

**Comment by rickr** [comment]
This gem will help get this going: https://github.com/OperationCode/operationcode-airtable
