### ISSUE TITLE
Display donors

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#62]
Need a great way to display donors. Donors wall?

**Comment by emckenna** [comment]
maybe just stick some names in a yaml file and we can serve it up.

**Comment by davidmolina** [comment]
Right.

**Comment by davidmolina** [comment]
@emckenna get around permissions?

**Comment by davidmolina** [comment]
@emckenna something like [this](http://stackoverflow.com/questions/4002092/how-do-i-use-yaml-in-ruby-rails)?

**Comment by rickr** [comment]
Closing this out due to lack of activity. Please feel free to open a new issue if this is still needed.
