### ISSUE TITLE
Blog: Convert Medium blog post content to Markdown 

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/operationcode#620]
As a VISITOR,
When I visit the self-hosted blog at https://www.operationcode.org/blog,
I can read the same blog posts that have already been published to the Medium blog at https://medium.com/operation-code.

Additional Information: 
* Throughout 2016, there's been blog content posted to the Medium blog.  These long-form blog posts will need to be converted to Markdown so we can include them in the GitHub Pages blog we're planning.  The GitHub Pages blog will use Jekyll or other static-site generator.

See #576 (now closed)

Requirements (updated 3/8/2017): 

- [x] Convert all tag categories from Medium:
  - [x]  Member Stories
  - [x] Web Development
  - [x] Open Source
  - [x] Conferences
  - [x] News
<br>

- [x] Apply the existing tags on Medium (Member Stories, Web Development, Open Source, Conferences, News) as tags to the corresponding Jekyll markdown posts.

**Comment by sfillm07** [comment]
@jjhampton I was checking out what this was going to take to complete.  I created a branch and pushed it to my repo and was going to do a PR for someone to check out the markdown file.  This seems like a pretty simple task, if you would prefer me to do it I can.

**Comment by jjhampton** [comment]
Reopening this issue, I prematurely closed it.  Turns out there are still more blog posts on Medium to convert over to Markdown.

Only the 'Member Stories' tag category from Medium had all blog posts converted.  The other categories on the Operation Code [Medium blog](https://medium.com/operation-code) still have blog posts that need to be converted to Markdown and published to the [Jekyll blog](https://www.operationcode.org/blog).  

Updating requirements in the issue description w/ a checklist to reflect this.
