### ISSUE TITLE
Blog: Automate cross-posting of new blog posts to Medium

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/operationcode#622]
As an ADMIN,
When I publish a blog post on Operation Code's self-hosted blog,
It will automatically cross-post to Medium at https://medium.com/operation-code.

Potential Tools:
* Travis CI
* Medium API

See #576 (now closed)

**Comment by hollomancer** [comment]
https://github.com/Medium/medium-api-docs#33-posts

**Comment by jjhampton** [comment]
Plugin that may do what we need: https://github.com/aarongustafson/jekyll-crosspost-to-medium
