### ISSUE TITLE
Blog: Automate cross-posting of new blog posts to LinkedIn

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/operationcode#623]
As an ADMIN,
When I publish a blog post on Operation Code's self-hosted blog,
It will automatically cross-post to LinkedIn.

Potential Tools:
* Travis CI
* LinkedIn API

See #576 (now closed)

**Comment by hollomancer** [comment]
https://developer.linkedin.com/docs/share-on-linkedin

**Comment by hollomancer** [comment]
Contacted LinkedIn for support.

**Comment by sethbergman** [comment]
I'm working on a new app and I need a good purpose like this one. I'm thinking of using the Github API and register a hook that when a blog gets posted, it notifies the app to take the next action. We could use buffer or HubSpot to syndicate to all of the necessary social channels.
