### ISSUE TITLE
Allow mentors to sign up without emailing staff@operationcode.org

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#630]
As a visitor
When I click the footer 'Get Involved' Software Mentorship link
It should send me to a page to sign up.

This can either be /sign_up or whatever page is created in #629

**Comment by C-Lion** [comment]
I like to be assigned this issue.

**Comment by rickr** [comment]
It's all yours

**Comment by sdoyle0** [comment]
@rickr, should this be closed from #732
