### ISSUE TITLE
Add log of our livecoding.tv broadcasts

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#632]
So far, our livecoding.tv broadcasts stay on livecoding.tv. We should archive links to them on our site for later reference, maybe just a markdown file as an MVP.

Should be an easy one for someone to grab.

**Comment by mcolyer** [comment]
I'm interested in taking this on, do you mean just creating a page with links to all of the videos on: https://www.liveedu.tv/rickr/RLJY2-ruby-on-rails-operation-code/gQnLn-operation-code-9/.

Also did you have a specific url in mind for the page to live at?

**Comment by hollomancer** [comment]
@mcolyer, there are also some videos by @davidmolina there too.

You've got the idea, though. MVP is a markdown page under /docs, https://operationcode.org/livecoding would be the ideal location if it becomes a webpage.
