### ISSUE TITLE
As a new member, I want to land on a page that tells me what to do next, after I supply my email.

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#635]
Right now, after a new member signs up, they receive an email telling them to join Slack.

We need to better communicate to new users what they've signed up for, and what to do next. i.e.

1. User provides email.
2. User lands on a page with information telling them what they now have access to, as a member of Operation Code.
3. User learns that this information is provided via Slack.
4. User is provided a link to the desktop or mobile version of Slack.

**Comment by rickr** [comment]
After a user submits the form lets do the following:
- [ ] Add a new page that thanks the user for signing up, tells them to expect an email and an invitation to slack, and displays the slack download button.
- [ ] Update the sign up action to point to this new page

**Comment by sethbergman** [comment]
Would this be of any help?
[auto-join-slack](https://devslack.herokuapp.com)
Additional configuration is possible.

**Comment by rickr** [comment]
If that's the app I'm thinking of not really. It's just doing what we're doing in https://github.com/OperationCode/operationcode/blob/master/app/jobs/slack_inviter_job.rb

**Comment by sethbergman** [comment]
Ohh by the way, the reason this form doesn't work is because I'll need an admin API key.
https://api.slack.com/tokens
https://api.slack.com/docs/oauth-test-tokens

**Comment by sethbergman** [comment]
Ahh ok gotcha

**Comment by lsaville** [comment]
@rickr Does this still need doing? I'm looking to contribute to your project and would love to work on it if it hasn't been started by anyone else. Would the download slack button be an automatic download start or a redirect to Slack's [download page](https://slack.com/downloads/osx)?

**Comment by hollomancer** [comment]
It does! I think the button should be an automatic download, if possible.

We also need to consider the mobile-user case, for later.

**Comment by lsaville** [comment]
@hollomancer perhaps the mobile-user could be split into another issue/feature request? I don't have experience with mobile-specific development. I can still do the basic case if that sounds good to you. As far as specifics I'll plan on doing the general steps outlined by @rickr above.

**Comment by hollomancer** [comment]
Agreed, was 'thinking out loud' a bit there - mobile is out of scope for this story.

**Comment by technicalpickles** [comment]
It looks like there's a few other issues around this topic:

- add instructions to download slack desktop https://github.com/OperationCode/operationcode/issues/568
- remove zip code from flow https://github.com/OperationCode/operationcode/issues/570
- gather additional user information after sign up https://github.com/OperationCode/operationcode/issues/569

**Comment by lsaville** [comment]
@hollomancer @technicalpickles, I've begun work on this. Would the zip code then belong in the additional information gathering? Just for clarification, currently there is no 'inside' of the app for a veteran?

**Comment by technicalpickles** [comment]
@lsaville I only started looking at this app, but that is my understanding. I never got an password reset, so filed https://github.com/OperationCode/operationcode/issues/650 . It seems there the password reset is just a welcome email, but doesn't include a link to reset your password which means a veteran would be logged in at any point.

I was trying to thinking through how a landing page would be implemented. I think the veteran would need to be 'logged in' after registration, so they can update their zip and other information. I think they would also need to be prompted to reset their password as well.

**Comment by rickr** [comment]
We're not currently using profiles and I don't think we will be in the near future.

For this ticket I'd like a simple landing page covering the following things:
- [ ] Remove the current flash message
- [ ] Add a header thank the user for signing up
- [ ] Add a sub header telling the user there is one more step
- [ ] Add copy explaining how to join slack
- [ ] Add copy about how what slack is, how we use it and why
- [ ] User is presented with a download link for slack

If simple lets try to get the download to pop up automatically. 
Remember to keep mobile users in mind.

**Comment by rickr** [comment]
Fixed in #656
