### ISSUE TITLE
Add Placeholder Text For Forms

### ISSUE THREAD

**Issue by kylemh** [OperationCode/operationcode#636]
As a visitor, when I'd like to register to learn more about OC, I should be able to easily understand what type of info you'd like in the form inputs to the left of the TEACH ME HOW TO CODE button.

I believe it is necessary to have placeholder text to identify what information the form seeks to have entered.

Screenshot:
![screen shot 2017-02-19 at 5 31 48 pm](https://cloud.githubusercontent.com/assets/9523719/23108982/527a61f6-f6c9-11e6-92dd-df10a3b6d5db.png)

**Comment by rickr** [comment]
There's an email and zip code placeholder already there. Do you think they aren't visible enough?

**Comment by kylemh** [comment]
Holy crap. I'm gonna say yes, since I didn't even see them. I know I wear glasses, but I promise I'm near-sighted.

**Comment by hollomancer** [comment]
Maybe we can make the placeholder text darker, or a bit larger?

**Comment by sethbergman** [comment]
![operation code open source veterans non profit](https://cloud.githubusercontent.com/assets/8031689/23134230/a05c0c2c-f759-11e6-9853-cc259e6a46f9.png)

How about that? I can get right on this if you think it's the right move.

**Comment by rickr** [comment]
I don't think you captured the change? 

Regardless yea, we can make the text a tiny bit darker and bigger. Just be careful to make sure it still looks like a form. Maybe we update the placeholder text as well. 'enter your email' or something like that.

**Comment by sethbergman** [comment]
Yeah I'm looking at that right now. I was referring to @hollomancer 
![pic in slack](https://files.slack.com/files-pri/T03GSNF5H-F48ACAPFZ/pasted_image_at_2017_02_20_00_07.png)

Working on the form elements now. The CSS classes are all in materialize.min.css. Is this a file that gets bundled during the build? I'm not able to find that file name in the repo. At any rate this should fix it:
```
::-webkit-input-placeholder {
    color: #565656
}
```
Which CSS file is this in?

**Comment by sethbergman** [comment]
Ok I found it. It's in one of the cloudflare scripts. I can either:

1. Change that class over to a custom css class and copy the styles
2. Bring over materialize.min.css in an un-minified version and make the change there. I'd also have to change the reference from the script to the new css file.

**Comment by rickr** [comment]
Oh...that's being tracked in #637 

What do you mean by cloudflare scripts?

**Comment by sethbergman** [comment]
In application.html.erb:
 ``` <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css"></link>```

**Comment by rickr** [comment]
Ah I see. That's actually how we're loading materialize (the CSS framework we're using). It's just plain CSS and the only thing Cloud Flare is doing is hosting it for us.

You should be able to override this at https://github.com/OperationCode/operationcode/blob/master/app/assets/stylesheets/application.css.scss

**Comment by rickr** [comment]
Merged via #640
