### ISSUE TITLE
Join link in header is hard to read with current color scheme.

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#637]
![pasted image at 2017_02_20 00_07](https://cloud.githubusercontent.com/assets/9288648/23131590/8f475d66-f758-11e6-8b29-87ea217eaf1b.png)

I think the issue is in the footer, at;
`<% ab_test(:signup_button_size, 'btn btn-large', '') do |button_size| %>
<%= link_to 'Join', new_veteran_registration_path, class: button_size, style: 'background-color: #B23900;' %>
<% end %>`

![pasted image at 2017_02_20 00_08](https://cloud.githubusercontent.com/assets/9288648/23131618/a58b181a-f758-11e6-9b90-9dcb87c50981.png)

To fix this we need to update the following line: 

`<% ab_test(:signup_button_size, 'btn btn-large', '') do |button_size| %>`

To read:

`<% ab_test(:signup_button_size, 'btn btn-large', 'btn') do |button_size| %>`

**Comment by rickr** [comment]
This has been reported before and it was due to caching. If you clear your cache does the button go back to normal? After you clear the cache and reload the page does it bug out again?

**Comment by hollomancer** [comment]
I think the A/B test might be the culprit here. I refreshed five times, and it looks different 3/5 times.

**Comment by rickr** [comment]
Ah yea - that's exactly it.

**Comment by sethbergman** [comment]
This is what the button looks like with `btn btn-large`:
![operation code-btn-btn-large](https://cloud.githubusercontent.com/assets/8031689/23144074/c12eeede-f78a-11e6-8aef-9647be846e94.png)

This is what it looks like with `btn`:
![operation code-btn](https://cloud.githubusercontent.com/assets/8031689/23144101/ff2e0d1e-f78a-11e6-8842-931a08863c40.png)

I think that `btn` looks much better. Please advise

**Comment by rickr** [comment]
Merged via #639
