### ISSUE TITLE
Donate button on home page takes us to the old donation page

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#643]
As a VISITOR
When I visit https://operationcode.org and scroll to the bottom of the page to the DONATE NOW button
It takes me to https://operationcode.org/square.
It should take me to https://donorbox.org/operationcode

We should check for any other donation related links and fix those as well.

**Comment by rickr** [comment]
@codejordancode is going to be working this.

**Comment by sethbergman** [comment]
@rickr I got this.
import assignment from './issues';
import service from 'seth';
let this.assignment = (seth) => {
   return true;
}

**Comment by sethbergman** [comment]
Ahh I must have not seen this. Give me something else then @rickr

**Comment by rickr** [comment]
Fixed in #645
