### ISSUE TITLE
CONTRIBUTING.md lacks appropriate setup instructions

### ISSUE THREAD

**Issue by sethbergman** [OperationCode/operationcode#644]
As a new contributor / member,
When I go through all of the setup instructions:
- I get errors in my terminal relating to setting up the database.
- I also have problems with file permissions and the pg gem.

The setup instructions should have sufficient, easy to follow instructions for getting the site running locally.

I'm running Linux Mint 18, a hybrid of Ubuntu 16.04 and Debian.
- Kernel version 4.4.0-62-generic x86_64 GNU/Linux

**Comment by rickr** [comment]
Can you please paste the errors you receive?

**Comment by sethbergman** [comment]
@rickr I'll take this one. I'll write it up today and knock it out.

**Comment by sethbergman** [comment]
running “bundle install” yields:

[4:55]  
Fetching source index from https://rubygems.org/
Fetching https://github.com/stripe/stripe-ruby
Could not verify the SSL certificate for
https://rubygems.org/quick/Marshal.4.8/actionmailer-4.2.5.2.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system
doesn't have the CA certificates needed for verification. For information about OpenSSL
certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile
sources and change 'https' to 'http'.
github.com
GitHub - stripe/stripe-ruby: Stripe Ruby bindings
stripe-ruby - Stripe Ruby bindings

**Comment by sethbergman** [comment]
Could not verify the SSL certificate for
https://rubygems.org/quick/Marshal.4.8/actionmailer-4.2.5.2.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system
doesn't have the CA certificates needed for verification. For information about OpenSSL
certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile
sources and change 'https' to 'http'.

**Comment by sethbergman** [comment]
[Archive of Slack messages](https://operation-code.slack.com/archives/operationcode-dot-org/p1487716126001603)
@codejordancode is on Mac OSX

**Comment by rickr** [comment]
Fixed in #668
