### ISSUE TITLE
Markdown resume

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#65]
Build a markdown resume that compiles into a PDF based on DocBook (http://docbook.org) or Latex (http://www.latex-project.org) possibly. Or Prawn. Help standardize the process for our veteran coders, automate the process.

**Comment by ericelliott** [comment]
Great project!

**Comment by davidmolina** [comment]
Thanks Eric! Welcome your support: 
https://github.com/OperationCode/operationcode/blob/master/CONTRIBUTING.md.

**Comment by ericelliott** [comment]
I'm doing something similar. See the [JSHomes Platform](https://github.com/jshomes/JSHomes-Platform) project. We're creating a high-quality environment for people to learn how to code, and releasing the whole thing as open source. =)

**Comment by davidmolina** [comment]
Awesome. Will take a look.

**Comment by davidmolina** [comment]
Eric, absolutely love it. As you already know veterans homelessness is one of our issues. Love to include your organization as we apply for grants to solve this problem.

**Comment by ericelliott** [comment]
:+1:

**Comment by jjhampton** [comment]
Might be able to get some ideas from this project: https://github.com/ellekasai/resumecards
Also may want to check out Pandoc: http://pandoc.org/

**Comment by davidmolina** [comment]
Those aren't bad at all.

**Comment by rickr** [comment]
Closing this out due to lack of activity. Please feel free to open a new issue if this is still needed.
