### ISSUE TITLE
Did not receive email with password reset instructions

### ISSUE THREAD

**Issue by technicalpickles** [OperationCode/operationcode#650]
As a visitor
When I register
It does not send me an email with password reset instructions
It should send me an email with password reset instructions

I registered yesterday, and I received a "Welcome to Operation Code" email with information about Slack, and an invite to the Slack.

Reading over `Veterans::RegistrationController`, it seems like it should be sending an email with reset: https://github.com/OperationCode/operationcode/blob/0bc01628d09415ed520df45a9a5b75dcb9d372fb/app/controllers/veterans/registrations_controller.rb#L26-L32 . While testing in development, I also get a new window open with the sent Welcome email but not the registration.

This `@veteran.send_reset_password_instructions` seems to come from [devise](https://github.com/plataformatec/devise)'s [recoverable](http://www.rubydoc.info/github/plataformatec/devise/master/Devise/Models/Recoverable) which is [set in `Veteran`](https://github.com/OperationCode/operationcode/blob/0bc01628d09415ed520df45a9a5b75dcb9d372fb/app/models/veteran.rb#L22)

**Comment by technicalpickles** [comment]
Forgot to mention I checked my spam folder, and didn't see anything there either.

**Comment by technicalpickles** [comment]
With a tip from @sfillm07 in slack, the welcome email *is* the password reset: https://github.com/OperationCode/operationcode/blob/0bc01628d09415ed520df45a9a5b75dcb9d372fb/app/views/devise/mailer/reset_password_instructions.html.erb

**Comment by rickr** [comment]
We had this functionality but then removed it to focus on shoring up our UX on slack.

Closing this out as if we choose to turn on profiles again we should be covered by devise.
