### ISSUE TITLE
Add PR guidelines to docs

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#686]
As a visitor, when I file a PR, I should file it with the designated issue# as the name of the branch.

**Comment by rickr** [comment]
This has already been started at https://github.com/operationcode/operationcode/blob/master/CONTRIBUTING.md#submitting-your-changes

I think a clearer title and a checklist in `PULL_REQUEST_TEMPLATE.md` will help.

**Comment by josephrebolledo** [comment]
Is this still open? Can I claim this?
