### ISSUE TITLE
Move from Heroku to Rancher

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#687]
- [x] Get docker compose running
- [x] Configure travis to push to Docker hub if master
- [x] Deploy rancher stack
- [x] Get HTTPS cert
- [ ] Flip over CNAME
- [x] File a ticket for psql backups (#690)
- [x] Update CONTRIBUTING.md

**Comment by sethbergman** [comment]
Let me know if I can do any of these tasks.
