### ISSUE TITLE
Add Make install instructions for Windows to CONTRIBUTING.md

### ISSUE THREAD

**Issue by coffeehorn** [OperationCode/operationcode#704]
As a new developer, when I try to set up my development environment following the instructions in the CONTRIBUTING.md on Windows, I get an error after trying to use the command `make`.  The CONTRIBUTING.md file should be update that make is also a required install for windows.

**Comment by jjhampton** [comment]
Agree that this should be added, as Windows lacks `make` command out of the box.

Make for Windows can be found here: http://gnuwin32.sourceforge.net/packages/make.htm
We should probably have some instructions for beginners on how to properly install it and add it to PATH so it can be ran from the command-line.

**Comment by coffeehorn** [comment]
I'll volunteer to add content to this

**Comment by rickr** [comment]
Thanks @coffeehorn. I don't have a windows machine to test this out on so your help is invaluable!

**Comment by rickr** [comment]
Fixed in #705
