### ISSUE TITLE
Operation Code website outage - 3/17/2017

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/operationcode#706]
As a VISITOR,
When I visit https://www.operationcode.org ~(or any variation of the domain)~
It displays an error message
It should display the Operation Code website

Additional Information:
![screenclip](https://cloud.githubusercontent.com/assets/8835055/24068673/3827a58c-0b6b-11e7-999a-e59704bdc8a9.png)

Occurred sometime after merging #702 and automated build/deploy.

Sentry error message related to the database:
https://sentry.io/auth/login/operation-code/

**Comment by jjhampton** [comment]
Looks like `https://operationcode.org` is working, but `https://www.operationcode.org` returns a 503 error now.

**Comment by rickr** [comment]
RFO  appears to be our psql host being restarted and our data volume not being moved along with the app container. When I discovered the problem I recreated the DB on the new host, ran migrations, and imported one of our psql dumps.

Next steps: Get rancher NFS (or some other persistence) running
