### ISSUE TITLE
Update github templates

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#709]
* Add a checklist for PRs
* Update the current issue templates to use markdown/headers. The idea is to not have people delete things and to act more like a form.

**Comment by hd719** [comment]
Hello there! I am new to open source source and I would like to contribute.

**Comment by hollomancer** [comment]
@hd719 All yours!

**Comment by hd719** [comment]
Hey @hollomancer do you want a generalized pull request checklist or a pull request checklist based on the repository standards (https://github.com/OperationCode/operationcode)? 

-Thank you.

**Comment by rickr** [comment]
Lets start with this text for PRs (taken from the list [here](https://github.com/operationcode/operationcode/blob/master/CONTRIBUTING.md#submitting-your-changes)):

```
## Description of changes

## Pull Request Checklist
This pull request:
- [ ] is tied to a single issue
- [ ] has appropriate tests
- [ ] does not break existing tests
```
Please feel free to make suggestions on how this could be better!

**Comment by hd719** [comment]
@rickr @hollomancer Sorry for bother, but any update on the pull request?

**Comment by rickr** [comment]
Hey @hd719. Apologies for the delay. I've been super underwater lately. I'll try to get to this today.

**Comment by hd719** [comment]
@rickr Oh no worries take your time!
