### ISSUE TITLE
[location].operationcode.org pages should feature their chapter

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#712]
This is an epic for the future and needs to be broken down into smaller stories.

As a chapter leader, I would like a dedicated page for my chapter, that gives me a web presence aligned with operationcode.org.

The population of this page should be automated, grabbing future meetups / membership from Meetup, and grabbing sponsorships from OpenCollective.

**Comment by davidmolina** [comment]
This is uuuge.

**Comment by dreamsincode** [comment]
Interested in helping out with this one

**Comment by hollomancer** [comment]
@dreamsincode, all yours. You'll need to check out the Meetup Pro API to pull some of this info https://www.meetup.com/pro/operationcode/

**Comment by rickr** [comment]
I was thinking we could do this statically via github pages to reduce hosting costs. Each section would get their own repo they could manage and modify as they wanted.

**Comment by davidmolina** [comment]
Static pages could work.

**Comment by aayushgoyal1** [comment]
I'm interested in helping out

**Comment by hollomancer** [comment]
All yours - send a PR and let's check it out!
