### ISSUE TITLE
As a visitor, when I read CONTRIBUTING.md, it should explain what "Install Docker" means

### ISSUE THREAD

**Issue by aaron-suarez** [OperationCode/operationcode#716]
The phrase "Install Docker" and linking to docker.com is unsat. It should at the very least say "Install Docker Desktop for your OS" and link to the download page for each OS (Windows, Mac, Linux). Because there is no page on docker.com for installing Docker Desktop on Linux, it should link to the correct tutorial to install Docker on Linux.

I'll take this issue if anyone wants to assign it to me. Expect a PR shortly.

**Comment by rickr** [comment]
All yours!

**Comment by rickr** [comment]
Fixed in #717
