### ISSUE TITLE
Transparent landing page text

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#72]
Need to add a transparent block behind the landing page text. A bit difficult to read for some.

**Comment by rjcox** [comment]
I added a simple transparent box behind the text. I will work on trying to make it a blurred window of what's behind it tomorrow.

**Comment by davidmolina** [comment]
Awesome. Will pull down in the am.

**Comment by alexkaufman06** [comment]
Did this ever get resolved?

**Comment by davidmolina** [comment]
Somewhat. Yes.

**Comment by KevinRoss-** [comment]
Can we close this issue?
