### ISSUE TITLE
Links within README.md's "Setting up your environment" section

### ISSUE THREAD

**Issue by jaitjacob** [OperationCode/operationcode#723]
As a VISITOR,
When I open [readme.md], I find trouble setting up the environment because certain links pointing to the location of required software is not up and running. Can we have an alternative for that, like a different method to set up the required environment.
It should make it easy for anyone who is coming to the repository for the first time and wants to get started with the code.

**Comment by hd719** [comment]
Hey @jaitjacob when you set up the development env. when you run `make setup` are you getting any errors? I am getting this one 

```
Hamels-MacBook-Air:operationcode-upstream HD$ make setup
docker-compose run web rake db:create
rake aborted!
NameError: Cannot load `Rails.application.database_configuration`:
uninitialized constant OperationCode
(erb):7:in `<main>'
/usr/local/bundle/gems/railties-4.2.5.2/lib/rails/application/configuration.rb:104:in `dat
abase_configuration'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/railtie.rb:41:in `block (3 l
evels) in <class:Railtie>'
/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
NameError: uninitialized constant OperationCode
(erb):7:in `<main>'
/usr/local/bundle/gems/railties-4.2.5.2/lib/rails/application/configuration.rb:104:in `dat
abase_configuration'
/usr/local/bundle/gems/activerecord-4.2.5.2/lib/active_record/railtie.rb:41:in `block (3 l
evels) in <class:Railtie>'
/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create => db:load_config
(See full trace by running task with --trace)
make: *** [db_create] Error 1
```

I have Docker up and running for mac as well as Postgres. 

-Thanks

**Comment by rickr** [comment]
@jaitjacob Can you be a bit more specific? What links were not up and running? Where are you getting hung up?

**Comment by jaitjacob** [comment]
@rickr  I was talking about the " GNUWin general installation guide" link which is used to install the Make tool for windows. The zip file required for installing "Make" within that page has been down because of some internal server error. I don't think we can fix that other than specifying an alternative for "Make" for Windows.
More clarification, I am talking about the download link within this link "http://gnuwin32.sourceforge.net/install.html"

**Comment by jaitjacob** [comment]
@hd719 Hi there, I was on my Windows PC and I had a lot of trouble with installation. I'll be switching to my Linux  and trying this out. Will let you know if i face any issues. Which OS do you work upon by the way?

**Comment by hd719** [comment]
@jaitjacob So I was using a mac, but @rickr fixed the bug and it works now, just make sure you pull in the latest changes from the master branch.

**Comment by rickr** [comment]
Ok. Since this appears to be fixed I'm going to go ahead and close this issue.

Thanks for the heads up!
