### ISSUE TITLE
Add /gala page

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#730]
As a visitor,
When I visit /gala
There should be a page highlighting our Gala fundraiser, including, location, date & time, quick summary, planning committee co-chairs & members (along w/ their Slack handle), sponsorship prospectus, a way for companies to pay for a table or seats.

**Comment by hollomancer** [comment]
We need copy for this.

**Comment by davidmolina** [comment]
Nov 10, 2017
Governor's Ballroom, Sentinel Hotel
Portland, Oregon

**Comment by rickr** [comment]
Going to track this in operationcode/operationcode_frontend#44.

**Comment by kylemh** [comment]
Any images or format you'd like this page in?

*claimed*
