### ISSUE TITLE
Add Thomas to /board

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#735]
Thomas Ciszek (@ciszek) currently leads media and entertainment research at Twitter in Los Angeles. Mr. Ciszek previously co-founded Cojoin, a Launchpad LA startup and attended University of North Carolina on the Morehead Scholarship where he earned a Master of Science in Information Science.

**Comment by fredosantana** [comment]
I can take care of this. Have a PR for #728 waiting to be merged that's similar to this.
