### ISSUE TITLE
Add Tyrone to /board

### ISSUE THREAD

**Issue by hollomancer** [OperationCode/operationcode#738]
Dr. Tyrone Grandison (@tgrandison) is the CIO of the Institute for Health Metrics and Evaluation (IHME) at the University of Washington. He previously served as a White House Presidential Innovation Fellow working with the US Department of Labor, and co-founded the Commerce Data Service at the US Department of Commerce.

@davidmolina, this look ok?

**Comment by davidmolina** [comment]
Perfect

**Comment by Kevffeine** [comment]
Can I claim this

**Comment by rickr** [comment]
Absolutely! All yours.
