### ISSUE TITLE
Updates to Styling of Press section on Homepage and Press Page

### ISSUE THREAD

**Issue by jdivo** [OperationCode/operationcode#743]
As a Vistor,
When I visit the homepage and Press page
It does not match design of rest of sight.
It should look like the rest of the site from a styling perspective.

Additional Information (eg browser version, screenshots etc):

I was hoping to contribute to this project as part of a software engineering bootcamp I am enrolled in by updating the styling of the Press section on the homepage as well as the Press page itself. It appears there is a newer project in the works (operationcode_frontend & operationcode_backend) and I was wondering where it would be best to contribute.

Thanks!
Jason

**Comment by rickr** [comment]
@jdivo - we'd love your help!

OperationCode/operationcode_frontend is 1 or 2 issues from being deployed so if you'll be working on this for a few weeks I'd say that's the best place to make this change. 

Are you comfortable with react?

**Comment by jdivo** [comment]
@rickr - I do plan on spending some time over the next few weeks and am comfortable with both react and rails so will take a look at current issues for both frontend and backend and continue the conversation there!

**Comment by rickr** [comment]
Ok then. See you over there! I'm going to close this out.
