### ISSUE TITLE
ID.me integration

### ISSUE THREAD

**Issue by rickr** [OperationCode/operationcode#747]
operationcode/operationcode_frontend#20
operationcode/operationcode_frontend#125
operationcode/operationcode_frontend#124
operationcode/operationcode_frontend#118
operationcode/operationcode_backend#38

**Comment by Cooperbuilt** [comment]
Unless there is more integration needed, I think we have this one solved and can close.

**Comment by Hiren-Mehta** [comment]
Yeah, that's what I was thinking at https://operation-code.slack.com/archives/C04FASBU9/p1504883471000152

**Comment by hollomancer** [comment]
Agreed.
