### ISSUE TITLE
Add example config/application.yml file

### ISSUE THREAD

**Issue by emckenna** [OperationCode/operationcode#76]
Figaro gem (https://github.com/laserlemon/figaro) uses application.yml to hold its values and setup asks to add application.yml to gitignore.  BUT, for others to get running, we need example copy of application.yml file.

so add
config/application.example.yml

be sure this file has all the required keys with default/fake values for things that should be secret (token keys, ids, api keys, etc)

Also add setup directions to contrib page.  (basically just copy application.example.yml to application.yml)

**Comment by davidmolina** [comment]
Awesome. Let me get this one going first and will add this next.

**Comment by davidmolina** [comment]
Got it.

On Thu, Jul 2, 2015 at 1:36 PM, Eric Mckenna <notifications@github.com>
wrote:

> Figaro gem (https://github.com/laserlemon/figaro) uses application.yml to
> hold its values and setup asks to add application.yml to gitignore. BUT,
> for others to get running, we need example copy of application.yml file.
>
> so add
> config/application.example.yml
>
> be sure this file has all the required keys with default/fake values for
> things that should be secret (token keys, ids, api keys, etc)
>
> Also add setup directions to contrib page. (basically just copy
> application.example.yml to application.yml)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/76>.
>



-- 
David
t. @davidcmolina <https://twitter.com/davidcmolina>
http://davidmolina.github.io/

**Comment by rickr** [comment]
Closing this out due to lack of activity. Please feel free to open a new issue if this is still needed.
