### ISSUE TITLE
Code School Scholarships title CSS Misalignment

### ISSUE THREAD

**Issue by Programazing** [OperationCode/operationcode#762]
I noticed at my screen resolution, `1366 x 768`, the title of this section is displayed incorrectly.

![css](https://user-images.githubusercontent.com/11393826/30996429-ddc0118e-a48e-11e7-969c-c4c3f0559de7.png)

**Comment by jjhampton** [comment]
Quick fix that wouldn't require any changes to CSS - change the text content of the `h6` element to from 'Code School Scholarships' to just 'Scholarships'

**Comment by jjhampton** [comment]
Closing, moved this issue to the front-end repo: https://github.com/OperationCode/operationcode_frontend/issues/511
