### ISSUE TITLE
Add validations for donations

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#79]
If a donor forgets to add their email, donation still goes through, but need to require their email to provide a receipt copy for their tax filings. Nonprofit requirement.

**Comment by superscott** [comment]
(☞ﾟ∀ﾟ)☞

**Comment by davidmolina** [comment]
Thanks @superscott! /cc @cenderin @gxespino

**Comment by superscott** [comment]
Form validation is fixed, should open additional issues or whatnot for the fixes for https://github.com/OperationCode/operationcode/blob/master/app/models/donation.rb#L4-L6

**Comment by davidmolina** [comment]
This commit 554c594 fixes this issue.
