### ISSUE TITLE
Add b-roll video top of page. 

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#8]
Add transparent nav-bar.

**Comment by davidmolina** [comment]
@alexkaufman06 -- can you attack this? Thanks man!

**Comment by alexkaufman06** [comment]
Just finished adding the video and text.  It is now fully responsive on both chrome and safari.  We just have to check the phone view next.

**Comment by davidmolina** [comment]
Looking great-- thanks @alexkaufman06!
