### ISSUE TITLE
Use better typography

### ISSUE THREAD

**Issue by nanoxd** [OperationCode/operationcode#84]
IMO we should use a different font or alter our font weight. For a good example of why look at the following: 
![operation code veteran coders 2015-07-15 16-04-06](https://cloud.githubusercontent.com/assets/1889575/8711934/3f2675e4-2b0b-11e5-86fa-1125bf92ed54.png)

Everything looks like it's bold unless it's a link. There should be some more delineation and possibly a smaller font used.

**Comment by nanoxd** [comment]
Our Mission does not exhibit this issue.

**Comment by davidmolina** [comment]
Sounds good.

On Wed, Jul 15, 2015 at 4:06 PM, Fernando Paredes <notifications@github.com>
wrote:

> Our Mission does not exhibit this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/84#issuecomment-121772741>
> .
>



-- 
David
t. @davidcmolina <https://twitter.com/davidcmolina>
http://davidmolina.github.io/

**Comment by davidmolina** [comment]
Hmmm. I'll take another look. Something in the HTML/CSS.

**Comment by davidmolina** [comment]
This commit 5c3d3aa9372e1342827f12ee5fdf94c7feae1141 fixes this.
