### ISSUE TITLE
Code Schools/Hackathons has extra spacing from header

### ISSUE THREAD

**Issue by nanoxd** [OperationCode/operationcode#85]
Code Schools has extra spacing that is not present on other pages. It should look like other pages.

![operation code veteran coders 2015-07-15 16-07-10](https://cloud.githubusercontent.com/assets/1889575/8711964/8f30c666-2b0b-11e5-8ed1-fdf94a063801.png)

**Comment by davidmolina** [comment]
Cornelius had a good suggestion. Separate it. Example:
codeschool.operationcode.org. And, map it. Thoughts?

On Wed, Jul 15, 2015 at 4:07 PM, Fernando Paredes <notifications@github.com>
wrote:

> Code Schools has extra spacing that is not present on other pages. It
> should look like other pages.
>
> [image: operation code veteran coders 2015-07-15 16-07-10]
> <https://cloud.githubusercontent.com/assets/1889575/8711964/8f30c666-2b0b-11e5-8ed1-fdf94a063801.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/85>.
>



-- 
David
t. @davidcmolina <https://twitter.com/davidcmolina>
http://davidmolina.github.io/

**Comment by nanoxd** [comment]
I have no problem with that. It allows us to change the layout to something more appropriate for that page.

**Comment by davidmolina** [comment]
Exactly.

On Wed, Jul 15, 2015 at 4:19 PM, Fernando Paredes <notifications@github.com>
wrote:

> I have no problem with that. It allows us to change the layout to
> something more appropriate for that page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OperationCode/operationcode/issues/85#issuecomment-121774314>
> .
>



-- 
David
t. @davidcmolina <https://twitter.com/davidcmolina>
http://davidmolina.github.io/

**Comment by davidmolina** [comment]
This commit 3d1e4ad8a7561f2e629761f005681ff4e572efde fixes this.
