### ISSUE TITLE
Add SSL certificate

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#86]
Regardless of Stripe not hitting Heroku, adding SSL to ensure no one brings this point up again.

**Comment by davidmolina** [comment]
$ dig operationcode.org mx

; <<>> DiG 9.8.3-P1 <<>> operationcode.org mx
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59695
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;operationcode.org.		IN	MX

;; ANSWER SECTION:
operationcode.org.	3203	IN	MX	1 ASPMX.L.GOOGLE.COM.
operationcode.org.	3203	IN	MX	10 ALT3.ASPMX.L.GOOGLE.COM.
operationcode.org.	3203	IN	MX	5 ALT2.ASPMX.L.GOOGLE.COM.
operationcode.org.	3203	IN	MX	10 ALT4.ASPMX.L.GOOGLE.COM.
operationcode.org.	3203	IN	MX	5 ALT1.ASPMX.L.GOOGLE.COM.

;; Query time: 30 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Thu Jul 16 23:31:58 2015
;; MSG SIZE  rcvd: 153

---
Shows our MX records are correct. Working w/ host provider to white list SSL provider verification email.

**Comment by davidmolina** [comment]
Added SSL certificate for Heroku test site. However: 
$ heroku certs:add CRT KEY --app opcod3
Resolving trust chain... failed
 !    Unable to read CRT file: No such file or directory @ rb_sysopen - CRT

**Comment by cavalryjim** [comment]
David, 

I haven't been following this discussion very closely so forgive me if this  is not the solution you need. Instead of paying a for a certificate, I use CloudFlare. It gives you SSL and a whole lot more....plus there is a free level of service. 

Regards,
James

**Comment by davidmolina** [comment]
James, I'd do that but just dropped $100 already for this SSL certificate. Stuck on the download .zip, some command lines part. Error'ing up.

**Comment by davidmolina** [comment]
James, for CloudFlare I'm seeing "most modern browsers" for SSL. Issue? https://www.cloudflare.com/plans

**Comment by cavalryjim** [comment]
I've never encountered a problem with an unsupported browser.  If someone
is using a non-HTML5 browser, shame on them.

**Comment by davidmolina** [comment]
@cavalryjim 
(1) requested a new certificate. The other certificate keys were compromised. 
(2) [last step](https://devcenter.heroku.com/articles/ssl-endpoint) failed: 
$ heroku certs:add CRT KEY --app opcod3
Resolving trust chain... failed
 !    Unable to read CRT file: No such file or directory @ rb_sysopen - CRT

**Comment by cavalryjim** [comment]
Truthfully, it has been years since I used a legacy SSL certificate. With the advent of CloudFlare, and other cloud-based solutions, I gladly made to move from the pain of fighting with SSL certificates.

**Comment by davidmolina** [comment]
@cavalryjim I'm nearing that decision. Part of me feels to persevere through their [docs](https://support.comodo.com/index.php?/Default). I already have the certificate, but failing in the [Heroku instructions](https://devcenter.heroku.com/articles/ssl-endpoint) to properly call the certificate and activate it.

**Comment by davidmolina** [comment]
@cavalryjim beyond encrypting the CDN side, need it to encrypt the base site. For CloudFlare.

**Comment by davidmolina** [comment]
Somewhere I missed a step. 

$ heroku certs:add server.crt server.key --app opcod3
Resolving trust chain... failed
 !    Unable to read server.crt file: No such file or directory @ rb_sysopen - server.crt

**Comment by davidmolina** [comment]
Revisiting: 
https://devcenter.heroku.com/articles/ssl-certificate-dnsimple#wildcard-domain and https://robots.thoughtbot.com/ssl-for-rails-with-heroku-and-dnsimple.

**Comment by davidmolina** [comment]
This commit 473bcab0e6afb36bf7721bc4fbc7d649737664c9 fixes this.
