### ISSUE TITLE
Add paypal as a donate option

### ISSUE THREAD

**Issue by davidmolina** [OperationCode/operationcode#92]

**Comment by davidmolina** [comment]
Pending bank transfer to complete final process.

**Comment by davidmolina** [comment]
Must get done ASAP.

**Comment by davidmolina** [comment]
Add to header.

**Comment by rickr** [comment]
@davidmolina is this still needed?

**Comment by davidmolina** [comment]
Rick, negative. Close issue.

Seperately issue, add additional donation options, ex. $5, $10, $20... $2000
